In [1]:
from lwpackage.lwmongo import *
from lwpackage.lwdata import *

In [7]:
from mongo.mongify import list_database_details

res = list_database_details()  # 全部非系统库

====================================================================================================
MongoDB Database Summary
     database  collections   objects  data_size_mb  storage_size_mb  \
0       stock            6  17472265   2166.137608       804.199219
1     futures            2    170685     22.910389         8.246094
2  mydatabase            1         7      0.000305         0.035156

   index_size_mb  avg_obj_size_bytes
0     219.808594          129.998023
1       1.648438          140.746310
2       0.035156           45.714286
====================================================================================================
MongoDB Collection Summary
     database                       collection     count      size_mb  \
0       stock                      price_daily  10147824  1258.103485
1       stock                       price_1min   5095515   631.730032
2       stock                       price_5min   2139705   265.275621
3     futures  continuous_contract_price_daily    170610    22.904017
4       stock                    instrument_id     79167     9.814939
5       stock                  instrument_info      5553     0.796969
6       stock                   risk_free_rate      4501     0.416560
7  mydatabase                        customers         7     0.000305
8     futures         continuous_contract_info        75     0.006371

   storage_size_mb  avg_obj_size_bytes  nindexes  total_index_size_mb  capped
0       451.667969                 130         1           107.136719   False
1       176.496094                 130         1            54.363281   False
2       169.765625                 130         1            57.054688   False
3         8.226562                 140         1             1.628906   False
4         5.425781                 130         1             1.105469   False
5         0.605469                 150         1             0.078125   False
6         0.238281                  97         1             0.070312   False
7         0.035156                  45         1             0.035156   False
8         0.019531                  89         1             0.019531   False
====================================================================================================

In [10]:
res['database_summary']

,database,collections,objects,data_size_mb,storage_size_mb,index_size_mb,avg_obj_size_bytes
0,stock,6,17472265,2166.137608,804.199219,219.808594,129.998023
1,futures,2,170685,22.910389,8.246094,1.648438,140.746310
2,mydatabase,1,7,0.000305,0.035156,0.035156,45.714286

In [11]:
res['collection_summary']

,database,collection,count,size_mb,storage_size_mb,avg_obj_size_bytes,nindexes,total_index_size_mb,capped
0,stock,price_daily,10147824,1258.103485,451.667969,130,1,107.136719,False
1,stock,price_1min,5095515,631.730032,176.496094,130,1,54.363281,False
2,stock,price_5min,2139705,265.275621,169.765625,130,1,57.054688,False
3,futures,continuous_contract_price_daily,170610,22.904017,8.226562,140,1,1.628906,False
4,stock,instrument_id,79167,9.814939,5.425781,130,1,1.105469,False
5,stock,instrument_info,5553,0.796969,0.605469,150,1,0.078125,False
6,stock,risk_free_rate,4501,0.416560,0.238281,97,1,0.070312,False
7,mydatabase,customers,7,0.000305,0.035156,45,1,0.035156,False
8,futures,continuous_contract_info,75,0.006371,0.019531,89,1,0.019531,False

In [2]:
import akshare as ak

In [3]:
df_futures_info = ak.futures_display_main_sina()

In [4]:
df_futures_info

   symbol exchange   name
0      V0      dce  PVC连续
1      P0      dce  棕榈油连续
2      B0      dce   豆二连续
3      M0      dce   豆粕连续
4      I0      dce  铁矿石连续
..    ...      ...    ...
77    SI0     gfex  工业硅连续
78    LC0     gfex  碳酸锂连续
79    PS0     gfex  多晶硅连续
80    PT0     gfex    铂连续
81    PD0     gfex    钯连续

[82 rows x 3 columns]

In [5]:
df_futures = ak.futures_main_sina()

In [6]:
df_futures

              日期   开盘价   最高价   最低价   收盘价      成交量      持仓量  动态结算价
0     2009-05-25  6575  6630  6435  6490   107764    12278      0
1     2009-05-26  6485  6540  6445  6460    38290    10562      0
2     2009-05-27  6500  6535  6460  6485    34002    10346      0
3     2009-06-01  6555  6595  6520  6570    26178    10352      0
4     2009-06-02  6590  6590  6545  6555    13496     9388      0
...          ...   ...   ...   ...   ...      ...      ...    ...
4066  2026-03-04  4970  5053  4894  4995  2612767  1065884   4970
4067  2026-03-05  4984  5099  4927  5016  2676049  1078460   5019
4068  2026-03-06  5040  5298  5020  5276  3114407  1143319   5157
4069  2026-03-09  5400  5466  5335  5466  2453088  1072148   5419
4070  2026-03-10  5500  5525  4986  5229  2639433   914632   5274

[4071 rows x 8 columns]

In [2]:
drop_duplicated_data(database='stock', collection='price_1min', subset=['time', 'instrument_id'])

Successfully insert 5091624 records into stock.price_1min.

In [3]:
drop_duplicated_data(database='stock', collection='price_5min', subset=['time', 'instrument_id'])

Successfully insert 2134831 records into stock.price_5min.

In [3]:
database = 'stock'
collection = 'price_1d'

In [6]:
df = get_data(database, collection)

In [11]:
df.drop_duplicates(subset=['time', 'instrument_id'])

        time instrument_id  close   high    low  open  volume
0 2001-01-02        600795  35.50  35.65  35.19  35.2    2939
1 2001-01-02        000911  12.84  12.99  12.66  12.9    5380
2 2001-01-02        000778  15.05  15.10  14.40  14.6   59455
3 2001-01-02        000088  15.05  15.40  14.18  14.2   81481
4 2001-01-02        600808   3.94   3.96   3.86   3.9   38431
5 2001-01-02        600771  35.50  35.65  35.19   0.0    2939
6 2018-01-02        300191  23.05  23.30  22.47  22.7   19038

In [9]:
df['time'].iloc[0]

Timestamp('2001-01-02 00:00:00')

In [1]:
import akshare as ak
import pandas as pd

In [1]:
from lwpackage.lwmongo import *

In [5]:
db = client['stock']

In [9]:
collection_stats = db.command("collstats", 'price_1min')
print(f"Collection size in bytes: {collection_stats['size']}")

Collection size in bytes: 306057050

In [2]:
df_stock = ak.stock_individual_info_em()

In [3]:
df_stock

   item          value
0   总市值  4664720324.88
1  流通市值  4664720324.88
2    行业           食品饮料
3  上市时间       20161012
4  股票代码         603777
5  股票简称            来伊份
6   总股本    336559908.0
7   流通股    336559908.0

In [4]:
df = ak.stock_zh_a_spot_em()

In [5]:
df

,序号,代码,名称,最新价,涨跌幅,涨跌额,成交量,成交额,振幅,最高,...,量比,换手率,市盈率-动态,市净率,总市值,流通市值,涨速,5分钟涨跌,60日涨跌幅,年初至今涨跌幅
0,1,839946,华阳变速,3.25,30.00,0.75,89424.0,2.751832e+07,30.00,3.25,...,23.27,8.97,-30.65,1.63,4.387189e+08,3.238625e+08,0.00,0.00,34.30,11.68
1,2,830896,旺成科技,5.98,30.00,1.38,78646.0,4.499187e+07,30.00,5.98,...,26.03,30.89,13.72,1.54,6.053210e+08,1.522568e+08,0.00,0.00,26.43,-23.33
2,3,831526,凯华材料,9.04,29.89,2.08,136511.0,1.073315e+08,27.87,9.04,...,2.20,55.31,42.49,3.65,7.476080e+08,2.231078e+08,0.00,0.00,96.10,122.11
3,4,831278,泰德股份,3.67,22.33,0.67,107752.0,3.708011e+07,27.67,3.82,...,14.36,11.05,107.44,1.54,5.707804e+08,3.578651e+08,-0.27,0.55,17.63,19.54
4,5,300210,森远股份,10.78,20.04,1.80,1142626.0,1.143285e+09,22.94,10.78,...,1.39,23.62,-110.42,9.78,5.219891e+09,5.213944e+09,0.00,0.00,212.46,269.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5546,5547,300475,香农芯创,38.69,-7.66,-3.21,582230.0,2.275428e+09,7.92,41.20,...,1.15,13.23,61.25,7.13,1.770322e+10,1.703292e+10,0.18,0.60,29.53,136.06
5547,5548,688733,壹石通,37.41,-7.86,-3.19,249457.0,9.451348e+08,7.07,39.50,...,1.84,17.34,363.14,3.34,7.473590e+09,5.382684e+09,0.03,-0.24,31.40,-0.16
5548,5549,605086,龙高股份,32.90,-8.23,-2.95,180532.0,5.919798e+08,9.15,35.55,...,4.83,35.29,34.30,3.63,4.211200e+09,1.682901e+09,-0.18,-0.30,54.90,74.17
5549,5550,300799,*ST左江,214.48,-9.76,-23.21,4522.0,9.904676e+07,7.54,231.00,...,2.75,0.67,-168.63,37.78,2.188339e+10,1.449349e+10,-0.92,-1.02,-18.79,64.53
5550,5551,688319,欧林生物,19.71,-12.67,-2.86,128279.0,2.567519e+08,16.30,22.88,...,4.21,4.45,198.26,8.66,8.005380e+09,5.680930e+09,0.00,-0.15,22.50,42.11

In [6]:
df_hist = ak.stock_zh_a_hist()

In [7]:
df_hist

,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
0,1991-04-03,49.00,49.00,49.00,49.00,1,5.000000e+03,0.00,22.50,9.00,0.00
1,1991-04-04,48.76,48.76,48.76,48.76,3,1.500000e+04,0.00,-0.49,-0.24,0.00
2,1991-04-05,48.52,48.52,48.52,48.52,2,1.000000e+04,0.00,-0.49,-0.24,0.00
3,1991-04-06,48.28,48.28,48.28,48.28,7,3.400000e+04,0.00,-0.49,-0.24,0.00
4,1991-04-08,48.04,48.04,48.04,48.04,2,1.000000e+04,0.00,-0.50,-0.24,0.00
...,...,...,...,...,...,...,...,...,...,...,...
7790,2023-11-14,10.24,10.27,10.33,10.23,596859,6.133777e+08,0.98,0.20,0.02,0.31
7791,2023-11-15,10.37,10.37,10.45,10.34,1109140,1.152155e+09,1.07,0.97,0.10,0.57
7792,2023-11-16,10.38,10.24,10.39,10.23,922622,9.483951e+08,1.54,-1.25,-0.13,0.48
7793,2023-11-17,10.22,10.15,10.25,10.12,903362,9.176167e+08,1.27,-0.88,-0.09,0.47
7794,2023-11-20,10.15,10.19,10.22,10.10,639528,6.500774e+08,1.18,0.39,0.04,0.33

In [8]:
df_id = ak.stock_zh_a_spot_em()

In [12]:
df_id.columns

Index(['序号', '代码', '名称', '最新价', '涨跌幅', '涨跌额', '成交量', '成交额', '振幅', '最高', '最低',
       '今开', '昨收', '量比', '换手率', '市盈率-动态', '市净率', '总市值', '流通市值', '涨速', '5分钟涨跌',
       '60日涨跌幅', '年初至今涨跌幅'],
      dtype='object')

In [ ]:
df_id.loc[]

In [107]:
df_id

,序号,代码,名称,最新价,涨跌幅,涨跌额,成交量,成交额,振幅,最高,...,量比,换手率,市盈率-动态,市净率,总市值,流通市值,涨速,5分钟涨跌,60日涨跌幅,年初至今涨跌幅
0,1,839946,华阳变速,3.25,30.00,0.75,89424.0,2.751832e+07,30.00,3.25,...,23.27,8.97,-30.65,1.63,4.387189e+08,3.238625e+08,0.00,0.00,34.30,11.68
1,2,830896,旺成科技,5.98,30.00,1.38,78646.0,4.499187e+07,30.00,5.98,...,26.03,30.89,13.72,1.54,6.053210e+08,1.522568e+08,0.00,0.00,26.43,-23.33
2,3,831526,凯华材料,9.04,29.89,2.08,136511.0,1.073315e+08,27.87,9.04,...,2.20,55.31,42.49,3.65,7.476080e+08,2.231078e+08,0.00,0.00,96.10,122.11
3,4,831278,泰德股份,3.67,22.33,0.67,107752.0,3.708011e+07,27.67,3.82,...,14.36,11.05,107.44,1.54,5.707804e+08,3.578651e+08,-0.27,0.55,17.63,19.54
4,5,300210,森远股份,10.78,20.04,1.80,1142626.0,1.143285e+09,22.94,10.78,...,1.39,23.62,-110.42,9.78,5.219891e+09,5.213944e+09,0.00,0.00,212.46,269.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5546,5547,300475,香农芯创,38.69,-7.66,-3.21,582230.0,2.275428e+09,7.92,41.20,...,1.15,13.23,61.25,7.13,1.770322e+10,1.703292e+10,0.18,0.60,29.53,136.06
5547,5548,688733,壹石通,37.41,-7.86,-3.19,249457.0,9.451348e+08,7.07,39.50,...,1.84,17.34,363.14,3.34,7.473590e+09,5.382684e+09,0.03,-0.24,31.40,-0.16
5548,5549,605086,龙高股份,32.90,-8.23,-2.95,180532.0,5.919798e+08,9.15,35.55,...,4.83,35.29,34.30,3.63,4.211200e+09,1.682901e+09,-0.18,-0.30,54.90,74.17
5549,5550,300799,*ST左江,214.48,-9.76,-23.21,4522.0,9.904676e+07,7.54,231.00,...,2.75,0.67,-168.63,37.78,2.188339e+10,1.449349e+10,-0.92,-1.02,-18.79,64.53
5550,5551,688319,欧林生物,19.71,-12.67,-2.86,128279.0,2.567519e+08,16.30,22.88,...,4.21,4.45,198.26,8.66,8.005380e+09,5.680930e+09,0.00,-0.15,22.50,42.11

In [13]:
df = df_id.iloc[:5, :]
df

,序号,代码,名称,最新价,涨跌幅,涨跌额,成交量,成交额,振幅,最高,...,量比,换手率,市盈率-动态,市净率,总市值,流通市值,涨速,5分钟涨跌,60日涨跌幅,年初至今涨跌幅
0,1,839946,华阳变速,3.25,30.00,0.75,89424.0,2.751832e+07,30.00,3.25,...,23.27,8.97,-30.65,1.63,4.387189e+08,3.238625e+08,0.00,0.00,34.30,11.68
1,2,830896,旺成科技,5.98,30.00,1.38,78646.0,4.499187e+07,30.00,5.98,...,26.03,30.89,13.72,1.54,6.053210e+08,1.522568e+08,0.00,0.00,26.43,-23.33
2,3,831526,凯华材料,9.04,29.89,2.08,136511.0,1.073315e+08,27.87,9.04,...,2.20,55.31,42.49,3.65,7.476080e+08,2.231078e+08,0.00,0.00,96.10,122.11
3,4,831278,泰德股份,3.67,22.33,0.67,107752.0,3.708011e+07,27.67,3.82,...,14.36,11.05,107.44,1.54,5.707804e+08,3.578651e+08,-0.27,0.55,17.63,19.54
4,5,300210,森远股份,10.78,20.04,1.80,1142626.0,1.143285e+09,22.94,10.78,...,1.39,23.62,-110.42,9.78,5.219891e+09,5.213944e+09,0.00,0.00,212.46,269.18

In [14]:
df.to_dict(orient='records')

[{'序号': 1,
  '代码': '839946',
  '名称': '华阳变速',
  '最新价': 3.25,
  '涨跌幅': 30.0,
  '涨跌额': 0.75,
  '成交量': 89424.0,
  '成交额': 27518323.63,
  '振幅': 30.0,
  '最高': 3.25,
  '最低': 2.5,
  '今开': 2.52,
  '昨收': 2.5,
  '量比': 23.27,
  '换手率': 8.97,
  '市盈率-动态': -30.65,
  '市净率': 1.63,
  '总市值': 438718940.0,
  '流通市值': 323862500.0,
  '涨速': 0.0,
  '5分钟涨跌': 0.0,
  '60日涨跌幅': 34.3,
  '年初至今涨跌幅': 11.68},
 {'序号': 2,
  '代码': '830896',
  '名称': '旺成科技',
  '最新价': 5.98,
  '涨跌幅': 30.0,
  '涨跌额': 1.38,
  '成交量': 78646.0,
  '成交额': 44991869.69,
  '振幅': 30.0,
  '最高': 5.98,
  '最低': 4.6,
  '今开': 4.6,
  '昨收': 4.6,
  '量比': 26.03,
  '换手率': 30.89,
  '市盈率-动态': 13.72,
  '市净率': 1.54,
  '总市值': 605320955.0,
  '流通市值': 152256786.0,
  '涨速': 0.0,
  '5分钟涨跌': 0.0,
  '60日涨跌幅': 26.43,
  '年初至今涨跌幅': -23.33},
 {'序号': 3,
  '代码': '831526',
  '名称': '凯华材料',
  '最新价': 9.04,
  '涨跌幅': 29.89,
  '涨跌额': 2.08,
  '成交量': 136511.0,
  '成交额': 107331501.66,
  '振幅': 27.87,
  '最高': 9.04,
  '最低': 7.1,
  '今开': 7.25,
  '昨收': 6.96,
  '量比': 2.2,
  '换手率': 55.31,
  '市盈率-动态': 42.49,
  '市净率': 3.65,
  '总市值': 747608000.0,
  '流通市值': 223107815.0,
  '涨速': 0.0,
  '5分钟涨跌': 0.0,
  '60日涨跌幅': 96.1,
  '年初至今涨跌幅': 122.11},
 {'序号': 4,
  '代码': '831278',
  '名称': '泰德股份',
  '最新价': 3.67,
  '涨跌幅': 22.33,
  '涨跌额': 0.67,
  '成交量': 107752.0,
  '成交额': 37080108.21,
  '振幅': 27.67,
  '最高': 3.82,
  '最低': 2.99,
  '今开': 3.02,
  '昨收': 3.0,
  '量比': 14.36,
  '换手率': 11.05,
  '市盈率-动态': 107.44,
  '市净率': 1.54,
  '总市值': 570780420.0,
  '流通市值': 357865062.0,
  '涨速': -0.27,
  '5分钟涨跌': 0.55,
  '60日涨跌幅': 17.63,
  '年初至今涨跌幅': 19.54},
 {'序号': 5,
  '代码': '300210',
  '名称': '森远股份',
  '最新价': 10.78,
  '涨跌幅': 20.04,
  '涨跌额': 1.8,
  '成交量': 1142626.0,
  '成交额': 1143285494.98,
  '振幅': 22.94,
  '最高': 10.78,
  '最低': 8.72,
  '今开': 8.82,
  '昨收': 8.98,
  '量比': 1.39,
  '换手率': 23.62,
  '市盈率-动态': -110.42,
  '市净率': 9.78,
  '总市值': 5219891093.0,
  '流通市值': 5213943832.0,
  '涨速': 0.0,
  '5分钟涨跌': 0.0,
  '60日涨跌幅': 212.46,
  '年初至今涨跌幅': 269.18}]

In [23]:
# from utils import PASSWORD, USER_NAME
from pymongo import MongoClient
mongo_url = f'mongodb://leo:{240103}@127.0.0.1:27017'

client = MongoClient(mongo_url)

In [29]:
list(client['mydatabase']['customers'].find())

[{'_id': ObjectId('6555d59ca88aed77b6e3c137'), 'name': 'John', 'age': 30},
 {'_id': ObjectId('6555d59ca88aed77b6e3c138'), 'name': 'Leo', 'age': 22},
 {'_id': ObjectId('6555d59ca88aed77b6e3c139'), 'name': 'lucy', 'age': '21'},
 {'_id': ObjectId('6555d59ca88aed77b6e3c13a'), 'name': 'jack', 'age': '23'},
 {'_id': ObjectId('6555d59ca88aed77b6e3c13b'), 'hobby': 'sleep'},
 {'_id': ObjectId('6555d903a88aed77b6e3c13d'), 'name': 'John', 'age': 30},
 {'_id': ObjectId('6555d98da88aed77b6e3c13e'), 'name': 'cate', 'age': 30}]

In [33]:
db = client['mydatabase']['customers']

In [44]:
db.update_many({'name': {$eq:'leo'}}, {'name': 'Leo', 'age': 23})

SyntaxError: invalid syntax (3651006222.py, line 1)

In [54]:
{'name': {$eq:'leo'}}

SyntaxError: invalid syntax (3019962111.py, line 1)

In [51]:
{'name':{$eq:'leo'}}

SyntaxError: invalid syntax (331473048.py, line 1)

In [50]:
db.find()

SyntaxError: invalid syntax (2711921047.py, line 1)

In [86]:
list(db.find({'age':{'$gt':20}}))

[{'_id': ObjectId('6555d59ca88aed77b6e3c137'), 'name': 'John', 'age': 30},
 {'_id': ObjectId('6555d59ca88aed77b6e3c138'), 'name': 'Leo', 'age': 22},
 {'_id': ObjectId('6555d903a88aed77b6e3c13d'), 'name': 'John', 'age': 30},
 {'_id': ObjectId('6555d98da88aed77b6e3c13e'), 'name': 'cate', 'age': 30}]

In [112]:
list(db.find({'age':{'$eq':22}}))

[]

In [89]:
df_id.columns

Index(['序号', '代码', '名称', '最新价', '涨跌幅', '涨跌额', '成交量', '成交额', '振幅', '最高', '最低',
       '今开', '昨收', '量比', '换手率', '市盈率-动态', '市净率', '总市值', '流通市值', '涨速', '5分钟涨跌',
       '60日涨跌幅', '年初至今涨跌幅'],
      dtype='object')

In [90]:
df_id.head(3)

,序号,代码,名称,最新价,涨跌幅,涨跌额,成交量,成交额,振幅,最高,...,量比,换手率,市盈率-动态,市净率,总市值,流通市值,涨速,5分钟涨跌,60日涨跌幅,年初至今涨跌幅
0,1,839946,华阳变速,3.25,30.00,0.75,89424.0,2.751832e+07,30.00,3.25,...,23.27,8.97,-30.65,1.63,438718940.0,323862500.0,0.0,0.0,34.30,11.68
1,2,830896,旺成科技,5.98,30.00,1.38,78646.0,4.499187e+07,30.00,5.98,...,26.03,30.89,13.72,1.54,605320955.0,152256786.0,0.0,0.0,26.43,-23.33
2,3,831526,凯华材料,9.04,29.89,2.08,136511.0,1.073315e+08,27.87,9.04,...,2.20,55.31,42.49,3.65,747608000.0,223107815.0,0.0,0.0,96.10,122.11

In [91]:
df = df_id.copy()

In [95]:
[key for key in rename_dc.keys()]

['代码', '名称', '最新价', '总市值', '流通市值']

In [102]:
rename_dc = {'代码': 'instrument_id', '名称': 'name', '最新价': 'latest_price', '总市值': 'total_market_value', 
             '流通市值': 'current_market_value'}
df = df.rename(columns=rename_dc).loc[:, [key for key in rename_dc.values()]]
data = df.to_dict(orient='records')
data[:3]

[{'instrument_id': '839946',
  'name': '华阳变速',
  'latest_price': 3.25,
  'total_market_value': 438718940.0,
  'current_market_value': 323862500.0},
 {'instrument_id': '830896',
  'name': '旺成科技',
  'latest_price': 5.98,
  'total_market_value': 605320955.0,
  'current_market_value': 152256786.0},
 {'instrument_id': '831526',
  'name': '凯华材料',
  'latest_price': 9.04,
  'total_market_value': 747608000.0,
  'current_market_value': 223107815.0}]

In [203]:
db = client['stock']['instrument_info']
db.insert_many(data)

InsertManyResult([ObjectId('655c2235ca3e018469905464'), ObjectId('655c2235ca3e018469905465'), ObjectId('655c2235ca3e018469905466'), ObjectId('655c2235ca3e018469905467'), ObjectId('655c2235ca3e018469905468'), ObjectId('655c2235ca3e018469905469'), ObjectId('655c2235ca3e01846990546a'), ObjectId('655c2235ca3e01846990546b'), ObjectId('655c2235ca3e01846990546c'), ObjectId('655c2235ca3e01846990546d'), ObjectId('655c2235ca3e01846990546e'), ObjectId('655c2235ca3e01846990546f'), ObjectId('655c2235ca3e018469905470'), ObjectId('655c2235ca3e018469905471'), ObjectId('655c2235ca3e018469905472'), ObjectId('655c2235ca3e018469905473'), ObjectId('655c2235ca3e018469905474'), ObjectId('655c2235ca3e018469905475'), ObjectId('655c2235ca3e018469905476'), ObjectId('655c2235ca3e018469905477'), ObjectId('655c2235ca3e018469905478'), ObjectId('655c2235ca3e018469905479'), ObjectId('655c2235ca3e01846990547a'), ObjectId('655c2235ca3e01846990547b'), ObjectId('655c2235ca3e01846990547c'), ObjectId('655c2235ca3e01846990547d'), ObjectId('655c2235ca3e01846990547e'), ObjectId('655c2235ca3e01846990547f'), ObjectId('655c2235ca3e018469905480'), ObjectId('655c2235ca3e018469905481'), ObjectId('655c2235ca3e018469905482'), ObjectId('655c2235ca3e018469905483'), ObjectId('655c2235ca3e018469905484'), ObjectId('655c2235ca3e018469905485'), ObjectId('655c2235ca3e018469905486'), ObjectId('655c2235ca3e018469905487'), ObjectId('655c2235ca3e018469905488'), ObjectId('655c2235ca3e018469905489'), ObjectId('655c2235ca3e01846990548a'), ObjectId('655c2235ca3e01846990548b'), ObjectId('655c2235ca3e01846990548c'), ObjectId('655c2235ca3e01846990548d'), ObjectId('655c2235ca3e01846990548e'), ObjectId('655c2235ca3e01846990548f'), ObjectId('655c2235ca3e018469905490'), ObjectId('655c2235ca3e018469905491'), ObjectId('655c2235ca3e018469905492'), ObjectId('655c2235ca3e018469905493'), ObjectId('655c2235ca3e018469905494'), ObjectId('655c2235ca3e018469905495'), ObjectId('655c2235ca3e018469905496'), ObjectId('655c2235ca3e018469905497'), ObjectId('655c2235ca3e018469905498'), ObjectId('655c2235ca3e018469905499'), ObjectId('655c2235ca3e01846990549a'), ObjectId('655c2235ca3e01846990549b'), ObjectId('655c2235ca3e01846990549c'), ObjectId('655c2235ca3e01846990549d'), ObjectId('655c2235ca3e01846990549e'), ObjectId('655c2235ca3e01846990549f'), ObjectId('655c2235ca3e0184699054a0'), ObjectId('655c2235ca3e0184699054a1'), ObjectId('655c2235ca3e0184699054a2'), ObjectId('655c2235ca3e0184699054a3'), ObjectId('655c2235ca3e0184699054a4'), ObjectId('655c2235ca3e0184699054a5'), ObjectId('655c2235ca3e0184699054a6'), ObjectId('655c2235ca3e0184699054a7'), ObjectId('655c2235ca3e0184699054a8'), ObjectId('655c2235ca3e0184699054a9'), ObjectId('655c2235ca3e0184699054aa'), ObjectId('655c2235ca3e0184699054ab'), ObjectId('655c2235ca3e0184699054ac'), ObjectId('655c2235ca3e0184699054ad'), ObjectId('655c2235ca3e0184699054ae'), ObjectId('655c2235ca3e0184699054af'), ObjectId('655c2235ca3e0184699054b0'), ObjectId('655c2235ca3e0184699054b1'), ObjectId('655c2235ca3e0184699054b2'), ObjectId('655c2235ca3e0184699054b3'), ObjectId('655c2235ca3e0184699054b4'), ObjectId('655c2235ca3e0184699054b5'), ObjectId('655c2235ca3e0184699054b6'), ObjectId('655c2235ca3e0184699054b7'), ObjectId('655c2235ca3e0184699054b8'), ObjectId('655c2235ca3e0184699054b9'), ObjectId('655c2235ca3e0184699054ba'), ObjectId('655c2235ca3e0184699054bb'), ObjectId('655c2235ca3e0184699054bc'), ObjectId('655c2235ca3e0184699054bd'), ObjectId('655c2235ca3e0184699054be'), ObjectId('655c2235ca3e0184699054bf'), ObjectId('655c2235ca3e0184699054c0'), ObjectId('655c2235ca3e0184699054c1'), ObjectId('655c2235ca3e0184699054c2'), ObjectId('655c2235ca3e0184699054c3'), ObjectId('655c2235ca3e0184699054c4'), ObjectId('655c2235ca3e0184699054c5'), ObjectId('655c2235ca3e0184699054c6'), ObjectId('655c2235ca3e0184699054c7'), ObjectId('655c2235ca3e0184699054c8'), ObjectId('655c2235ca3e0184699054c9'), ObjectId('655c2235ca3e0184699054ca'), ObjectId('655c2235ca3e0184699054cb'), ObjectId('655c2235ca3e0184699054cc'), ObjectId('655c2235ca3e0184699054cd'), ObjectId('655c2235ca3e0184699054ce'), ObjectId('655c2235ca3e0184699054cf'), ObjectId('655c2235ca3e0184699054d0'), ObjectId('655c2235ca3e0184699054d1'), ObjectId('655c2235ca3e0184699054d2'), ObjectId('655c2235ca3e0184699054d3'), ObjectId('655c2235ca3e0184699054d4'), ObjectId('655c2235ca3e0184699054d5'), ObjectId('655c2235ca3e0184699054d6'), ObjectId('655c2235ca3e0184699054d7'), ObjectId('655c2235ca3e0184699054d8'), ObjectId('655c2235ca3e0184699054d9'), ObjectId('655c2235ca3e0184699054da'), ObjectId('655c2235ca3e0184699054db'), ObjectId('655c2235ca3e0184699054dc'), ObjectId('655c2235ca3e0184699054dd'), ObjectId('655c2235ca3e0184699054de'), ObjectId('655c2235ca3e0184699054df'), ObjectId('655c2235ca3e0184699054e0'), ObjectId('655c2235ca3e0184699054e1'), ObjectId('655c2235ca3e0184699054e2'), ObjectId('655c2235ca3e0184699054e3'), ObjectId('655c2235ca3e0184699054e4'), ObjectId('655c2235ca3e0184699054e5'), ObjectId('655c2235ca3e0184699054e6'), ObjectId('655c2235ca3e0184699054e7'), ObjectId('655c2235ca3e0184699054e8'), ObjectId('655c2235ca3e0184699054e9'), ObjectId('655c2235ca3e0184699054ea'), ObjectId('655c2235ca3e0184699054eb'), ObjectId('655c2235ca3e0184699054ec'), ObjectId('655c2235ca3e0184699054ed'), ObjectId('655c2235ca3e0184699054ee'), ObjectId('655c2235ca3e0184699054ef'), ObjectId('655c2235ca3e0184699054f0'), ObjectId('655c2235ca3e0184699054f1'), ObjectId('655c2235ca3e0184699054f2'), ObjectId('655c2235ca3e0184699054f3'), ObjectId('655c2235ca3e0184699054f4'), ObjectId('655c2235ca3e0184699054f5'), ObjectId('655c2235ca3e0184699054f6'), ObjectId('655c2235ca3e0184699054f7'), ObjectId('655c2235ca3e0184699054f8'), ObjectId('655c2235ca3e0184699054f9'), ObjectId('655c2235ca3e0184699054fa'), ObjectId('655c2235ca3e0184699054fb'), ObjectId('655c2235ca3e0184699054fc'), ObjectId('655c2235ca3e0184699054fd'), ObjectId('655c2235ca3e0184699054fe'), ObjectId('655c2235ca3e0184699054ff'), ObjectId('655c2235ca3e018469905500'), ObjectId('655c2235ca3e018469905501'), ObjectId('655c2235ca3e018469905502'), ObjectId('655c2235ca3e018469905503'), ObjectId('655c2235ca3e018469905504'), ObjectId('655c2235ca3e018469905505'), ObjectId('655c2235ca3e018469905506'), ObjectId('655c2235ca3e018469905507'), ObjectId('655c2235ca3e018469905508'), ObjectId('655c2235ca3e018469905509'), ObjectId('655c2235ca3e01846990550a'), ObjectId('655c2235ca3e01846990550b'), ObjectId('655c2235ca3e01846990550c'), ObjectId('655c2235ca3e01846990550d'), ObjectId('655c2235ca3e01846990550e'), ObjectId('655c2235ca3e01846990550f'), ObjectId('655c2235ca3e018469905510'), ObjectId('655c2235ca3e018469905511'), ObjectId('655c2235ca3e018469905512'), ObjectId('655c2235ca3e018469905513'), ObjectId('655c2235ca3e018469905514'), ObjectId('655c2235ca3e018469905515'), ObjectId('655c2235ca3e018469905516'), ObjectId('655c2235ca3e018469905517'), ObjectId('655c2235ca3e018469905518'), ObjectId('655c2235ca3e018469905519'), ObjectId('655c2235ca3e01846990551a'), ObjectId('655c2235ca3e01846990551b'), ObjectId('655c2235ca3e01846990551c'), ObjectId('655c2235ca3e01846990551d'), ObjectId('655c2235ca3e01846990551e'), ObjectId('655c2235ca3e01846990551f'), ObjectId('655c2235ca3e018469905520'), ObjectId('655c2235ca3e018469905521'), ObjectId('655c2235ca3e018469905522'), ObjectId('655c2235ca3e018469905523'), ObjectId('655c2235ca3e018469905524'), ObjectId('655c2235ca3e018469905525'), ObjectId('655c2235ca3e018469905526'), ObjectId('655c2235ca3e018469905527'), ObjectId('655c2235ca3e018469905528'), ObjectId('655c2235ca3e018469905529'), ObjectId('655c2235ca3e01846990552a'), ObjectId('655c2235ca3e01846990552b'), ObjectId('655c2235ca3e01846990552c'), ObjectId('655c2235ca3e01846990552d'), ObjectId('655c2235ca3e01846990552e'), ObjectId('655c2235ca3e01846990552f'), ObjectId('655c2235ca3e018469905530'), ObjectId('655c2235ca3e018469905531'), ObjectId('655c2235ca3e018469905532'), ObjectId('655c2235ca3e018469905533'), ObjectId('655c2235ca3e018469905534'), ObjectId('655c2235ca3e018469905535'), ObjectId('655c2235ca3e018469905536'), ObjectId('655c2235ca3e018469905537'), ObjectId('655c2235ca3e018469905538'), ObjectId('655c2235ca3e018469905539'), ObjectId('655c2235ca3e01846990553a'), ObjectId('655c2235ca3e01846990553b'), ObjectId('655c2235ca3e01846990553c'), ObjectId('655c2235ca3e01846990553d'), ObjectId('655c2235ca3e01846990553e'), ObjectId('655c2235ca3e01846990553f'), ObjectId('655c2235ca3e018469905540'), ObjectId('655c2235ca3e018469905541'), ObjectId('655c2235ca3e018469905542'), ObjectId('655c2235ca3e018469905543'), ObjectId('655c2235ca3e018469905544'), ObjectId('655c2235ca3e018469905545'), ObjectId('655c2235ca3e018469905546'), ObjectId('655c2235ca3e018469905547'), ObjectId('655c2235ca3e018469905548'), ObjectId('655c2235ca3e018469905549'), ObjectId('655c2235ca3e01846990554a'), ObjectId('655c2235ca3e01846990554b'), ObjectId('655c2235ca3e01846990554c'), ObjectId('655c2235ca3e01846990554d'), ObjectId('655c2235ca3e01846990554e'), ObjectId('655c2235ca3e01846990554f'), ObjectId('655c2235ca3e018469905550'), ObjectId('655c2235ca3e018469905551'), ObjectId('655c2235ca3e018469905552'), ObjectId('655c2235ca3e018469905553'), ObjectId('655c2235ca3e018469905554'), ObjectId('655c2235ca3e018469905555'), ObjectId('655c2235ca3e018469905556'), ObjectId('655c2235ca3e018469905557'), ObjectId('655c2235ca3e018469905558'), ObjectId('655c2235ca3e018469905559'), ObjectId('655c2235ca3e01846990555a'), ObjectId('655c2235ca3e01846990555b'), ObjectId('655c2235ca3e01846990555c'), ObjectId('655c2235ca3e01846990555d'), ObjectId('655c2235ca3e01846990555e'), ObjectId('655c2235ca3e01846990555f'), ObjectId('655c2235ca3e018469905560'), ObjectId('655c2235ca3e018469905561'), ObjectId('655c2235ca3e018469905562'), ObjectId('655c2235ca3e018469905563'), ObjectId('655c2235ca3e018469905564'), ObjectId('655c2235ca3e018469905565'), ObjectId('655c2235ca3e018469905566'), ObjectId('655c2235ca3e018469905567'), ObjectId('655c2235ca3e018469905568'), ObjectId('655c2235ca3e018469905569'), ObjectId('655c2235ca3e01846990556a'), ObjectId('655c2235ca3e01846990556b'), ObjectId('655c2235ca3e01846990556c'), ObjectId('655c2235ca3e01846990556d'), ObjectId('655c2235ca3e01846990556e'), ObjectId('655c2235ca3e01846990556f'), ObjectId('655c2235ca3e018469905570'), ObjectId('655c2235ca3e018469905571'), ObjectId('655c2235ca3e018469905572'), ObjectId('655c2235ca3e018469905573'), ObjectId('655c2235ca3e018469905574'), ObjectId('655c2235ca3e018469905575'), ObjectId('655c2235ca3e018469905576'), ObjectId('655c2235ca3e018469905577'), ObjectId('655c2235ca3e018469905578'), ObjectId('655c2235ca3e018469905579'), ObjectId('655c2235ca3e01846990557a'), ObjectId('655c2235ca3e01846990557b'), ObjectId('655c2235ca3e01846990557c'), ObjectId('655c2235ca3e01846990557d'), ObjectId('655c2235ca3e01846990557e'), ObjectId('655c2235ca3e01846990557f'), ObjectId('655c2235ca3e018469905580'), ObjectId('655c2235ca3e018469905581'), ObjectId('655c2235ca3e018469905582'), ObjectId('655c2235ca3e018469905583'), ObjectId('655c2235ca3e018469905584'), ObjectId('655c2235ca3e018469905585'), ObjectId('655c2235ca3e018469905586'), ObjectId('655c2235ca3e018469905587'), ObjectId('655c2235ca3e018469905588'), ObjectId('655c2235ca3e018469905589'), ObjectId('655c2235ca3e01846990558a'), ObjectId('655c2235ca3e01846990558b'), ObjectId('655c2235ca3e01846990558c'), ObjectId('655c2235ca3e01846990558d'), ObjectId('655c2235ca3e01846990558e'), ObjectId('655c2235ca3e01846990558f'), ObjectId('655c2235ca3e018469905590'), ObjectId('655c2235ca3e018469905591'), ObjectId('655c2235ca3e018469905592'), ObjectId('655c2235ca3e018469905593'), ObjectId('655c2235ca3e018469905594'), ObjectId('655c2235ca3e018469905595'), ObjectId('655c2235ca3e018469905596'), ObjectId('655c2235ca3e018469905597'), ObjectId('655c2235ca3e018469905598'), ObjectId('655c2235ca3e018469905599'), ObjectId('655c2235ca3e01846990559a'), ObjectId('655c2235ca3e01846990559b'), ObjectId('655c2235ca3e01846990559c'), ObjectId('655c2235ca3e01846990559d'), ObjectId('655c2235ca3e01846990559e'), ObjectId('655c2235ca3e01846990559f'), ObjectId('655c2235ca3e0184699055a0'), ObjectId('655c2235ca3e0184699055a1'), ObjectId('655c2235ca3e0184699055a2'), ObjectId('655c2235ca3e0184699055a3'), ObjectId('655c2235ca3e0184699055a4'), ObjectId('655c2235ca3e0184699055a5'), ObjectId('655c2235ca3e0184699055a6'), ObjectId('655c2235ca3e0184699055a7'), ObjectId('655c2235ca3e0184699055a8'), ObjectId('655c2235ca3e0184699055a9'), ObjectId('655c2235ca3e0184699055aa'), ObjectId('655c2235ca3e0184699055ab'), ObjectId('655c2235ca3e0184699055ac'), ObjectId('655c2235ca3e0184699055ad'), ObjectId('655c2235ca3e0184699055ae'), ObjectId('655c2235ca3e0184699055af'), ObjectId('655c2235ca3e0184699055b0'), ObjectId('655c2235ca3e0184699055b1'), ObjectId('655c2235ca3e0184699055b2'), ObjectId('655c2235ca3e0184699055b3'), ObjectId('655c2235ca3e0184699055b4'), ObjectId('655c2235ca3e0184699055b5'), ObjectId('655c2235ca3e0184699055b6'), ObjectId('655c2235ca3e0184699055b7'), ObjectId('655c2235ca3e0184699055b8'), ObjectId('655c2235ca3e0184699055b9'), ObjectId('655c2235ca3e0184699055ba'), ObjectId('655c2235ca3e0184699055bb'), ObjectId('655c2235ca3e0184699055bc'), ObjectId('655c2235ca3e0184699055bd'), ObjectId('655c2235ca3e0184699055be'), ObjectId('655c2235ca3e0184699055bf'), ObjectId('655c2235ca3e0184699055c0'), ObjectId('655c2235ca3e0184699055c1'), ObjectId('655c2235ca3e0184699055c2'), ObjectId('655c2235ca3e0184699055c3'), ObjectId('655c2235ca3e0184699055c4'), ObjectId('655c2235ca3e0184699055c5'), ObjectId('655c2235ca3e0184699055c6'), ObjectId('655c2235ca3e0184699055c7'), ObjectId('655c2235ca3e0184699055c8'), ObjectId('655c2235ca3e0184699055c9'), ObjectId('655c2235ca3e0184699055ca'), ObjectId('655c2235ca3e0184699055cb'), ObjectId('655c2235ca3e0184699055cc'), ObjectId('655c2235ca3e0184699055cd'), ObjectId('655c2235ca3e0184699055ce'), ObjectId('655c2235ca3e0184699055cf'), ObjectId('655c2235ca3e0184699055d0'), ObjectId('655c2235ca3e0184699055d1'), ObjectId('655c2235ca3e0184699055d2'), ObjectId('655c2235ca3e0184699055d3'), ObjectId('655c2235ca3e0184699055d4'), ObjectId('655c2235ca3e0184699055d5'), ObjectId('655c2235ca3e0184699055d6'), ObjectId('655c2235ca3e0184699055d7'), ObjectId('655c2235ca3e0184699055d8'), ObjectId('655c2235ca3e0184699055d9'), ObjectId('655c2235ca3e0184699055da'), ObjectId('655c2235ca3e0184699055db'), ObjectId('655c2235ca3e0184699055dc'), ObjectId('655c2235ca3e0184699055dd'), ObjectId('655c2235ca3e0184699055de'), ObjectId('655c2235ca3e0184699055df'), ObjectId('655c2235ca3e0184699055e0'), ObjectId('655c2235ca3e0184699055e1'), ObjectId('655c2235ca3e0184699055e2'), ObjectId('655c2235ca3e0184699055e3'), ObjectId('655c2235ca3e0184699055e4'), ObjectId('655c2235ca3e0184699055e5'), ObjectId('655c2235ca3e0184699055e6'), ObjectId('655c2235ca3e0184699055e7'), ObjectId('655c2235ca3e0184699055e8'), ObjectId('655c2235ca3e0184699055e9'), ObjectId('655c2235ca3e0184699055ea'), ObjectId('655c2235ca3e0184699055eb'), ObjectId('655c2235ca3e0184699055ec'), ObjectId('655c2235ca3e0184699055ed'), ObjectId('655c2235ca3e0184699055ee'), ObjectId('655c2235ca3e0184699055ef'), ObjectId('655c2235ca3e0184699055f0'), ObjectId('655c2235ca3e0184699055f1'), ObjectId('655c2235ca3e0184699055f2'), ObjectId('655c2235ca3e0184699055f3'), ObjectId('655c2235ca3e0184699055f4'), ObjectId('655c2235ca3e0184699055f5'), ObjectId('655c2235ca3e0184699055f6'), ObjectId('655c2235ca3e0184699055f7'), ObjectId('655c2235ca3e0184699055f8'), ObjectId('655c2235ca3e0184699055f9'), ObjectId('655c2235ca3e0184699055fa'), ObjectId('655c2235ca3e0184699055fb'), ObjectId('655c2235ca3e0184699055fc'), ObjectId('655c2235ca3e0184699055fd'), ObjectId('655c2235ca3e0184699055fe'), ObjectId('655c2235ca3e0184699055ff'), ObjectId('655c2235ca3e018469905600'), ObjectId('655c2235ca3e018469905601'), ObjectId('655c2235ca3e018469905602'), ObjectId('655c2235ca3e018469905603'), ObjectId('655c2235ca3e018469905604'), ObjectId('655c2235ca3e018469905605'), ObjectId('655c2235ca3e018469905606'), ObjectId('655c2235ca3e018469905607'), ObjectId('655c2235ca3e018469905608'), ObjectId('655c2235ca3e018469905609'), ObjectId('655c2235ca3e01846990560a'), ObjectId('655c2235ca3e01846990560b'), ObjectId('655c2235ca3e01846990560c'), ObjectId('655c2235ca3e01846990560d'), ObjectId('655c2235ca3e01846990560e'), ObjectId('655c2235ca3e01846990560f'), ObjectId('655c2235ca3e018469905610'), ObjectId('655c2235ca3e018469905611'), ObjectId('655c2235ca3e018469905612'), ObjectId('655c2235ca3e018469905613'), ObjectId('655c2235ca3e018469905614'), ObjectId('655c2235ca3e018469905615'), ObjectId('655c2235ca3e018469905616'), ObjectId('655c2235ca3e018469905617'), ObjectId('655c2235ca3e018469905618'), ObjectId('655c2235ca3e018469905619'), ObjectId('655c2235ca3e01846990561a'), ObjectId('655c2235ca3e01846990561b'), ObjectId('655c2235ca3e01846990561c'), ObjectId('655c2235ca3e01846990561d'), ObjectId('655c2235ca3e01846990561e'), ObjectId('655c2235ca3e01846990561f'), ObjectId('655c2235ca3e018469905620'), ObjectId('655c2235ca3e018469905621'), ObjectId('655c2235ca3e018469905622'), ObjectId('655c2235ca3e018469905623'), ObjectId('655c2235ca3e018469905624'), ObjectId('655c2235ca3e018469905625'), ObjectId('655c2235ca3e018469905626'), ObjectId('655c2235ca3e018469905627'), ObjectId('655c2235ca3e018469905628'), ObjectId('655c2235ca3e018469905629'), ObjectId('655c2235ca3e01846990562a'), ObjectId('655c2235ca3e01846990562b'), ObjectId('655c2235ca3e01846990562c'), ObjectId('655c2235ca3e01846990562d'), ObjectId('655c2235ca3e01846990562e'), ObjectId('655c2235ca3e01846990562f'), ObjectId('655c2235ca3e018469905630'), ObjectId('655c2235ca3e018469905631'), ObjectId('655c2235ca3e018469905632'), ObjectId('655c2235ca3e018469905633'), ObjectId('655c2235ca3e018469905634'), ObjectId('655c2235ca3e018469905635'), ObjectId('655c2235ca3e018469905636'), ObjectId('655c2235ca3e018469905637'), ObjectId('655c2235ca3e018469905638'), ObjectId('655c2235ca3e018469905639'), ObjectId('655c2235ca3e01846990563a'), ObjectId('655c2235ca3e01846990563b'), ObjectId('655c2235ca3e01846990563c'), ObjectId('655c2235ca3e01846990563d'), ObjectId('655c2235ca3e01846990563e'), ObjectId('655c2235ca3e01846990563f'), ObjectId('655c2235ca3e018469905640'), ObjectId('655c2235ca3e018469905641'), ObjectId('655c2235ca3e018469905642'), ObjectId('655c2235ca3e018469905643'), ObjectId('655c2235ca3e018469905644'), ObjectId('655c2235ca3e018469905645'), ObjectId('655c2235ca3e018469905646'), ObjectId('655c2235ca3e018469905647'), ObjectId('655c2235ca3e018469905648'), ObjectId('655c2235ca3e018469905649'), ObjectId('655c2235ca3e01846990564a'), ObjectId('655c2235ca3e01846990564b'), ObjectId('655c2235ca3e01846990564c'), ObjectId('655c2235ca3e01846990564d'), ObjectId('655c2235ca3e01846990564e'), ObjectId('655c2235ca3e01846990564f'), ObjectId('655c2235ca3e018469905650'), ObjectId('655c2235ca3e018469905651'), ObjectId('655c2235ca3e018469905652'), ObjectId('655c2235ca3e018469905653'), ObjectId('655c2235ca3e018469905654'), ObjectId('655c2235ca3e018469905655'), ObjectId('655c2235ca3e018469905656'), ObjectId('655c2235ca3e018469905657'), ObjectId('655c2235ca3e018469905658'), ObjectId('655c2235ca3e018469905659'), ObjectId('655c2235ca3e01846990565a'), ObjectId('655c2235ca3e01846990565b'), ObjectId('655c2235ca3e01846990565c'), ObjectId('655c2235ca3e01846990565d'), ObjectId('655c2235ca3e01846990565e'), ObjectId('655c2235ca3e01846990565f'), ObjectId('655c2235ca3e018469905660'), ObjectId('655c2235ca3e018469905661'), ObjectId('655c2235ca3e018469905662'), ObjectId('655c2235ca3e018469905663'), ObjectId('655c2235ca3e018469905664'), ObjectId('655c2235ca3e018469905665'), ObjectId('655c2235ca3e018469905666'), ObjectId('655c2235ca3e018469905667'), ObjectId('655c2235ca3e018469905668'), ObjectId('655c2235ca3e018469905669'), ObjectId('655c2235ca3e01846990566a'), ObjectId('655c2235ca3e01846990566b'), ObjectId('655c2235ca3e01846990566c'), ObjectId('655c2235ca3e01846990566d'), ObjectId('655c2235ca3e01846990566e'), ObjectId('655c2235ca3e01846990566f'), ObjectId('655c2235ca3e018469905670'), ObjectId('655c2235ca3e0184699056

In [105]:
list(db.find())

[]

In [110]:
df.loc[df['instrument_id'] == '839946']

  instrument_id  name  latest_price  total_market_value  current_market_value
0        839946  华阳变速          3.25         438718940.0           323862500.0

In [115]:
instrument_id = ['002746', '301068']

In [119]:
pd.DataFrame(db.find({'instrument_id': {'$in': instrument_id}}, {"_id": False}))

  instrument_id  name  latest_price  total_market_value  current_market_value
0        002746  仙坛股份          7.39        6.359381e+09          5.244507e+09
1        301068  大地海洋         30.06        2.525040e+09          1.191762e+09

In [122]:
def fun1(*args):
    for i in args:
        print('a', args)

In [128]:
def fun2(**kargs):
    for key, value in kargs.items():
        print(key, value)

In [131]:
fun2(a=1, b=2)

a 1
b 2

In [123]:
fun1(1, 2, 3)

a (1, 2, 3)
a (1, 2, 3)
a (1, 2, 3)

In [137]:
{'instrument_id': {'$in': instrument_id}, 'latest_price': {'$gt': 10}}

{'instrument_id': {'$in': ['002746', '301068']}, 'latest_price': {'$gt': 10}}

In [149]:
pd.DataFrame(db.find({'instrument_id': {'$in': instrument_id}, 'latest_price': {'$gt': 10, '$lt': 33}}, {"_id": False}))

  instrument_id  name  latest_price  total_market_value  current_market_value
0        301068  大地海洋         30.06        2.525040e+09          1.191762e+09

In [140]:
s = "instrument_id in instrument_id and latest_price gt 10 lt 33'"

In [143]:
s1 = s.split('and')

In [152]:
{'instrument_id': {'$in': instrument_id}, 'latest_price': {'$gt': 10, '$lt': 33}}

{'instrument_id': {'$in': ['002746', '301068']},
 'latest_price': {'$gt': 10, '$lt': 33}}

In [154]:
df

,instrument_id,name,latest_price,total_market_value,current_market_value
0,839946,华阳变速,3.25,4.387189e+08,3.238625e+08
1,830896,旺成科技,5.98,6.053210e+08,1.522568e+08
2,831526,凯华材料,9.04,7.476080e+08,2.231078e+08
3,831278,泰德股份,3.67,5.707804e+08,3.578651e+08
4,300210,森远股份,10.78,5.219891e+09,5.213944e+09
...,...,...,...,...,...
5546,300475,香农芯创,38.69,1.770322e+10,1.703292e+10
5547,688733,壹石通,37.41,7.473590e+09,5.382684e+09
5548,605086,龙高股份,32.90,4.211200e+09,1.682901e+09
5549,300799,*ST左江,214.48,2.188339e+10,1.449349e+10
5550,688319,欧林生物,19.71,8.005380e+09,5.680930e+09

In [183]:
temp = pd.DataFrame(db.find({'instrument_id': {'$in': instrument_id}}))

In [185]:
list(set(instrument_id) - set(temp['instrument_id'].to_list()))

['1139003']

In [188]:
list(set(temp['instrument_id'].to_list()) - set(instrument_id))

[]

In [187]:
set(temp['instrument_id'])

{'002746', '301068'}

In [186]:
len(temp)

2

In [159]:
db = client['stock']['instrument_info']

In [179]:
instrument_id = ['002746', '301068', '1139003']

In [178]:
df.loc[df['instrument_id'].isin(instrument_id)]

,instrument_id,name,latest_price,total_market_value,current_market_value
992,002746,仙坛股份,7.39,6.359381e+09,5.244507e+09
993,301068,大地海洋,30.06,2.525040e+09,1.191762e+09

In [169]:
df['instrument_id'].apply(lambda x: x in instrument_id)

0       False
1       False
2       False
3       False
4       False
        ...
5546    False
5547    False
5548    False
5549    False
5550    False
Name: instrument_id, Length: 5551, dtype: bool

In [216]:
mongo_filter = None
db.delete_many({})

TypeError: delete_many() missing 1 required positional argument: 'filter'

In [190]:
class MyError(Exception):
    pass

def my_function():
        
    raise MyError("This is my custom error message.")

try:
    my_function()
except MyError as e:
    print(e)

In [197]:
class MyError(Exception):
    def __init__(self, message):
        self.message = message
        super().__init__(self.message)

try:
    raise MyError("这是我的自定义错误消息。")
except MyError as e:
    print(e.message)

这是我的自定义错误消息。

In [198]:
raise MyError("这是我的自定义错误消息。")

MyError: 这是我的自定义错误消息。

In [218]:
from lwpackage.lwdata.lwstock import get_stock_info

In [215]:
mongo_filter = None
df = pd.DataFrame(db.find(None))
df

,_id,instrument_id,name,latest_price,total_market_value,current_market_value
0,655c2235ca3e018469905464,839946,华阳变速,3.25,4.387189e+08,3.238625e+08
1,655c2235ca3e018469905465,830896,旺成科技,5.98,6.053210e+08,1.522568e+08
2,655c2235ca3e018469905466,831526,凯华材料,9.04,7.476080e+08,2.231078e+08
3,655c2235ca3e018469905467,831278,泰德股份,3.67,5.707804e+08,3.578651e+08
4,655c2235ca3e018469905468,300210,森远股份,10.78,5.219891e+09,5.213944e+09
...,...,...,...,...,...,...
5546,655c2235ca3e018469906a0e,300475,香农芯创,38.69,1.770322e+10,1.703292e+10
5547,655c2235ca3e018469906a0f,688733,壹石通,37.41,7.473590e+09,5.382684e+09
5548,655c2235ca3e018469906a10,605086,龙高股份,32.90,4.211200e+09,1.682901e+09
5549,655c2235ca3e018469906a11,300799,*ST左江,214.48,2.188339e+10,1.449349e+10
5550,655c2235ca3e018469906a12,688319,欧林生物,19.71,8.005380e+09,5.680930e+09

In [209]:
db

Collection(Database(MongoClient(host=['127.0.0.1:27017'], document_class=dict, tz_aware=False, connect=True), 'stock'), 'instrument_info')

In [210]:
mongo_filter = {'instrument_id': {'$in': instrument_id}, 'latest_price': {'$gt': 10, '$lt': 33}}

In [240]:
data = df.head(2).to_dict(orient='records')
data

[{'_id': ObjectId('655c2235ca3e018469905464'),
  'instrument_id': '839946',
  'name': '华阳变速',
  'latest_price': 3.25,
  'total_market_value': 438718940.0,
  'current_market_value': 323862500.0},
 {'_id': ObjectId('655c2235ca3e018469905465'),
  'instrument_id': '830896',
  'name': '旺成科技',
  'latest_price': 5.98,
  'total_market_value': 605320955.0,
  'current_market_value': 152256786.0}]

In [245]:
pd.DataFrame(db.find({}, {'_id': False}))

,instrument_id,name,latest_price,total_market_value,current_market_value
0,839946,华阳变速,3.25,4.387189e+08,3.238625e+08
1,830896,旺成科技,5.98,6.053210e+08,1.522568e+08
2,831526,凯华材料,9.04,7.476080e+08,2.231078e+08
3,831278,泰德股份,3.67,5.707804e+08,3.578651e+08
4,300210,森远股份,10.78,5.219891e+09,5.213944e+09
...,...,...,...,...,...
5546,300475,香农芯创,38.69,1.770322e+10,1.703292e+10
5547,688733,壹石通,37.41,7.473590e+09,5.382684e+09
5548,605086,龙高股份,32.90,4.211200e+09,1.682901e+09
5549,300799,*ST左江,214.48,2.188339e+10,1.449349e+10
5550,688319,欧林生物,19.71,8.005380e+09,5.680930e+09

In [251]:
rename_dc = {'代码': 'instrument_id', '名称': 'name', '最新价': 'latest_price', '总市值': 'total_market_value',
                     '流通市值': 'current_market_value'}
df_instrument = ak.stock_zh_a_spot_em()
df_instrument = df_instrument.rename(columns=rename_dc).loc[:, [key for key in rename_dc.values()]]

In [257]:
test = df_instrument.loc[df_instrument['instrument_id'] == '839946'].to_dict(orient='records')[0]

In [271]:
df_instrument.loc[df_instrument['instrument_id'] == '839946'].to_dict(orient='records')

[{'instrument_id': '839946',
  'name': '华阳变速',
  'latest_price': 6.35,
  'total_market_value': 857189313.0,
  'current_market_value': 632777500.0}]

In [273]:
for idx, row in df_instrument.iterrows():
    t = row
    break

In [275]:
t['instrument_id']

'873570'

In [274]:
t.to_dict()

{'instrument_id': '873570',
 'name': 'N坤博',
 'latest_price': 67.1,
 'total_market_value': 2106960600.0,
 'current_market_value': 516515670.0}

In [264]:
df_instrument.loc[0].to_dict()

{'instrument_id': '873570',
 'name': 'N坤博',
 'latest_price': 67.1,
 'total_market_value': 2106960600.0,
 'current_market_value': 516515670.0}

In [258]:
test

{'instrument_id': '839946',
 'name': '华阳变速',
 'latest_price': 6.35,
 'total_market_value': 857189313.0,
 'current_market_value': 632777500.0}

In [259]:
db.update_one({'instrument_id': '839946'}, {'$set': test})

UpdateResult({'n': 1, 'nModified': 1, 'ok': 1.0, 'updatedExisting': True}, acknowledged=True)

In [260]:
pd.DataFrame(db.find({}, {'_id': False}))

,instrument_id,name,latest_price,total_market_value,current_market_value
0,839946,华阳变速,6.35,8.571893e+08,6.327775e+08
1,830896,旺成科技,5.98,6.053210e+08,1.522568e+08
2,831526,凯华材料,9.04,7.476080e+08,2.231078e+08
3,831278,泰德股份,3.67,5.707804e+08,3.578651e+08
4,300210,森远股份,10.78,5.219891e+09,5.213944e+09
...,...,...,...,...,...
5546,300475,香农芯创,38.69,1.770322e+10,1.703292e+10
5547,688733,壹石通,37.41,7.473590e+09,5.382684e+09
5548,605086,龙高股份,32.90,4.211200e+09,1.682901e+09
5549,300799,*ST左江,214.48,2.188339e+10,1.449349e+10
5550,688319,欧林生物,19.71,8.005380e+09,5.680930e+09

In [277]:
from lwpackage.lwdata.lwstock import get_stock_info, update_instrument_info

ImportError: cannot import name 'update_instrument_info' from 'lwpackage.lwdata.lwstock' (/Users/wenglongao/anaconda3/envs/leoweng4.0/lib/python3.9/site-packages/lwpackage/lwdata/lwstock.py)

In [1]:
from lwpackage.lwdata import *

In [2]:
update_stock_price(frequency='5m')

sh600788 股票数据不存在，请检查是否已退市

:

In [35]:
a = 100

In [13]:
x

40

In [36]:
res = 0
while a > 0:
    temp = a // (10 **(len(str(a)) - 1))
    res += temp **2
    a = a - temp * (10 **(len(str(a)) - 1))

In [50]:
l = list(s)
l

['a', 'p', 'p', 'l', 'e']

In [56]:
from collections import deque
d = deque()

In [57]:
d.append(1)

In [45]:
from functools import reduce

In [46]:
reduce(lambda x, y: x + y, list(s))

'apple'

In [42]:
s = 'apple'
s[1:3] = s[1:3][::-1]

TypeError: 'str' object does not support item assignment

In [38]:
l = [1, 3, 5, 2]

In [39]:
sorted(l)

[1, 2, 3, 5]

In [31]:
temp = a // (10 **(len(str(a)) - 1))
res += temp **2
a = a - temp * (10 **(len(str(a)) - 1))

In [32]:
a

298

In [17]:
a // (10 **(len(str(a)) - 1))

1

In [21]:
 // 10

0

In [7]:
821 // 100

8

In [9]:
from collections import Counter
nums = [1,1,1,2,2,3]
c = Counter(nums)

In [13]:
ord('a') - 95

2

In [16]:
from functools import reduce

In [17]:
l = ['a', 'b', 'c']
reduce(lambda x, y: x + y, l)

'abc'

In [27]:
l[:100] + l[101:]

[3, 2, 1]

In [29]:
left = []
right = []
path = [left, right]

In [33]:
path = [[5, 2], [3]]
[i + [1] for i in path]

[[5, 2, 1], [3, 1]]

In [38]:
'->'.join([str(i) for i in l])

'3->2->1'

In [7]:
import os
os.path.exists('/Volumes/NO NAME/DCIM/100_PANA')

True

In [9]:
x = os.listdir('/Volumes/NO NAME/DCIM/100_PANA')

In [13]:
x1 = [i for i in x if i.endswith('RW2')]

In [14]:
len(x1)

75

In [3]:
from collections import Counter
c = Counter()

In [6]:
c[1] -= 1
c[1]

-1

In [25]:
l = [2, 1, 3]
l.sort(reverse=True)
l

[3, 2, 1]

In [7]:
int((13 / 5))

2

In [5]:
from collections import deque
q = deque([1, 2, 3])

In [6]:
max(q)

3

In [1]:
from lwpackage.lwutils import categorize_photos

In [68]:
photo_name = 'IMG_20240101_141521.jpg'

In [7]:
prefix = photo_name.split('.')[0]
p1 = prefix.split('_')[1]
p2 = prefix.split('_')[2][:6]
prefix = '_'.join([p1, p2])
suffix = photo_name.split('.')[-1]
'.'.join([prefix, suffix])

IndexError: list index out of range

In [3]:
photo_name = '144fec0a334fedd27760d23860d1539b.jpeg'

In [4]:
photo_name = '.IMG_20240116_201331.jpg'

In [6]:
photo = '20240116_201331(1).jpg'

In [4]:
photo[1:]

'0240116_201331(1).jpg'

In [7]:
prefix = photo.split('.')[0]
suffix = photo.split('.')[1]
base_name = '.'.join([prefix[:-3], suffix])

In [8]:
prefix.endswith(')')

True

In [16]:
base_name

'20240116_201331.jpg'

In [7]:
condition2 = len(photo_name.split('_')) > 1 and photo_name.split('_')[1].isdigit() and len(photo_name.split('_')[1]) == 8
condition2

False

In [6]:
photo_name.split('_')

['.IMG', '20240116', '201331.jpg']

In [5]:
import os
from lwpackage.lwutils import POSTPROCESS_PHOTO_PATH
postprocess_photo_path = POSTPROCESS_PHOTO_PATH
p = os.path.join(postprocess_photo_path, '相机')

In [13]:
os.path.exists(os.path.join(p, '_20231003_124111.jpg'))

False

In [12]:
os.path.join(p, '_20231003_124529.jpg')

'/Volumes/Leo Weng/photos/整理完成的照片/相机/_20231003_124529.jpg'

In [18]:
os.listdir(p)

['20231005_082230.jpg',
 '._20231005_082230.jpg',
 '20231005_082220.jpg',
 '._20231005_082220.jpg',
 '20231004_204753.jpg',
 '._20231004_204753.jpg',
 '20231004_203409.jpg',
 '._20231004_203409.jpg',
 '20231004_203405.jpg',
 '._20231004_203405.jpg',
 '20231004_203139.jpg',
 '._20231004_203139.jpg',
 '20231004_203044.jpg',
 '._20231004_203044.jpg',
 '20231004_203039.jpg',
 '._20231004_203039.jpg',
 '20231004_202824.jpg',
 '._20231004_202824.jpg',
 '20231004_202156.jpg',
 '._20231004_202156.jpg',
 '20231004_193839.jpg',
 '._20231004_193839.jpg',
 '20231004_172232.jpg',
 '._20231004_172232.jpg',
 '20231004_172227.jpg',
 '._20231004_172227.jpg',
 '20231004_172226.jpg',
 '._20231004_172226.jpg',
 '20231004_172152.jpg',
 '._20231004_172152.jpg',
 '20231004_172128.jpg',
 '._20231004_172128.jpg',
 '20231004_172125.jpg',
 '._20231004_172125.jpg',
 '20231004_172123.jpg',
 '._20231004_172123.jpg',
 '20231004_172122.jpg',
 '._20231004_172122.jpg',
 '20231004_172036.jpg',
 '._20231004_172036.jpg',
 '20231004_171802.jpg',
 '._20231004_171802.jpg',
 '20231004_171726.jpg',
 '._20231004_171726.jpg',
 '20231004_171724.jpg',
 '._20231004_171724.jpg',
 '20231004_171712.jpg',
 '._20231004_171712.jpg',
 '20231004_171638.jpg',
 '._20231004_171638.jpg',
 '20231004_171637.jpg',
 '._20231004_171637.jpg',
 '20231004_171636.jpg',
 '._20231004_171636.jpg',
 '20231004_171635.jpg',
 '._20231004_171635.jpg',
 '20231004_171634.jpg',
 '._20231004_171634.jpg',
 '20231004_171549.jpg',
 '._20231004_171549.jpg',
 '20231004_171546.jpg',
 '._20231004_171546.jpg',
 '20231004_171538.jpg',
 '._20231004_171538.jpg',
 '20231004_171524.jpg',
 '._20231004_171524.jpg',
 '20231004_171517.jpg',
 '._20231004_171517.jpg',
 '20231004_171503.jpg',
 '._20231004_171503.jpg',
 '20231004_171502.jpg',
 '._20231004_171502.jpg',
 '20231004_171451.jpg',
 '._20231004_171451.jpg',
 '20231004_171446.jpg',
 '._20231004_171446.jpg',
 '20231004_171250.jpg',
 '._20231004_171250.jpg',
 '20231004_171248.jpg',
 '._20231004_171248.jpg',
 '20231004_171247.jpg',
 '._20231004_171247.jpg',
 '20231004_171159.jpg',
 '._20231004_171159.jpg',
 '20231004_171156.jpg',
 '._20231004_171156.jpg',
 '20231004_171155.jpg',
 '._20231004_171155.jpg',
 '20231004_171135.jpg',
 '._20231004_171135.jpg',
 '20231004_171131.jpg',
 '._20231004_171131.jpg',
 '20231004_170932.jpg',
 '._20231004_170932.jpg',
 '20231004_170831.jpg',
 '._20231004_170831.jpg',
 '20231004_170827.jpg',
 '._20231004_170827.jpg',
 '20231004_170826.jpg',
 '._20231004_170826.jpg',
 '20231004_170727.jpg',
 '._20231004_170727.jpg',
 '20231004_170620.jpg',
 '._20231004_170620.jpg',
 '20231004_163330.jpg',
 '._20231004_163330.jpg',
 '20231004_163328.jpg',
 '._20231004_163328.jpg',
 '20231004_163323.jpg',
 '._20231004_163323.jpg',
 '20231004_163321.jpg',
 '._20231004_163321.jpg',
 '20231004_163232.jpg',
 '._20231004_163232.jpg',
 '20231004_163225.jpg',
 '._20231004_163225.jpg',
 '20231004_163221.jpg',
 '._20231004_163221.jpg',
 '20231004_163219.jpg',
 '._20231004_163219.jpg',
 '20231004_162930.jpg',
 '._20231004_162930.jpg',
 '20231004_162920.jpg',
 '._20231004_162920.jpg',
 '20231004_162748.jpg',
 '._20231004_162748.jpg',
 '20231004_162550.jpg',
 '._20231004_162550.jpg',
 '20231004_162549.jpg',
 '._20231004_162549.jpg',
 '20231004_162540.jpg',
 '._20231004_162540.jpg',
 '20231004_162539.jpg',
 '._20231004_162539.jpg',
 '20231004_162227.jpg',
 '._20231004_162227.jpg',
 '20231004_162018.jpg',
 '._20231004_162018.jpg',
 '20231004_161808.jpg',
 '._20231004_161808.jpg',
 '20231004_161542.jpg',
 '._20231004_161542.jpg',
 '20231004_161541.jpg',
 '._20231004_161541.jpg',
 '20231004_161536.jpg',
 '._20231004_161536.jpg',
 '20231004_161253.jpg',
 '._20231004_161253.jpg',
 '20231004_161252.jpg',
 '._20231004_161252.jpg',
 '20231004_161234.jpg',
 '._20231004_161234.jpg',
 '20231004_161232.jpg',
 '._20231004_161232.jpg',
 '20231004_160830.jpg',
 '._20231004_160830.jpg',
 '20231004_160827.jpg',
 '._20231004_160827.jpg',
 '20231004_160825.jpg',
 '._20231004_160825.jpg',
 '20231004_160809.jpg',
 '._20231004_160809.jpg',
 '20231004_160237.jpg',
 '._20231004_160237.jpg',
 '20231004_160229.jpg',
 '._20231004_160229.jpg',
 '20231004_160058.jpg',
 '._20231004_160058.jpg',
 '20231004_160034.jpg',
 '._20231004_160034.jpg',
 '20231004_160028.jpg',
 '._20231004_160028.jpg',
 '20231004_160021.jpg',
 '._20231004_160021.jpg',
 '20231004_155800.jpg',
 '._20231004_155800.jpg',
 '20231004_155736.jpg',
 '._20231004_155736.jpg',
 '20231004_155728.jpg',
 '._20231004_155728.jpg',
 '20231004_155531.jpg',
 '._20231004_155531.jpg',
 '20231004_155528.jpg',
 '._20231004_155528.jpg',
 '20231004_154649.jpg',
 '._20231004_154649.jpg',
 '20231004_154444.jpg',
 '._20231004_154444.jpg',
 '20231004_154212.jpg',
 '._20231004_154212.jpg',
 '20231004_154211.jpg',
 '._20231004_154211.jpg',
 '20231004_154209.jpg',
 '._20231004_154209.jpg',
 '20231004_154156.jpg',
 '._20231004_154156.jpg',
 '20231004_154155.jpg',
 '._20231004_154155.jpg',
 '20231004_154124.jpg',
 '._20231004_154124.jpg',
 '20231004_154122.jpg',
 '._20231004_154122.jpg',
 '20231004_153811.jpg',
 '._20231004_153811.jpg',
 '20231004_153756.jpg',
 '._20231004_153756.jpg',
 '20231004_153229.jpg',
 '._20231004_153229.jpg',
 '20231004_153222.jpg',
 '._20231004_153222.jpg',
 '20231004_153138.jpg',
 '._20231004_153138.jpg',
 '20231004_153123.jpg',
 '._20231004_153123.jpg',
 '20231004_153119.jpg',
 '._20231004_153119.jpg',
 '20231004_153039.jpg',
 '._20231004_153039.jpg',
 '20231004_153034.jpg',
 '._20231004_153034.jpg',
 '20231004_153021.jpg',
 '._20231004_153021.jpg',
 '20231004_153018.jpg',
 '._20231004_153018.jpg',
 '20231004_153015.jpg',
 '._20231004_153015.jpg',
 '20231004_152814.jpg',
 '._20231004_152814.jpg',
 '20231004_152807.jpg',
 '._20231004_152807.jpg',
 '20231004_152806.jpg',
 '._20231004_152806.jpg',
 '20231004_152746.jpg',
 '._20231004_152746.jpg',
 '20231004_152446.jpg',
 '._20231004_152446.jpg',
 '20231004_152445.jpg',
 '._20231004_152445.jpg',
 '20231004_152420.jpg',
 '._20231004_152420.jpg',
 '20231004_152413.jpg',
 '._20231004_152413.jpg',
 '20231004_152210.jpg',
 '._20231004_152210.jpg',
 '20231004_152109.jpg',
 '._20231004_152109.jpg',
 '20231004_151900.jpg',
 '._20231004_151900.jpg',
 '20231004_151857.jpg',
 '._20231004_151857.jpg',
 '20231004_151852.jpg',
 '._20231004_151852.jpg',
 '20231004_151734.jpg',
 '._20231004_151734.jpg',
 '20231004_151720.jpg',
 '._20231004_151720.jpg',
 '20231004_150428.jpg',
 '._20231004_150428.jpg',
 '20231004_131231.jpg',
 '._20231004_131231.jpg',
 '20231004_111056.jpg',
 '._20231004_111056.jpg',
 '20231004_111048.jpg',
 '._20231004_111048.jpg',
 '20231004_075858.jpg',
 '._20231004_075858.jpg',
 '20231004_075853.jpg',
 '._20231004_075853.jpg',
 '20231003_180619.jpg',
 '._20231003_180619.jpg',
 '20231003_180618.jpg',
 '._20231003_180618.jpg',
 '20231003_180617.jpg',
 '._20231003_180617.jpg',
 '20231003_175958.jpg',
 '._20231003_175958.jpg',
 '20231003_144357.jpg',
 '._20231003_144357.jpg',
 '20231003_144348.jpg',
 '._20231003_144348.jpg',
 '20231003_144054.jpg',
 '._20231003_144054.jpg',
 '20231003_144051.jpg',
 '._20231003_144051.jpg',
 '20231003_144040.jpg',
 '._20231003_144040.jpg',
 '20231003_143607.jpg',
 '._20231003_143607.jpg',
 '20231003_143553.jpg',
 '._20231003_143553.jpg',
 '20231003_143541.jpg',
 '._20231003_143541.jpg',
 '20231003_143533.jpg',
 '._20231003_143533.jpg',
 '20231003_143524.jpg',
 '._20231003_143524.jpg',
 '20231003_143519.jpg',
 '._20231003_143519.jpg',
 '20231003_143504.jpg',
 '._20231003_143504.jpg',
 '20231003_142636.jpg',
 '._20231003_142636.jpg',
 '20231003_142634.jpg',
 '._20231003_142634.jpg',
 '20231003_142623.jpg',
 '._20231003_142623.jpg',
 '20231003_142622.jpg',
 '._20231003_142622.jpg',
 '20231003_142620.jpg',
 '._20231003_142620.jpg',
 '20231003_142522.jpg',
 '._20231003_142522.jpg',
 '20231003_142521.jpg',
 '._20231003_142521.jpg',
 '20231003_142520.jpg',
 '._20231003_142520.jpg',
 '20231003_142519.jpg',
 '._20231003_142519.jpg',
 '20231003_142221.jpg',
 '._20231003_142221.jpg',
 '20231003_141944.jpg',
 '._20231003_141944.jpg',
 '20231003_141943.jpg',
 '._20231003_141943.jpg',
 '20231003_141409.jpg',
 '._20231003_141409.jpg',
 '20231003_141351.jpg',
 '._20231003_141351.jpg',
 '20231003_140851.jpg',
 '._20231003_140851.jpg',
 '20231003_140845.jpg',
 '._20231003_140845.jpg',
 '20231003_135731.jpg',
 '._20231003_135731.jpg',
 '20231003_135455.jpg',
 '._20231003_135455.jpg',
 '20231003_135432.jpg',
 '._20231003_135432.jpg',
 '20231003_135428.jpg',
 '._20231003_135428.jpg',
 '20231003_135254.jpg',
 '._20231003_135254.jpg',
 '20231003_134529.jpg',
 '._20231003_134529.jpg',
 '20231003_134159.jpg',
 '._20231003_134159.jpg',
 '20231003_134135.jpg',
 '._20231003_134135.jpg',
 '20231003_134108.jpg',
 '._20231003_134108.jpg',
 '20231003_134014.jpg',
 '._20231003_134014.jpg',
 '20231003_133805.jpg',
 '._20231003_133805.jpg',
 '20231003_133804.jpg',
 '._20231003_133804.jpg',
 '20231003_133756.jpg',
 '._20231003_133756.jpg',
 '20231003_133755.jpg',
 '._20231003_133755.jpg',
 '20231003_133714.jpg',
 '._20231003_133714.jpg',
 '20231003_133702.jpg',
 '._20231003_133702.jpg',
 '20231003_133647.jpg',
 '._20231003_133647.jpg',
 '20231003_132901.jpg',
 '._20231003_132901.jpg',
 '20231003_132833.jpg',
 '._20231003_132833.jpg',
 '20231003_132830.jpg',
 '._20231003_132830.jpg',
 '20231003_132812.jpg',
 '._20231003_132812.jpg',
 '20231003_132811.jpg',
 '._20231003_132811.jpg',
 '20231003_132634.jpg',
 '._20231003_132634.jpg',
 '20231003_132552.jpg',
 '._20231003_132552.jpg',
 '20231003_131338.jpg',
 '._20231003_131338.jpg',
 '20231003_131334.jpg',
 '._20231003_131334.jpg',
 '20231003_130933.jpg',
 '._20231003_130933.jpg',
 '20231003_130854.jpg',
 '._20231003_130854.jpg',
 '20231003_130844.jpg',
 '._20231003_130844.jpg',
 '20231003_130815.jpg',
 '._20231003_130815.jpg',
 '20231003_130813.jpg',
 '._20231003_130813.jpg',
 '20231003_130811.jpg',
 '._20231003_130811.jpg',
 '20231003_130740.jpg',
 '._20231003_130740.jpg',
 '20231003_130724.jpg',
 '._20231003_130724.jpg',
 '20231003_130717.jpg',
 '._20231003_130717.jpg',
 '20231003_130506.jpg',
 '._20231003_130506.jpg',
 '20231003_130135.jpg',
 '._20231003_130135.jpg',
 '20231003_125844.jpg',
 '._20231003_125844.jpg',
 '20231003_125841.jpg',
 '._20231003_125841.jpg',
 '20231003_125705.jpg',
 '._20231003_125705.jpg',
 '20231003_124659.jpg',
 '._20231003_124659.jpg',
 '20231003_124657.jpg',
 '._20231003_124657.jpg',
 '20231003_124535.jpg',
 '._20231003_124535.jpg',
 '20231003_124529.jpg',
 '._20231003_124529.jpg',
 '20231003_124111.jpg',
 '._20231003_124111.jpg',
 '20231003_124056.jpg',
 '._20231003_124056.jpg',
 '20231003_123259.jpg',
 '._20231003_123259.jpg',
 '20231003_123258.jpg',
 '._20231003_123258.jpg',
 '20231003_123146.jpg',
 '._20231003_123146.jpg',
 '20231003_123111.jpg',
 '._20231003_123111.jpg',
 '20231003_123007.jpg',
 '._20231003_123007.jpg',
 '20231003_122331.jpg',
 '._20231003_122331.jpg',
 '20231003_122325.jpg',
 '._20231003_122325.jpg',
 '20231003_092845.jpg',
 '._20231003_092845.jpg',
 '20231003_092838.jpg',
 '._20231003_092838.jpg',
 '20231002_224257.jpg',
 '._20231002_224257.jpg',
 '20231002_224230.jpg',
 '._20231002_224230.jpg',
 '20231002_224048.jpg',
 '._20231002_224048.jpg',
 '20231002_224046.jpg',
 '._20231002_224046.jpg',
 '20231002_224044.jpg',
 '._20231002_224044.jpg',
 '20231002_224016.jpg',
 '._20231002_224016.jpg',
 '20231002_224015.jpg',
 '._20231002_224015.jpg',
 '20231002_224010.jpg',
 '._20231002_224010.jpg',
 '20231002_224001.jpg',
 '._20231002_224001.jpg',
 '20231002_223118.jpg',
 '._20231002_223118.jpg',
 '20231002_212300.jpg',
 '._20231002_212300.jpg',
 '20231002_211528.jpg',
 '._20231002_211528.jpg',
 '20231002_211511.jpg',
 '._20231002_211511.jpg',
 '20231002_211508.jpg',
 '._20231002_211508.jpg',
 '20231002_211347.jpg',
 '._20231002_211347.jpg',
 '20231002_211041.jpg',
 '._20231002_211041.jpg',
 '20231002_211033.jpg',
 '._20231002_211033.jpg',
 '20231002_204530.mp4',
 '._20231002_204530.mp4',
 '20231002_204341(0).jpg',
 '._20231002_204341(0).jpg',
 '20231002_204341.jpg',
 '._20231002_204341.jpg',
 '20231002_204340.jpg',
 '._20231002_204340.jpg',
 '20231002_204324.jpg',
 '._20231002_204324.jpg',
 '20231002_202204.jpg',
 '._20231002_202204.jpg',
 '20231002_194904.jpg',
 '._20231002_194904.jpg',
 '20231002_194900.jpg',
 '._20231002_194900.jpg',
 '20231002_194457.jpg',
 '._20231002_194457.jpg',
 '20231002_194233.jpg',
 '._20231002_194233.jpg',
 '20231002_194118.jpg',
 '._20231002_194118.jpg',
 '20231002_194056.jpg',
 '._20231002_194056.jpg',
 '20231002_194037.jpg',
 '._20231002_194037.jpg',
 '20231002_194021.jpg',
 '._20231002_194021.jpg',
 '20231002_193712.jpg',
 '._20231002_193712.jpg',
 '20231002_193531.jpg',
 '._20231002_193531.jpg',
 '20231002_193514.jpg',
 '._20231002_193514.jpg',
 '20231002_193252.jpg',
 '._20231002_193252.jpg',
 '20231002_193249.jpg',
 '._20231002_193249.jpg',
 '20231002_193021.jpg',
 '._20231002_193021.jpg',
 '20231002_192215.jpg',
 '._20231002_192215.jpg',
 '20231002_191553.jpg',
 '._20231002_191553.jpg',
 '20231002_191454.jpg',
 '._20231002_191454.jpg',
 '20231002_191450.jpg',
 '._20231002_191450.jpg',
 '20231002_191417.jpg',
 '._20231002_191417.jpg',
 '20231002_191415.jpg',
 '._20231002_191415.jpg',
 '20231002_191251.jpg',
 '._20231002_191251.jpg',
 '20231002_191224.jpg',
 '._20231002_191224.jpg',
 '20231002_191215.jpg',
 '._20231002_191215.jpg',
 '20231002_184419.jpg',
 '._20231002_184419.jpg',
 '20231002_184139.jpg',
 '._20231002_184139.jpg',
 '20231002_184136.jpg',
 '._20231002_184136.jpg',
 '20231002_184046.jpg',
 '._20231002_184046.jpg',
 '20231002_184021.jpg',
 '._20231002_184021.jpg',
 '20231002_183847.jpg',
 '._20231002_183847.jpg',
 '20231002_183839.jpg',
 '._20231002_183839.jpg',
 '20231002_183815.jpg',
 '._20231002_183815.jpg',
 '20231002_183806.jpg',
 '._20231002_183806.jpg',
 '20231002_183624.jpg',
 '._20231002_183624.jpg',
 '20231002_183622.jpg',
 '._20231002_183622.jpg',
 '20231002_183621.jpg',
 '._20231002_183621.jpg',
 '20231002_183315.jpg',
 '._20231002_183315.jpg',
 '20231002_183255.jpg',
 '._20231002_183255.jpg',
 '20231002_183155.jpg',
 '._20231002_183155.jpg',
 '20231002_183005.jpg',
 '._20231002_183005.jpg',
 '20231002_182836.jpg',
 '._20231002_182836.jpg',
 '20231002_182830.jpg',
 '._20231002_182830.jpg',
 '20231002_182522.jpg',
 '._20231002_182522.jpg',
 '20231002_182517.jpg',
 '._20231002_182517.jpg',
 '20231002_182455.jpg',
 '._20231002_182455.jpg',
 '20231002_182340.jpg',
 '._20231002_182340.jpg',
 '20231002_182336.jpg',
 '._20231002_182336.jpg',
 '20231002_182311.jpg',
 '._20231002_182311.jpg',
 '20231002_182308.jpg',
 '._20231002_182308.jpg',
 '20231002_182245.jpg',
 '._20231002_182245.jpg',
 '20231002_181228.jpg',
 '._20231002_181228.jpg',
 '20231002_181135.jpg',
 '._20231002_181135.jpg',
 '20231002_181134.jpg',
 '._20231002_181134.jpg',
 '20231002_163507.jpg',
 '._20231002_163507.jpg',
 '20231002_163505.jpg',
 '._20231002_163505.jpg',
 '20231002_163347.jpg',
 '._20231002_163347.jpg',
 '20231002_163259.jpg',
 '._20231002_163259.jpg',
 '20231002_161638.jpg',
 '._20231002_161638.jpg',
 '20231002_161631.jpg',
 '._20231002_161631.jpg',
 '20231002_161549.jpg',
 '._20231002_161549.jpg',
 '20231002_152736.jpg',
 '._20231002_152736.jpg',
 '20231002_152724.jpg',
 '._20231002_152724.jpg',
 '20231002_143629.jpg',
 '._20231002_143629.jpg',
 '20231002_135702.jpg',
 '._20231002_135702.jpg',
 '20231002_135651.jpg',
 '._20231002_135651.jpg',
 '20231002_135648.jpg',
 '._20231002_135648.jpg',
 '20231002_135636.jpg',
 '._20231002_135636.jpg',
 '20231002_135315.jpg',
 '._20231002_135315.jpg',
 '20231001_193755.jpg',
 '._20231001_193755.jpg',
 '20231001_193753.jpg',
 '._20231001_193753.jpg',
 '20231001_193718.jpg',
 '._20231001_193718.jpg',
 '20231001_193049.jpg',
 '._20231001_193049.jpg',
 '20231001_193038.jpg',
 '._20231001_193038.jpg',
 '20231001_193036.jpg',
 '._20231001_193036.jpg',
 '20231001_193030.jpg',
 '._20231001_193030.jpg',
 '20231001_190224.jpg',
 '._20231001_190224.jpg',
 '20231001_190014.jpg',
 '._20231001_190014.jpg',
 '20231001_190001.jpg',
 '._20231001_190001.jpg',
 '20231001_185957.jpg',
 '._20231001_185957.jpg',
 '20231001_185744.jpg',
 '._20231001_185744.jpg',
 '20231001_184238.jpg',
 '._20231001_184238.jpg',
 '20231001_184226(0).jpg',
 '._20231001_184226(0).jpg',
 '20231001_184226.jpg',
 '._20231001_184226.jpg',
 '20231001_184222.jpg',
 '._20231001_184222.jpg',
 '20231001_184211.jpg',
 '._20231001_184211.jpg',
 '20231001_183724.jpg',
 '._20231001_183724.jpg',
 '20231001_183717.jpg',
 '._20231001_183717.jpg',
 '20231001_183702.jpg',
 '._20231001_183702.jpg',
 '20231001_183601.jpg',
 '._20231001_183601.jpg',
 '20231001_183336.jpg',
 '._20231001_183336.jpg',
 '20231001_183334.jpg',
 '._20231001_183334.jpg',
 '20231001_183326.jpg',
 '._20231001_183326.jpg',
 '20231001_183324.jpg',
 '._20231001_183324.jpg',
 '20231001_183311.jpg',
 '._20231001_183311.jpg',
 '20231001_183257.jpg',
 '._20231001_183257.jpg',
 '20231001_183255.jpg',
 '._20231001_183255.jpg',
 '20231001_183249.jpg',
 '._20231001_183249.jpg',
 '20231001_183206.jpg',
 '._20231001_183206.jpg',
 '20231001_183204.jpg',
 '._20231001_183204.jpg',
 '20231001_183201.jpg',
 '._20231001_183201.jpg',
 '20231001_183200.jpg',
 '._20231001_183200.jpg',
 '20231001_182816.jpg',
 '._20231001_182816.jpg',
 '20231001_182814.jpg',
 '._20231001_182814.jpg',
 '20231001_182808.jpg',
 '._20231001_182808.jpg',
 '20231001_182737.jpg',
 '._20231001_182737.jpg',
 '20231001_182732.jpg',
 '._20231001_182732.jpg',
 '20231001_182518.jpg',
 '._20231001_182518.jpg',
 '20231001_182418.jpg',
 '._20231001_182418.jpg',
 '20231001_182406.jpg',
 '._20231001_182406.jpg',
 '20231001_182326.jpg',
 '._20231001_182326.jpg',
 '20231001_182206.jpg',
 '._20231001_182206.jpg',
 '20231001_182123.jpg',
 '._20231001_182123.jpg',
 '20231001_182116.jpg',
 '._20231001_182116.jpg',
 '20231001_182044.jpg',
 '._20231001_182044.jpg',
 '20231001_182017.jpg',
 '._20231001_182017.jpg',
 '20231001_181931.jpg',
 '._20231001_181931.jpg',
 '20231001_181815.jpg',
 '._20231001_181815.jpg',
 '20231001_181812.jpg',
 '._20231001_181812.jpg',
 '20231001_181725.jpg',
 '._20231001_181725.jpg',
 '20231001_181720.jpg',
 '._20231001_181720.jpg',
 '20231001_181708.jpg',
 '._20231001_181708.jpg',
 '20231001_181427.jpg',
 '._20231001_181427.jpg',
 '20231001_181421.jpg',
 '._20231001_181421.jpg',
 '20231001_181228.jpg',
 '._20231001_181228.jpg',
 '20231001_181225.jpg',
 '._20231001_181225.jpg',
 '20231001_181041.jpg',
 '._20231001_181041.jpg',
 '20231001_181039.jpg',
 '._20231001_181039.jpg',
 '20231001_181036.jpg',
 '._20231001_181036.jpg',
 '20231001_161254.jpg',
 '._20231001_161254.jpg',
 '20231001_161248.jpg',
 '._20231001_161248.jpg',
 '20231001_161224.jpg',
 '._20231001_161224.jpg',
 '20231001_161220.jpg',
 '._20231001_161220.jpg',
 '20231001_161027.jpg',
 '._20231001_161027.jpg',
 '20231001_160811.jpg',
 '._20231001_160811.jpg',
 '20231001_160805.jpg',
 '._20231001_160805.jpg',
 '20231001_160707.jpg',
 '._20231001_160707.jpg',
 '20231001_160224.jpg',
 '._20231001_160224.jpg',
 '20231001_152206.jpg',
 '._20231001_152206.jpg',
 '20231001_151026.jpg',
 '._20231001_151026.jpg',
 '20231001_150933.jpg',
 '._20231001_150933.jpg',
 '20231001_150916.jpg',
 '._20231001_150916.jpg',
 '20231001_150910.jpg',
 '._20231001_150910.jpg',
 '20231001_150905.jpg',
 '._20231001_150905.jpg',
 '20231001_145652.jpg',
 '._20231001_145652.jpg',
 '20231001_145649.jpg',
 '._20231001_145649.jpg',
 '20231001_144605.jpg',
 '._20231001_144605.jpg',
 '20231001_144603.jpg',
 '._20231001_144603.jpg',
 '20231001_133728.jpg',
 '._20231001_133728.jpg',
 '20231001_120053.jpg',
 '._20231001_120053.jpg',
 '20231001_120041.jpg',
 '._20231001_120041.jpg',
 '20231001_120018.jpg',
 '._20231001_120018.jpg',
 '20231001_120005.jpg',
 '._20231001_120005.jpg',
 '20231001_114514.jpg',
 '._20231001_114514.jpg',
 '20231001_114512.jpg',
 '._20231001_114512.jpg',
 '20231001_114507.jpg',
 '._20231001_114507.jpg',
 '20231001_114505.jpg',
 '._20231001_114505.jpg',
 '20231001_114441.jpg',

In [17]:
for photo in os.listdir(p):
    if not photo.startswith('.'):
        prefix = photo.split('.')[0]
        # specially deal with the photo prefix names end with (x)
        if prefix.endswith(')'):  # e.g.20231004_171155(1).jpg
            suffix = photo.split('.')[1]
            base_name = '.'.join([prefix[:-3], suffix])
            if check_file_exists(postprocess_photo_path, base_name):
                os.remove(os.path.join(postprocess_photo_path, photo))
        elif photo.startswith('_'):
            print(photo)
            print(prefix)
            print(os.path.exists(os.path.join(p, photo)))
        else:
            e = f'{photo} in Camera folder with wrong type'
            assert prefix.split('_')[0].isdigit() and prefix.split('_')[1].isdigit(), e
            assert (len(prefix.split('_')[0]) == 8) and (len(prefix.split('_')[0]) == 8), e

_20231005_082230.jpg
_20231005_082230
False
_20231005_082220.jpg
_20231005_082220
False
_20231004_204753.jpg
_20231004_204753
False
_20231004_203409.jpg
_20231004_203409
False
_20231004_203405.jpg
_20231004_203405
False
_20231004_203139.jpg
_20231004_203139
False
_20231004_203044.jpg
_20231004_203044
False
_20231004_203039.jpg
_20231004_203039
False
_20231004_202824.jpg
_20231004_202824
False
_20231004_202156.jpg
_20231004_202156
False
_20231004_193839.jpg
_20231004_193839
False
_20231004_172232.jpg
_20231004_172232
False
_20231004_172227.jpg
_20231004_172227
False
_20231004_172226.jpg
_20231004_172226
False
_20231004_172152.jpg
_20231004_172152
False
_20231004_172128.jpg
_20231004_172128
False
_20231004_172125.jpg
_20231004_172125
False
_20231004_172123.jpg
_20231004_172123
False
_20231004_172122.jpg
_20231004_172122
False
_20231004_172036.jpg
_20231004_172036
False
_20231004_171802.jpg
_20231004_171802
False
_20231004_171726.jpg
_20231004_171726
False
_20231004_171724.jpg
_20231004_171724
False
_20231004_171712.jpg
_20231004_171712
False
_20231004_171638.jpg
_20231004_171638
False
_20231004_171637.jpg
_20231004_171637
False
_20231004_171636.jpg
_20231004_171636
False
_20231004_171635.jpg
_20231004_171635
False
_20231004_171634.jpg
_20231004_171634
False
_20231004_171549.jpg
_20231004_171549
False
_20231004_171546.jpg
_20231004_171546
False
_20231004_171538.jpg
_20231004_171538
False
_20231004_171524.jpg
_20231004_171524
False
_20231004_171517.jpg
_20231004_171517
False
_20231004_171503.jpg
_20231004_171503
False
_20231004_171502.jpg
_20231004_171502
False
_20231004_171451.jpg
_20231004_171451
False
_20231004_171446.jpg
_20231004_171446
False
_20231004_171250.jpg
_20231004_171250
False
_20231004_171248.jpg
_20231004_171248
False
_20231004_171247.jpg
_20231004_171247
False
_20231004_171159.jpg
_20231004_171159
False
_20231004_171156.jpg
_20231004_171156
False
_20231004_171155.jpg
_20231004_171155
False
_20231004_171135.jpg
_20231004_171135
False
_20231004_171131.jpg
_20231004_171131
False
_20231004_170932.jpg
_20231004_170932
False
_20231004_170831.jpg
_20231004_170831
False
_20231004_170827.jpg
_20231004_170827
False
_20231004_170826.jpg
_20231004_170826
False
_20231004_170727.jpg
_20231004_170727
False
_20231004_170620.jpg
_20231004_170620
False
_20231004_163330.jpg
_20231004_163330
False
_20231004_163328.jpg
_20231004_163328
False
_20231004_163323.jpg
_20231004_163323
False
_20231004_163321.jpg
_20231004_163321
False
_20231004_163232.jpg
_20231004_163232
False
_20231004_163225.jpg
_20231004_163225
False
_20231004_163221.jpg
_20231004_163221
False
_20231004_163219.jpg
_20231004_163219
False
_20231004_162930.jpg
_20231004_162930
False
_20231004_162920.jpg
_20231004_162920
False
_20231004_162748.jpg
_20231004_162748
False
_20231004_162550.jpg
_20231004_162550
False
_20231004_162549.jpg
_20231004_162549
False
_20231004_162540.jpg
_20231004_162540
False
_20231004_162539.jpg
_20231004_162539
False
_20231004_162227.jpg
_20231004_162227
False
_20231004_162018.jpg
_20231004_162018
False
_20231004_161808.jpg
_20231004_161808
False
_20231004_161542.jpg
_20231004_161542
False
_20231004_161541.jpg
_20231004_161541
False
_20231004_161536.jpg
_20231004_161536
False
_20231004_161253.jpg
_20231004_161253
False
_20231004_161252.jpg
_20231004_161252
False
_20231004_161234.jpg
_20231004_161234
False
_20231004_161232.jpg
_20231004_161232
False
_20231004_160830.jpg
_20231004_160830
False
_20231004_160827.jpg
_20231004_160827
False
_20231004_160825.jpg
_20231004_160825
False
_20231004_160809.jpg
_20231004_160809
False
_20231004_160237.jpg
_20231004_160237
False
_20231004_160229.jpg
_20231004_160229
False
_20231004_160058.jpg
_20231004_160058
False
_20231004_160034.jpg
_20231004_160034
False
_20231004_160028.jpg
_20231004_160028
False
_20231004_160021.jpg
_20231004_160021
False
_20231004_155800.jpg
_20231004_155800
False
_20231004_155736.jpg
_20231004_155736
False
_20231004_155728.jpg
_20231004_155728
False
_20231004_155531.jpg
_20231004_155531
False
_20231004_155528.jpg
_20231004_155528
False
_20231004_154649.jpg
_20231004_154649
False
_20231004_154444.jpg
_20231004_154444
False
_20231004_154212.jpg
_20231004_154212
False
_20231004_154211.jpg
_20231004_154211
False
_20231004_154209.jpg
_20231004_154209
False
_20231004_154156.jpg
_20231004_154156
False
_20231004_154155.jpg
_20231004_154155
False
_20231004_154124.jpg
_20231004_154124
False
_20231004_154122.jpg
_20231004_154122
False
_20231004_153811.jpg
_20231004_153811
False
_20231004_153756.jpg
_20231004_153756
False
_20231004_153229.jpg
_20231004_153229
False
_20231004_153222.jpg
_20231004_153222
False
_20231004_153138.jpg
_20231004_153138
False
_20231004_153123.jpg
_20231004_153123
False
_20231004_153119.jpg
_20231004_153119
False
_20231004_153039.jpg
_20231004_153039
False
_20231004_153034.jpg
_20231004_153034
False
_20231004_153021.jpg
_20231004_153021
False
_20231004_153018.jpg
_20231004_153018
False
_20231004_153015.jpg
_20231004_153015
False
_20231004_152814.jpg
_20231004_152814
False
_20231004_152807.jpg
_20231004_152807
False
_20231004_152806.jpg
_20231004_152806
False
_20231004_152746.jpg
_20231004_152746
False
_20231004_152446.jpg
_20231004_152446
False
_20231004_152445.jpg
_20231004_152445
False
_20231004_152420.jpg
_20231004_152420
False
_20231004_152413.jpg
_20231004_152413
False
_20231004_152210.jpg
_20231004_152210
False
_20231004_152109.jpg
_20231004_152109
False
_20231004_151900.jpg
_20231004_151900
False
_20231004_151857.jpg
_20231004_151857
False
_20231004_151852.jpg
_20231004_151852
False
_20231004_151734.jpg
_20231004_151734
False
_20231004_151720.jpg
_20231004_151720
False
_20231004_150428.jpg
_20231004_150428
False
_20231004_131231.jpg
_20231004_131231
False
_20231004_111056.jpg
_20231004_111056
False
_20231004_111048.jpg
_20231004_111048
False
_20231004_075858.jpg
_20231004_075858
False
_20231004_075853.jpg
_20231004_075853
False
_20231003_180619.jpg
_20231003_180619
False
_20231003_180618.jpg
_20231003_180618
False
_20231003_180617.jpg
_20231003_180617
False
_20231003_175958.jpg
_20231003_175958
False
_20231003_144357.jpg
_20231003_144357
False
_20231003_144348.jpg
_20231003_144348
False
_20231003_144054.jpg
_20231003_144054
False
_20231003_144051.jpg
_20231003_144051
False
_20231003_144040.jpg
_20231003_144040
False
_20231003_143607.jpg
_20231003_143607
False
_20231003_143553.jpg
_20231003_143553
False
_20231003_143541.jpg
_20231003_143541
False
_20231003_143533.jpg
_20231003_143533
False
_20231003_143524.jpg
_20231003_143524
False
_20231003_143519.jpg
_20231003_143519
False
_20231003_143504.jpg
_20231003_143504
False
_20231003_142636.jpg
_20231003_142636
False
_20231003_142634.jpg
_20231003_142634
False
_20231003_142623.jpg
_20231003_142623
False
_20231003_142622.jpg
_20231003_142622
False
_20231003_142620.jpg
_20231003_142620
False
_20231003_142522.jpg
_20231003_142522
False
_20231003_142521.jpg
_20231003_142521
False
_20231003_142520.jpg
_20231003_142520
False
_20231003_142519.jpg
_20231003_142519
False
_20231003_142221.jpg
_20231003_142221
False
_20231003_141944.jpg
_20231003_141944
False
_20231003_141943.jpg
_20231003_141943
False
_20231003_141409.jpg
_20231003_141409
False
_20231003_141351.jpg
_20231003_141351
False
_20231003_140851.jpg
_20231003_140851
False
_20231003_140845.jpg
_20231003_140845
False
_20231003_135731.jpg
_20231003_135731
False
_20231003_135455.jpg
_20231003_135455
False
_20231003_135432.jpg
_20231003_135432
False
_20231003_135428.jpg
_20231003_135428
False
_20231003_135254.jpg
_20231003_135254
False
_20231003_134529.jpg
_20231003_134529
False
_20231003_134159.jpg
_20231003_134159
False
_20231003_134135.jpg
_20231003_134135
False
_20231003_134108.jpg
_20231003_134108
False
_20231003_134014.jpg
_20231003_134014
False
_20231003_133805.jpg
_20231003_133805
False
_20231003_133804.jpg
_20231003_133804
False
_20231003_133756.jpg
_20231003_133756
False
_20231003_133755.jpg
_20231003_133755
False
_20231003_133714.jpg
_20231003_133714
False
_20231003_133702.jpg
_20231003_133702
False
_20231003_133647.jpg
_20231003_133647
False
_20231003_132901.jpg
_20231003_132901
False
_20231003_132833.jpg
_20231003_132833
False
_20231003_132830.jpg
_20231003_132830
False
_20231003_132812.jpg
_20231003_132812
False
_20231003_132811.jpg
_20231003_132811
False
_20231003_132634.jpg
_20231003_132634
False
_20231003_132552.jpg
_20231003_132552
False
_20231003_131338.jpg
_20231003_131338
False
_20231003_131334.jpg
_20231003_131334
False
_20231003_130933.jpg
_20231003_130933
False
_20231003_130854.jpg
_20231003_130854
False
_20231003_130844.jpg
_20231003_130844
False
_20231003_130815.jpg
_20231003_130815
False
_20231003_130813.jpg
_20231003_130813
False
_20231003_130811.jpg
_20231003_130811
False
_20231003_130740.jpg
_20231003_130740
False
_20231003_130724.jpg
_20231003_130724
False
_20231003_130717.jpg
_20231003_130717
False
_20231003_130506.jpg
_20231003_130506
False
_20231003_130135.jpg
_20231003_130135
False
_20231003_125844.jpg
_20231003_125844
False
_20231003_125841.jpg
_20231003_125841
False
_20231003_125705.jpg
_20231003_125705
False
_20231003_124659.jpg
_20231003_124659
False
_20231003_124657.jpg
_20231003_124657
False
_20231003_124535.jpg
_20231003_124535
False
_20231003_124529.jpg
_20231003_124529
False
_20231003_124111.jpg
_20231003_124111
False
_20231003_124056.jpg
_20231003_124056
False
_20231003_123259.jpg
_20231003_123259
False
_20231003_123258.jpg
_20231003_123258
False
_20231003_123146.jpg
_20231003_123146
False
_20231003_123111.jpg
_20231003_123111
False
_20231003_123007.jpg
_20231003_123007
False
_20231003_122331.jpg
_20231003_122331
False
_20231003_122325.jpg
_20231003_122325
False
_20231003_092845.jpg
_20231003_092845
False
_20231003_092838.jpg
_20231003_092838
False
_20231002_224257.jpg
_20231002_224257
False
_20231002_224230.jpg
_20231002_224230
False
_20231002_224048.jpg
_20231002_224048
False
_20231002_224046.jpg
_20231002_224046
False
_20231002_224044.jpg
_20231002_224044
False
_20231002_224016.jpg
_20231002_224016
False
_20231002_224015.jpg
_20231002_224015
False
_20231002_224010.jpg
_20231002_224010
False
_20231002_224001.jpg
_20231002_224001
False
_20231002_223118.jpg
_20231002_223118
False
_20231002_212300.jpg
_20231002_212300
False
_20231002_211528.jpg
_20231002_211528
False
_20231002_211511.jpg
_20231002_211511
False
_20231002_211508.jpg
_20231002_211508
False
_20231002_211347.jpg
_20231002_211347
False
_20231002_211041.jpg
_20231002_211041
False
_20231002_211033.jpg
_20231002_211033
False
_20231002_204530.mp4
_20231002_204530
False

NameError: name 'check_file_exists' is not defined

In [4]:
categorize_photos()

(0, 0)