In [3]:
import pandas as pd
import numpy as np
# from lwpackage.factors import BackTester
# from lwpackage.models import LightGBM
from lwpackage.lwstats import row_count_at_percentage

In [3]:
bt = BackTester(fc_number_list=[1, 2, 3, 4], 
                instrument_type='stock',
                start_time='20160101', 
                end_time='20200101', 
                fc_freq = '1d',
                risk_free_rate=True,
                cost=0.00025,
                quantile=0.2,
                ir=True,
                longshort_instrument_number=5,
                yearly_performance=True,
                )

In [672]:
df_turnover

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1
time,,,,,,,,,,,
2016-01-04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2016-01-05,1.739583,1.664921,1.739583,1.759162,1.790576,1.738220,1.748691,1.760417,1.832461,1.312500,3.052083
2016-01-06,1.802083,1.729167,1.770833,1.769634,1.750000,1.750000,1.759162,1.708333,1.635417,1.260417,3.062500
2016-01-07,1.802083,1.729167,1.739583,1.780105,1.729167,1.812500,1.832461,1.750000,1.718750,1.281250,3.083333
2016-01-08,1.750000,1.781250,1.822917,1.748691,1.770833,1.750000,1.863874,1.750000,1.656250,1.197917,2.947917
...,...,...,...,...,...,...,...,...,...,...,...
2019-12-25,1.833935,1.811594,1.724638,1.760870,1.775362,1.717391,1.789855,1.739130,1.702899,1.155235,2.989170
2019-12-26,1.841155,1.775362,1.804348,1.818841,1.826087,1.782609,1.797101,1.833333,1.644928,1.140794,2.981949
2019-12-27,1.790614,1.746377,1.746377,1.754513,1.746377,1.731884,1.797834,1.702899,1.666667,1.155235,2.945848
2019-12-30,1.776173,1.747292,1.725632,1.747292,1.740072,1.754513,1.732852,1.740072,1.638989,1.184116,2.960289
2019-12-31,1.812274,1.754513,1.768953,1.812274,1.797834,1.682310,1.740072,1.747292,1.602888,1.205776,3.018051

In [675]:
df_gross_ret_ts

                fac1      fac2
time
2016-01-04  6.398909  3.334447
2016-01-05  4.794766  2.526908
2016-01-06  6.825663  3.294571
2016-01-07  7.549034  3.478146
2016-01-08  5.162780  2.718761
2016-01-11  6.827440  4.160085

In [687]:
(df_net_ret[ret_col].apply(lambda x: len(x[x > 0]) / len(x))).to_frame('all').T

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret
all,0.0,0.0,0.0,0.0,0.0,0.670769,1.0,1.0,1.0,1.0,1.0,1.0

In [689]:
(df_net_ret[ret_col].apply(lambda x: len(x[x > 0]) / len(x))).to_frame('all').T

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret
all,0.0,0.0,0.0,0.0,0.0,0.670769,1.0,1.0,1.0,1.0,1.0,1.0

In [5]:
bt.backtest()

/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_utils.py:104: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['rate'] = df['rate'].fillna(method='bfill').fillna(method='ffill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_utils.py:104: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['rate'] = df['rate'].fillna(method='bfill').fillna(method='ffill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_utils.py:104: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['rate'] = df['rate'].fillna(method='bfill').fillna(method='ffill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_utils.py:104: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['rate'] = df['rate'].fillna(method='bfill').fillna(method='ffill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:222: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_short_ret[f'ret_short_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:222: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_short_ret[f'ret_short_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:222: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_short_ret[f'ret_short_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:222: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_short_ret[f'ret_short_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:222: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_short_ret[f'ret_short_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:222: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_short_ret[f'ret_short_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:222: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_short_ret[f'ret_short_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:222: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_short_ret[f'ret_short_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:222: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_short_ret[f'ret_short_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:222: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_short_ret[f'ret_short_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:222: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_short_ret[f'ret_short_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:222: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_short_ret[f'ret_short_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:222: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_short_ret[f'ret_short_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:222: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_short_ret[f'ret_short_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:222: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_short_ret[f'ret_short_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:222: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_short_ret[f'ret_short_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:222: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_short_ret[f'ret_short_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:222: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_short_ret[f'ret_short_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:222: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_short_ret[f'ret_short_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:222: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_short_ret[f'ret_short_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:222: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_short_ret[f'ret_short_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:222: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_short_ret[f'ret_short_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:222: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_short_ret[f'ret_short_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:222: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_short_ret[f'ret_short_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:222: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_short_ret[f'ret_short_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_long_ret[f'ret_long_{self.longshort_instrument_number - i}'].fillna(method='bfill')
/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/lwpackage/lwfactors/factor_indicators.py:214: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.

In [9]:
bt.performance

,year,fc_number,fc_name,fc_freq,IC,Rank IC,Gross Sharpe,Net Sharpe,Gross TS-Sharpe,Net TS-Sharpe,...,Net Annualized Volatility,Gross TS-Annualized Volatility,Net TS-Annualized Volatility,Long Daily Turnover,Short Daily Turnover,Longshort Daily Turnover,Max Gross Drawdown,Max Net Drawdown,TS-Max Gross Drawdown,TS-Max Net Drawdown
0,2016,1,mom,1d,0.055363,-0.029804,0.087061,0.033738,1.004125,0.986877,...,0.573730,1.226557,1.229032,0.444453,0.526849,0.485651,2.060007,2.073686,1.521946,1.551327
1,2017,1,mom,1d,0.045456,-0.002680,4.787482,4.696027,5.588011,5.583633,...,0.326140,0.295339,0.295340,0.450739,0.502403,0.476571,0.244499,0.247115,0.137477,0.137570
2,2018,1,mom,1d,-0.013505,-0.033302,-3.837559,-3.919271,-2.364897,-2.370673,...,0.376842,0.247150,0.247160,0.470806,0.494805,0.482806,1.352171,1.378713,0.670161,0.671172
3,all,1,mom,1d,0.020092,-0.028303,-0.520770,-0.600263,0.926174,0.913164,...,0.383388,0.485210,0.485834,0.452577,0.513681,0.483129,2.060007,2.073686,1.521946,1.551327
0,2016,2,upper_line,1d,-0.058345,-0.041864,-11.746597,-11.904314,-18.317692,-18.354378,...,0.146524,0.111137,0.111263,0.299257,0.437954,0.368606,1.661751,1.684078,1.974465,1.974448
1,2017,2,upper_line,1d,-0.034495,-0.045903,-8.970423,-9.094217,-10.294412,-10.303444,...,0.182268,0.133961,0.133964,0.287963,0.421814,0.354888,1.562871,1.585376,1.303903,1.305022
2,2018,2,upper_line,1d,-0.027330,-0.041302,-4.414540,-4.508283,-6.134324,-6.144993,...,0.234463,0.134212,0.134214,0.289351,0.411745,0.350548,0.998813,1.011374,0.847051,0.848046
3,all,2,upper_line,1d,-0.031556,-0.038841,-6.462428,-6.586940,-9.094423,-9.114245,...,0.180894,0.118362,0.118396,0.292458,0.423385,0.357922,4.516832,4.592303,4.305849,4.313751
0,2016,3,win_ratio,1d,0.008312,0.003618,-1.191860,-1.285320,-0.408504,-0.397270,...,0.454895,0.314582,0.315269,0.656558,0.692285,0.674422,1.302886,1.321559,0.860322,0.855149
1,2017,3,win_ratio,1d,-0.001559,-0.016563,-2.284378,-2.473624,-1.179328,-1.187243,...,0.212518,0.156887,0.156891,0.639694,0.632539,0.636117,0.645267,0.657491,0.463163,0.463542
2,2018,3,win_ratio,1d,-0.006815,-0.016824,-2.533424,-2.688149,-1.782947,-1.790731,...,0.254144,0.183884,0.183892,0.628377,0.615390,0.621883,0.872993,0.896052,0.566636,0.567398
3,all,3,win_ratio,1d,-0.002031,-0.013801,-2.029710,-2.177701,-1.238818,-1.238908,...,0.274014,0.195199,0.195374,0.637172,0.646741,0.641956,2.280061,2.415884,1.044107,1.043850
0,2016,4,location,1d,-0.013042,-0.005340,-2.685459,-2.755117,-3.191993,-3.119418,...,0.347509,0.281945,0.281760,0.392855,0.366010,0.379433,1.864173,1.874541,1.448924,1.422630
1,2017,4,location,1d,-0.002670,-0.006940,-0.815178,-0.896645,-0.828784,-0.834818,...,0.287473,0.204756,0.204759,0.362341,0.379750,0.371045,0.549348,0.554769,0.394812,0.395087
2,2018,4,location,1d,-0.022053,-0.020939,-3.227716,-3.301262,-3.839061,-3.845185,...,0.312688,0.230096,0.230105,0.361469,0.371483,0.366476,1.078690,1.094123,0.928305,0.929344
3,all,4,location,1d,-0.012043,-0.015100,-2.192952,-2.271601,-2.629838,-2.611473,...,0.300326,0.223456,0.223415,0.372274,0.374046,0.373160,2.986189,3.066450,2.493822,2.465745

In [13]:
performance = bt.performance.copy()

In [28]:
performance[['Gross TS-Annualized Return', 'Net TS-Annualized Return','Gross Win Rate']].astype(float).round(2)

   Gross TS-Annualized Return  Net TS-Annualized Return  Gross Win Rate
0                        1.23                      1.21            0.60
1                        1.65                      1.65            0.59
2                       -0.58                     -0.59            0.38
3                        0.45                      0.44            0.50
0                       -2.04                     -2.04            0.20
1                       -1.38                     -1.38            0.28
2                       -0.82                     -0.82            0.32
3                       -1.08                     -1.08            0.29
0                       -0.13                     -0.13            0.54
1                       -0.19                     -0.19            0.45
2                       -0.33                     -0.33            0.41
3                       -0.24                     -0.24            0.46
0                       -0.90                     -0.88            0.49
1                       -0.17                     -0.17            0.45
2                       -0.88                     -0.88            0.42
3                       -0.59                     -0.58            0.47

In [25]:
performance[['Gross TS-Annualized Return', 'Net TS-Annualized Return','Gross Win Rate']] = performance[['Gross TS-Annualized Return', 'Net TS-Annualized Return','Gross Win Rate']].round(2)

In [43]:
performance

,year,fc_number,fc_name,fc_freq,IC,Rank IC,Gross Sharpe,Net Sharpe,Gross TS-Sharpe,Net TS-Sharpe,...,Net Annualized Volatility,Gross TS-Annualized Volatility,Net TS-Annualized Volatility,Long Daily Turnover,Short Daily Turnover,Longshort Daily Turnover,Max Gross Drawdown,Max Net Drawdown,TS-Max Gross Drawdown,TS-Max Net Drawdown
0,2016,1,mom,1d,0.055363,-0.029804,0.087061,0.033738,1.004125,0.986877,...,0.573730,1.226557,1.229032,0.444453,0.526849,0.485651,2.060007,2.073686,1.521946,1.551327
1,2017,1,mom,1d,0.045456,-0.002680,4.787482,4.696027,5.588011,5.583633,...,0.326140,0.295339,0.295340,0.450739,0.502403,0.476571,0.244499,0.247115,0.137477,0.137570
2,2018,1,mom,1d,-0.013505,-0.033302,-3.837559,-3.919271,-2.364897,-2.370673,...,0.376842,0.247150,0.247160,0.470806,0.494805,0.482806,1.352171,1.378713,0.670161,0.671172
3,all,1,mom,1d,0.020092,-0.028303,-0.520770,-0.600263,0.926174,0.913164,...,0.383388,0.485210,0.485834,0.452577,0.513681,0.483129,2.060007,2.073686,1.521946,1.551327
0,2016,2,upper_line,1d,-0.058345,-0.041864,-11.746597,-11.904314,-18.317692,-18.354378,...,0.146524,0.111137,0.111263,0.299257,0.437954,0.368606,1.661751,1.684078,1.974465,1.974448
1,2017,2,upper_line,1d,-0.034495,-0.045903,-8.970423,-9.094217,-10.294412,-10.303444,...,0.182268,0.133961,0.133964,0.287963,0.421814,0.354888,1.562871,1.585376,1.303903,1.305022
2,2018,2,upper_line,1d,-0.027330,-0.041302,-4.414540,-4.508283,-6.134324,-6.144993,...,0.234463,0.134212,0.134214,0.289351,0.411745,0.350548,0.998813,1.011374,0.847051,0.848046
3,all,2,upper_line,1d,-0.031556,-0.038841,-6.462428,-6.586940,-9.094423,-9.114245,...,0.180894,0.118362,0.118396,0.292458,0.423385,0.357922,4.516832,4.592303,4.305849,4.313751
0,2016,3,win_ratio,1d,0.008312,0.003618,-1.191860,-1.285320,-0.408504,-0.397270,...,0.454895,0.314582,0.315269,0.656558,0.692285,0.674422,1.302886,1.321559,0.860322,0.855149
1,2017,3,win_ratio,1d,-0.001559,-0.016563,-2.284378,-2.473624,-1.179328,-1.187243,...,0.212518,0.156887,0.156891,0.639694,0.632539,0.636117,0.645267,0.657491,0.463163,0.463542
2,2018,3,win_ratio,1d,-0.006815,-0.016824,-2.533424,-2.688149,-1.782947,-1.790731,...,0.254144,0.183884,0.183892,0.628377,0.615390,0.621883,0.872993,0.896052,0.566636,0.567398
3,all,3,win_ratio,1d,-0.002031,-0.013801,-2.029710,-2.177701,-1.238818,-1.238908,...,0.274014,0.195199,0.195374,0.637172,0.646741,0.641956,2.280061,2.415884,1.044107,1.043850
0,2016,4,location,1d,-0.013042,-0.005340,-2.685459,-2.755117,-3.191993,-3.119418,...,0.347509,0.281945,0.281760,0.392855,0.366010,0.379433,1.864173,1.874541,1.448924,1.422630
1,2017,4,location,1d,-0.002670,-0.006940,-0.815178,-0.896645,-0.828784,-0.834818,...,0.287473,0.204756,0.204759,0.362341,0.379750,0.371045,0.549348,0.554769,0.394812,0.395087
2,2018,4,location,1d,-0.022053,-0.020939,-3.227716,-3.301262,-3.839061,-3.845185,...,0.312688,0.230096,0.230105,0.361469,0.371483,0.366476,1.078690,1.094123,0.928305,0.929344
3,all,4,location,1d,-0.012043,-0.015100,-2.192952,-2.271601,-2.629838,-2.611473,...,0.300326,0.223456,0.223415,0.372274,0.374046,0.373160,2.986189,3.066450,2.493822,2.465745

In [30]:
data = bt.bbt[3].data.copy()

In [68]:
bt.bbt[3].ai.performance

,year,IC,Rank IC,Gross Sharpe,Net Sharpe,Gross TS-Sharpe,Net TS-Sharpe,Gross Annualized Return,Net Annualized Return,Gross TS-Annualized Return,...,Net Annualized Volatility,Gross TS-Annualized Volatility,Net TS-Annualized Volatility,Long Daily Turnover,Short Daily Turnover,Longshort Daily Turnover,Max Gross Drawdown,Max Net Drawdown,TS-Max Gross Drawdown,TS-Max Net Drawdown
0,2016,0.008312,0.003618,-1.191860,-1.285320,-0.408504,-0.397270,-0.542197,-0.584685,-0.128508,...,0.454895,0.314582,0.315269,0.656558,0.692285,0.674422,1.302886,1.321559,0.860322,0.855149
1,2017,-0.001559,-0.016563,-2.284378,-2.473624,-1.179328,-1.187243,-0.485614,-0.525689,-0.185022,...,0.212518,0.156887,0.156891,0.639694,0.632539,0.636117,0.645267,0.657491,0.463163,0.463542
2,2018,-0.006815,-0.016824,-2.533424,-2.688149,-1.782947,-1.790731,-0.643997,-0.683176,-0.327855,...,0.254144,0.183884,0.183892,0.628377,0.615390,0.621883,0.872993,0.896052,0.566636,0.567398
3,all,-0.002031,-0.013801,-2.029710,-2.177701,-1.238818,-1.238908,-0.556272,-0.596721,-0.241816,...,0.274014,0.195199,0.195374,0.637172,0.646741,0.641956,2.280061,2.415884,1.044107,1.043850

In [147]:
self = bt.bbt[3].ai
df_list = [self.ic, self.sharpe, self.annualized_return, self.win_rate, self.annualized_volatility,
                   self.daily_average_turnover, self.max_dd]

In [71]:
self.data.index.get_level_values('time').max().year

2019

In [65]:
bt.bbt[3].ai.daily_average_turnover

      Long Daily Turnover  Short Daily Turnover  Longshort Daily Turnover
year
2016             0.656558              0.692285                  0.674422
2017             0.639694              0.632539                  0.636117
2018             0.628377              0.615390                  0.621883
2019             0.622927              0.648528                  0.635728
all              0.637172              0.646741                  0.641956

In [88]:
ret_long = self.data.groupby('time').apply(
                lambda x: x.nlargest(row_count_at_percentage(x, self.quantile), columns='signal')['ret'].mean())

In [89]:
ret_long = ret_long.to_frame('ret').reset_index()

In [95]:
summary = self.data.groupby('time')[
    ['signal']].describe().mean().unstack()[['mean', 'std', 'count']]

In [96]:
summary

                mean  std        count
signal  7.254894e-17  1.0  2321.012834

In [ ]:
summary = data.groupby('time')[
    ['future_ret', f'FF3SPVOL_{window}', 
     f'TRVOV_{window}', 'REV_YTD_YOY', 'ROE_Q']].describe().mean().unstack()[['mean', 'std', 'count']]
summary[['mean', 'std']] = summary[['mean', 'std']].round(5)
summary['count'] = summary['count'].round().astype(int)
summary = summary.T
summary.index = ['Avg', 'Std', 'N']
summary.index.name = 'All stocks'
summary

In [150]:
self.data = self.data.drop(columns=['level_0', 'index', 'signal1'])

In [152]:
data = self.data.copy()

In [ ]:
def _get_instrument_count(self):
    self.data.groupby('time')[['signal']].count().mean()

In [173]:
count_year = data.groupby('year').apply(lambda x: x.groupby('time')[['signal']].count().mean()).astype(int)

In [176]:
count_year

      signal
year
2016    1944
2017    2249
2018    2469
2019    2649

In [ ]:
data

In [179]:
count_all = data.groupby('time')[['signal']].count().mean().astype(int).to_frame('signal')
count_all.index.name = 'all'
count_all

        signal
all
signal    2321

In [180]:
pd.concat([count_year, count_all])

        signal
2016      1944
2017      2249
2018      2469
2019      2649
signal    2321

In [165]:
data.groupby('time')['signal'].count().mean()

2321.012834224599

In [166]:
data['year'] = pd.to_datetime(data['time']).dt.year

In [2]:
from functools import reduce
from lwpackage.lwfactors.factor import *
from lwpackage.lwdata import get_stock_price, get_futures_continuous_contract_price

In [214]:
self = bt

In [3]:
data1 = get_stock_price(frequency='1d',
                        start_time='20160101', 
                        end_time='20200101', 
                        from_database=True)

In [4]:
data2 = data1.copy()

In [246]:
data1 = data1.set_index(['time', 'instrument_id'])

In [252]:
data1

                           open   high    low  close  volume
time       instrument_id
2016-01-04 600895         28.68  28.70  25.95  25.95  350024
           002318         15.37  15.45  13.77  13.77  278024
           600358         17.13  17.13  15.30  15.30  128171
           600363         20.43  20.85  18.48  18.51  148094
           601992          9.38   9.38   8.52   8.53  141857
...                         ...    ...    ...    ...     ...
2019-12-31 601001          4.33   4.42   4.30   4.40  185038
           600735          6.63   6.84   6.60   6.64   70067
           002636          8.71   8.77   8.50   8.57   49708
           603999          7.53   7.54   7.32   7.34  130181
           300293          8.12   8.16   7.95   8.01   98814

[2283779 rows x 5 columns]

In [255]:
bt.bbt[1].ai.ic

            IC   Rank IC
year
2016  0.055363 -0.029804
2017  0.045456 -0.002680
2018 -0.013505 -0.033302
2019 -0.010874 -0.050238
all   0.020092 -0.028303

In [259]:
bt.bbt[1].ai.sharpe

      Gross Sharpe  Net Sharpe  Gross TS-Sharpe  Net TS-Sharpe
year
2016      0.087061    0.033738         1.004125       0.986877
2017      4.787482    4.696027         5.588011       5.583633
2018     -3.837559   -3.919271        -2.364897      -2.370673
2019     -3.751660   -3.872099        -2.910095      -2.918731
all      -0.520770   -0.600263         0.926174       0.913164

In [262]:
bt.bbt[1].ai.icir

          icir  rank_icir
2016  0.489772  -0.243791
2017  0.443825  -0.023255
2018 -0.125262  -0.253511
2019 -0.155427  -0.572785
all   0.190950  -0.241673

In [270]:
data1 = data.copy()

In [271]:
data1[['a', 'b']] = data1.groupby('time')[['signal', 'ret']].transform(lambda x: x.quantile(1 / 5))

In [282]:
data1.groupby('time').corr('pearson')

                          instrument_id    signal       ret  year   a   b
time
2016-01-15 instrument_id       1.000000  0.032247 -0.013645   NaN NaN NaN
           signal              0.032247  1.000000 -0.033678   NaN NaN NaN
           ret                -0.013645 -0.033678  1.000000   NaN NaN NaN
           year                     NaN       NaN       NaN   NaN NaN NaN
           a                        NaN       NaN       NaN   NaN NaN NaN
...                                 ...       ...       ...   ...  ..  ..
2019-11-18 signal             -0.018332  1.000000 -0.019284   NaN NaN NaN
           ret                -0.012959 -0.019284  1.000000   NaN NaN NaN
           year                     NaN       NaN       NaN   NaN NaN NaN
           a                        NaN       NaN       NaN   NaN NaN NaN
           b                        NaN       NaN       NaN   NaN NaN NaN

[5610 rows x 6 columns]

In [300]:
data2

              time instrument_id   open   high    low  close  volume
1335036 2016-01-04        600895  28.68  28.70  25.95  25.95  350024
638250  2016-01-04        002318  15.37  15.45  13.77  13.77  278024
2012869 2016-01-04        600358  17.13  17.13  15.30  15.30  128171
1787534 2016-01-04        600363  20.43  20.85  18.48  18.51  148094
408157  2016-01-04        601992   9.38   9.38   8.52   8.53  141857
...            ...           ...    ...    ...    ...    ...     ...
1922417 2019-12-31        601001   4.33   4.42   4.30   4.40  185038
960383  2019-12-31        600735   6.63   6.84   6.60   6.64   70067
511501  2019-12-31        002636   8.71   8.77   8.50   8.57   49708
1246174 2019-12-31        603999   7.53   7.54   7.32   7.34  130181
2237541 2019-12-31        300293   8.12   8.16   7.95   8.01   98814

[2283779 rows x 7 columns]

In [5]:
data2['fac1'] = data2['close'].pct_change().diff()
data2['fac2'] = data2[['open']].diff().rolling(10).mean()
data2['ret'] = data2[['close']].pct_change()
fc_name_list = ['fac1', 'fac2']

In [362]:
num_ic = data2.groupby('time').corr('pearson').loc[(slice(None), ['fac1', 'fac2']), ['ret']].unstack(level=1)
num_ic.columns = num_ic.columns.droplevel(0)
rank_ic = data2.groupby('time').corr('spearman').loc[(slice(None), ['fac1', 'fac2']), ['ret']].unstack(level=1)
rank_ic.columns = rank_ic.columns.droplevel(0)

In [358]:
icir_cols = [x + ' NumICIR' for x in fc_name_list] + [x + ' RankICIR' for x in fc_name_list]
ic_cols = [x + ' NumIC' for x in fc_name_list] + [x + ' RankIC' for x in fc_name_list]
icir_cols

['fac1 NumICIR', 'fac2 NumICIR', 'fac1 RankICIR', 'fac2 RankICIR']

In [359]:
ic_all = pd.concat([num_ic, rank_ic], axis=1)
ic_all.columns = ic_cols
ic_year = ic_all.copy()
ic_year = ic_year.reset_index()
ic_year['year'] = pd.to_datetime(ic_year['time']).dt.year
ic_year = ic_year.groupby('year')[ic_cols].mean()
ic_year

      fac1 NumIC  fac2 NumIC  fac1 RankIC  fac2 RankIC
year
2016    0.782559    0.482995     0.847064     0.466748
2017    0.774217    0.508776     0.849294     0.468590
2018    0.761190    0.525915     0.850112     0.465335
2019    0.745613    0.533056     0.850316     0.464658

In [360]:
ic_all = ic_all.mean().to_frame('all').T
ic = pd.concat([ic_year, ic_all])
ic

      fac1 NumIC  fac2 NumIC  fac1 RankIC  fac2 RankIC
2016    0.782559    0.482995     0.847064     0.466748
2017    0.774217    0.508776     0.849294     0.468590
2018    0.761190    0.525915     0.850112     0.465335
2019    0.745613    0.533056     0.850316     0.464658
all     0.765900    0.512672     0.849196     0.466334

In [385]:
def get_ic_and_icir(Data: pd.DataFrame,
                    fc_name_list):
    for col in ['time', 'instrument_id', 'ret'] + fc_name_list:
        assert col in Data.columns, f'df does not contain columns {col}.'

    num_ic = Data.groupby('time').corr('pearson').loc[(slice(None), fc_name_list), ['ret']].unstack(level=1)
    num_ic.columns = num_ic.columns.droplevel(0)

    rank_ic = Data.groupby('time').corr('spearman').loc[(slice(None), fc_name_list), ['ret']].unstack(level=1)
    rank_ic.columns = rank_ic.columns.droplevel(0)

    ic_cols = [x + ' NumIC' for x in fc_name_list] + [x + ' RankIC' for x in fc_name_list]
    icir_cols = [x + ' NumICIR' for x in fc_name_list] + [x + ' RankICIR' for x in fc_name_list]

    ic_all = pd.concat([num_ic, rank_ic], axis=1)
    ic_all.columns = ic_cols
    ic_year = ic_all.copy()
    ic_year = ic_year.reset_index()
    ic_year['year'] = pd.to_datetime(ic_year['time']).dt.year
    ic_year = ic_year.groupby('year')[ic_cols].mean()

    ic_all = ic_all.mean().to_frame('all').T
    ic = pd.concat([ic_year, ic_all])

    icir = pd.concat([num_ic, rank_ic], axis=1)
    icir.columns = icir_cols

    icir_year = icir.copy()
    icir_year = icir_year.reset_index()
    icir_year['year'] = pd.to_datetime(icir_year['time']).dt.year
    icir_year = icir_year.groupby('year')[icir_cols].apply(lambda x: x.mean() / x.std())

    icir_all = (icir.mean() / icir.std()).to_frame('all').T
    icir = pd.concat([icir_year, icir_all])

    return ic, icir
get_ic_and_icir(data2, fc_name_list)

(      fac1 NumIC  fac2 NumIC  fac1 RankIC  fac2 RankIC
 2016    0.782559    0.482995     0.847064     0.466748
 2017    0.774217    0.508776     0.849294     0.468590
 2018    0.761190    0.525915     0.850112     0.465335
 2019    0.745613    0.533056     0.850316     0.464658
 all     0.765900    0.512672     0.849196     0.466334,
       fac1 NumICIR  fac2 NumICIR  fac1 RankICIR  fac2 RankICIR
 2016     74.190905     12.556224     113.844843      29.798043
 2017     57.083410     12.241051     129.957064      32.797365
 2018     49.322211      8.071319     117.527845      31.203116
 2019     50.900911      6.817680     134.332944      30.704477
 all      39.194629      8.369140     121.155749      30.964995)

In [386]:
ic, icir = get_ic_and_icir(data2, fc_name_list)

In [423]:
max_dd

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret
2016,1.0,1.0,1.0,1.0,1.0,0.142074,0.0,0.0,0.0,0.0,0.0,0.0
2017,1.0,1.0,1.0,1.0,1.0,0.072010,0.0,0.0,0.0,0.0,0.0,0.0
2018,1.0,1.0,1.0,1.0,1.0,0.102118,0.0,0.0,0.0,0.0,0.0,0.0
2019,1.0,1.0,1.0,1.0,1.0,0.286477,0.0,0.0,0.0,0.0,0.0,0.0
all,1.0,1.0,1.0,1.0,1.0,0.286477,0.0,0.0,0.0,0.0,0.0,0.0

In [437]:
data3 = data2.head(10000).set_index(['time', 'instrument_id'])
fee = 0.00025

In [478]:
cum_gross_ret = (1 + df_ret['ret']).cumprod()

/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/numpy/core/fromnumeric.py:57: RuntimeWarning: overflow encountered in accumulate
  return bound(*args, **kwds)

In [483]:
import matplotlib.pyplot as plt

In [481]:
cum_gross_ret.index

Index([2016-01-04, 2016-01-05, 2016-01-06, 2016-01-07, 2016-01-08, 2016-01-11,
       2016-01-12, 2016-01-13, 2016-01-14, 2016-01-15,
       ...
       2019-12-18, 2019-12-19, 2019-12-20, 2019-12-23, 2019-12-24, 2019-12-25,
       2019-12-26, 2019-12-27, 2019-12-30, 2019-12-31],
      dtype='object', name='time', length=975)

In [490]:
(1 + df_net_ret).cumprod()

/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/numpy/core/fromnumeric.py:57: RuntimeWarning: overflow encountered in accumulate
  return bound(*args, **kwds)

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret
time,,,,,,,,,,,,
2016-01-04,0.420037,5.274470e-01,5.987748e-01,7.377127e-01,8.460488e-01,1.001236e+00,1.400739e+00,1.871920e+00,2.721584,6.422670e+00,4.001316,4.001316
2016-01-05,0.167803,2.828402e-01,4.100486e-01,5.648764e-01,6.944489e-01,9.932636e-01,1.907500e+00,3.340380e+00,7.395718,3.864723e+01,15.237390,15.237390
2016-01-06,0.069390,1.553848e-01,2.317559e-01,4.067535e-01,5.997320e-01,1.023760e+00,2.634549e+00,6.125619e+00,19.848505,2.588941e+02,63.111078,63.111078
2016-01-07,0.027962,8.108327e-02,1.553426e-01,3.152233e-01,5.134384e-01,1.045696e+00,3.542087e+00,1.104581e+01,50.068065,1.688844e+03,256.188966,256.188966
2016-01-08,0.011125,4.164960e-02,1.017865e-01,2.159471e-01,4.271657e-01,1.088756e+00,4.826009e+00,1.998783e+01,136.932881,1.038943e+04,993.027697,993.027697
...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-25,0.000000,5.505772e-255,3.068418e-192,7.922258e-141,9.979784e-84,4.767168e+06,1.222578e+128,2.316151e+269,inf,inf,inf,inf
2019-12-26,0.000000,2.805942e-255,1.941400e-192,5.637316e-141,8.158974e-84,4.813419e+06,1.702510e+128,4.717540e+269,inf,inf,inf,inf
2019-12-27,0.000000,1.437391e-255,1.208383e-192,3.647170e-141,6.696183e-84,4.654585e+06,2.432414e+128,1.045378e+270,inf,inf,inf,inf
2019-12-30,0.000000,7.741384e-256,7.477026e-193,2.505163e-141,5.383369e-84,4.605656e+06,3.357795e+128,2.173103e+270,inf,inf,inf,inf
2019-12-31,0.000000,4.286818e-256,4.698200e-193,1.694759e-141,4.377282e-84,4.422253e+06,4.863375e+128,4.763606e+270,inf,inf,inf,inf

In [557]:
# gross_ret_ts = (data3['fac1'] * data3['ret']).groupby('time').mean()
df_gross_ret_ts = pd.DataFrame(data3[['fac1', 'fac2']].values * data3[['ret']].values, 
                            index=data3.index, 
                            columns=['fac1', 'fac2'])
df_gross_ret_ts = df_gross_ret_ts.groupby('time').mean()
df_turnover_ts = data3.unstack(level=1).diff().abs().fillna(0).mean(axis=1)
df_net_ret_ts = pd.DataFrame(df_gross_ret_ts.values - (df_turnover_ts * fee).to_frame().values,
                         index=df_gross_ret_ts.index, 
                         columns=df_gross_ret_ts.columns)

# gross_ret_ts = gross_ret_ts.to_frame('gross_ret_ts')
# turnover_ts = turnover_ts.to_frame('turnover_ts')
# net_ret_ts = net_ret_ts.to_frame('net_ret_ts')
# ts_ret_and_turnover = pd.concat([gross_ret_ts, net_ret_ts, turnover_ts], axis=1)

In [596]:
data = get_futures_continuous_contract_price(start_date='20200101',
                                            end_date='20221231',
                                            from_database=True)

In [599]:
data

,time,instrument_id,open,high,low,close,volume,position
0,2020-01-02,V0,6520.0,6530.0,6485.0,6500.0,54491,230632
1,2020-01-03,V0,6500.0,6510.0,6480.0,6495.0,72391,229655
2,2020-01-06,V0,6495.0,6590.0,6480.0,6545.0,174761,237376
3,2020-01-07,V0,6540.0,6545.0,6495.0,6510.0,86013,230968
4,2020-01-08,V0,6515.0,6570.0,6510.0,6565.0,115493,235940
...,...,...,...,...,...,...,...,...
45217,2022-12-26,SI0,16940.0,17435.0,16825.0,17170.0,23991,7922
45218,2022-12-27,SI0,17200.0,17410.0,17130.0,17165.0,13350,8685
45219,2022-12-28,SI0,17100.0,17575.0,16960.0,17425.0,21736,8197
45220,2022-12-29,SI0,17390.0,17665.0,17325.0,17515.0,12999,7813
45221,2022-12-30,SI0,17535.0,18520.0,17535.0,17895.0,37967,7708

In [629]:
data3 = data2.head(500000).reset_index()

In [665]:
data3 = data3.sort_values(by='instrument_id')
data3['year'] = pd.to_datetime(data3['time']).dt.year
fc_col = 'fac1'
ret_freq = 30

ic_ts_year = data3.groupby('year')[fc_col].corr(data3['ret'], method='pearson')
ic_ts_all = pd.Series(data3['fac1'].corr(data3['ret'], method='pearson'), index=['all'])
ic_ts = pd.concat([ic_ts_year, ic_ts_all]).to_frame('TS IC')

rank_ic_ts_year = data3.groupby('year')[fc_col].corr(data3['ret'], method='spearman')
rank_ic_ts_all = pd.Series(data3['fac1'].corr(data3['ret'], method='spearman'), index=['all'])
rank_ic_ts = pd.concat([rank_ic_ts_year, rank_ic_ts_all]).to_frame('TS RankIC')

ic_ts = pd.concat([ic_ts, rank_ic_ts], axis=1)

t_corr_year = data3.groupby('year')['ret'].apply(lambda x: np.sqrt(x.size / ret_freq))
t_corr_all = pd.Series(len(df) / ret_freq, index=['all'])
t_corr = pd.concat([t_corr_year, t_corr_all]).to_frame('T-corr')

In [667]:
t_corr

          T-corr
2016  126.201558
2017   27.199877
all    32.500000

In [666]:
ic_ts = pd.concat([ic_ts, rank_ic_ts], axis=1)
ic_ts

         TS IC  TS RankIC
2016  0.717562   0.847305
2017  0.782945   0.851860
all   0.717961   0.847511

In [649]:
data3.loc[data3['year'] == 2017]

,index,time,instrument_id,open,high,low,close,volume,fac1,fac2,ret,year
483380,1138992,2017-01-05,000001,9.17,9.18,9.15,9.17,344373,-1.297916,-3.523,-0.596568,2017
481875,1138991,2017-01-04,000001,9.15,9.18,9.14,9.16,449330,-0.152587,-2.510,-0.611370,2017
486429,1138994,2017-01-09,000001,9.13,9.17,9.11,9.15,361082,-2.985856,-0.887,-0.645624,2017
494169,1138997,2017-01-12,000001,9.13,9.17,9.13,9.15,428007,-0.815931,-3.169,-0.641598,2017
488754,1138995,2017-01-10,000001,9.15,9.16,9.14,9.15,241054,0.610890,-0.474,-0.026596,2017
...,...,...,...,...,...,...,...,...,...,...,...,...
494232,1647172,2017-01-12,839719,6.80,10.00,6.80,10.00,340,0.380853,-0.720,-0.269006,2017
491984,1647171,2017-01-11,839719,6.80,6.80,6.80,6.80,300,0.002463,-0.745,-0.474498,2017
495514,1647173,2017-01-13,839719,1.00,7.60,1.00,1.00,9110,-2.619508,-0.717,-0.940653,2017
499721,1647175,2017-01-17,839719,6.80,8.90,6.80,8.90,600,-0.698536,0.194,-0.548682,2017
488400,1647170,2017-01-10,839719,10.00,10.00,10.00,10.00,10,1.181818,-2.586,0.333333,2017

In [650]:
np.sqrt(22195 / 30)

27.19987745070432

In [648]:
t_corr_year = data3.groupby('year')['ret'].apply(lambda x: np.sqrt(x.size / ret_freq))

year
2016    126.201558
2017     27.199877
Name: ret, dtype: float64

In [612]:
ic = data3['fac1'].corr(data3['ret'], method='pearson')

0.7790686422389097

In [613]:
data3

,index,time,instrument_id,open,high,low,close,volume,fac1,fac2,ret
3310,1138747,2016-01-05,000001,11.27,11.57,11.15,11.40,663270,-5.048693,0.062,-0.917319
6910,1138749,2016-01-07,000001,11.41,11.41,10.91,10.94,174761,-0.072068,-0.315,-0.374857
7707,1138750,2016-01-08,000001,11.21,11.29,10.90,11.12,747528,0.152192,-0.024,-0.319878
5233,1138748,2016-01-06,000001,11.42,11.56,11.39,11.53,515706,0.572119,0.344,0.149551
683,1138746,2016-01-04,000001,12.00,12.03,11.23,11.33,563498,-0.675294,0.316,-0.631904
...,...,...,...,...,...,...,...,...,...,...,...
7684,591646,2016-01-08,833914,6.76,7.00,6.75,6.77,11510,-0.097322,-0.752,-0.464822
3179,591645,2016-01-05,833914,7.20,7.20,7.20,7.20,20,-0.699718,-0.114,-0.782543
370,591644,2016-01-04,833914,7.20,7.20,7.20,7.20,300,0.208363,-2.018,-0.465875
3987,258419,2016-01-06,834062,2.10,2.10,2.10,2.10,300,-0.889037,-1.040,-0.879794
7630,258420,2016-01-07,834062,2.10,2.10,2.10,2.10,1200,-2.471520,-2.310,-0.933121

In [583]:
data4 = data3.reset_index()
data4['year'] = pd.to_datetime(data4['time']).dt.year

count_all = int(data4.groupby('year').size().mean().round())
pd.Series(count_all, index=['all']).to_frame('count').T

         all
count  10000

In [565]:
data3.groupby('year').size()

KeyError: 'year'

In [560]:
data3.groupby('time').size()

time
2016-01-04    1912
2016-01-05    1915
2016-01-06    1918
2016-01-07    1912
2016-01-08    1918
2016-01-11     425
dtype: int64

In [558]:
df_gross_ret_ts

                fac1      fac2
time
2016-01-04  6.398909  3.334447
2016-01-05  4.794766  2.526908
2016-01-06  6.825663  3.294571
2016-01-07  7.549034  3.478146
2016-01-08  5.162780  2.718761
2016-01-11  6.827440  4.160085

In [556]:
pd.DataFrame(data3[['fac1', 'fac2']].values * data3[['ret']].values, 
                            index=data3.index, 
                            columns=['fac1', 'fac2'])

                               fac1       fac2
time       instrument_id
2016-01-04 600895               NaN        NaN
           002318               NaN        NaN
           600358          0.064497        NaN
           600363          0.020706        NaN
           601992          0.403822        NaN
...                             ...        ...
2016-01-11 300050          8.019198 -16.833656
           600882          2.193019   0.155150
           600259         12.805288   0.227122
           002249          2.707564   0.044059
           600848          0.498895   0.247694

[10000 rows x 2 columns]

In [552]:
net_ret_ts

                fac1      fac2
time
2016-01-04  6.398909  3.334447
2016-01-05  2.692038  0.424181
2016-01-06  4.797882  1.266790
2016-01-07  3.300796 -0.770092
2016-01-08  0.055791 -2.388228
2016-01-11  6.470363  3.803009

In [542]:
data3.unstack(level=1).diff().abs().fillna(0).mean(axis=1, keep=True)

TypeError: mean() got an unexpected keyword argument 'keep'

In [553]:
(turnover_ts * fee).to_frame().values

array([[0.        ],
       [2.10272721],
       [2.02778101],
       [4.24823814],
       [5.10698978],
       [0.35707647]])

In [545]:
gross_ret_ts

                fac1      fac2
time
2016-01-04  6.398909  3.334447
2016-01-05  4.794766  2.526908
2016-01-06  6.825663  3.294571
2016-01-07  7.549034  3.478146
2016-01-08  5.162780  2.718761
2016-01-11  6.827440  4.160085

In [554]:
gross_ret_ts.values - (turnover_ts * fee).to_frame().values

array([[ 6.39890903,  3.33444725],
       [ 2.69203831,  0.42418124],
       [ 4.79788243,  1.26678964],
       [ 3.30079598, -0.77009198],
       [ 0.05579057, -2.38822832],
       [ 6.47036317,  3.80300866]])

In [530]:
data3.unstack(level=1).diff().abs().fillna(0).mean(axis=1)

time
2016-01-04        0.000000
2016-01-05     8410.908835
2016-01-06     8111.124021
2016-01-07    16992.952576
2016-01-08    20427.959116
2016-01-11     1428.305877
dtype: float64

In [518]:
gross_ret_ts

                fac1      fac2
time
2016-01-04  6.398909  3.334447
2016-01-05  4.794766  2.526908
2016-01-06  6.825663  3.294571
2016-01-07  7.549034  3.478146
2016-01-08  5.162780  2.718761
2016-01-11  6.827440  4.160085

In [508]:
data3[['fac1', 'fac2']].multiply(data3[['ret']].rename(columns={'ret': 'fac2'}))

                          fac1       fac2
time       instrument_id
2016-01-04 600895          NaN        NaN
           002318          NaN        NaN
           600358          NaN        NaN
           600363          NaN        NaN
           601992          NaN        NaN
...                        ...        ...
2016-01-11 300050          NaN -16.833656
           600882          NaN   0.155150
           600259          NaN   0.227122
           002249          NaN   0.044059
           600848          NaN   0.247694

[10000 rows x 2 columns]

In [516]:
data3

                           open   high    low  close  volume      fac1   fac2  \
time       instrument_id
2016-01-04 600895         28.68  28.70  25.95  25.95  350024       NaN    NaN
           002318         15.37  15.45  13.77  13.77  278024       NaN    NaN
           600358         17.13  17.13  15.30  15.30  128171  0.580475    NaN
           600363         20.43  20.85  18.48  18.51  148094  0.098693    NaN
           601992          9.38   9.38   8.52   8.53  141857 -0.748972    NaN
...                         ...    ...    ...    ...     ...       ...    ...
2016-01-11 300050         29.50  30.00  27.53  27.99   69450  3.311309 -6.951
           600882          9.09   9.21   8.34   8.34   78355 -3.123797 -0.221
           600259         34.00  36.61  33.06  35.40  103754  3.946641  0.070
           002249         11.56  11.99  11.03  11.03  338302 -3.933022 -0.064
           600848         16.59  17.24  15.90  15.90   58036  1.129941  0.561

                               ret
time       instrument_id
2016-01-04 600895              NaN
           002318        -0.469364
           600358         0.111111
           600363         0.209804
           601992        -0.539168
...                            ...
2016-01-11 300050         2.421760
           600882        -0.702036
           600259         3.244604
           002249        -0.688418
           600848         0.441523

[10000 rows x 8 columns]

In [513]:
pd.DataFrame(data3[['fac1', 'fac2']].values * data3[['ret']].values, index=data3.index, columns=['fac1', 'fac2'])

                               fac1       fac2
time       instrument_id
2016-01-04 600895               NaN        NaN
           002318               NaN        NaN
           600358          0.064497        NaN
           600363          0.020706        NaN
           601992          0.403822        NaN
...                             ...        ...
2016-01-11 300050          8.019198 -16.833656
           600882          2.193019   0.155150
           600259         12.805288   0.227122
           002249          2.707564   0.044059
           600848          0.498895   0.247694

[10000 rows x 2 columns]

In [506]:
data3[['ret']]

                               ret
time       instrument_id
2016-01-04 600895              NaN
           002318        -0.469364
           600358         0.111111
           600363         0.209804
           601992        -0.539168
...                            ...
2016-01-11 300050         2.421760
           600882        -0.702036
           600259         3.244604
           002249        -0.688418
           600848         0.441523

[10000 rows x 1 columns]

In [505]:
data3[['fac1', 'fac2']]

                              fac1   fac2
time       instrument_id
2016-01-04 600895              NaN    NaN
           002318              NaN    NaN
           600358         0.580475    NaN
           600363         0.098693    NaN
           601992        -0.748972    NaN
...                            ...    ...
2016-01-11 300050         3.311309 -6.951
           600882        -3.123797 -0.221
           600259         3.946641  0.070
           002249        -3.933022 -0.064
           600848         1.129941  0.561

[10000 rows x 2 columns]

In [491]:
ts_ret_and_turnover

            gross_ret_ts  net_ret_ts  turnover_ts
time
2016-01-04      6.398909         NaN          NaN
2016-01-05      4.794766    4.794474     1.164687
2016-01-06      6.825663    6.825381     1.128135
2016-01-07      7.549034    7.548749     1.140033
2016-01-08      5.162780    5.162499     1.123568
2016-01-11      6.827440    6.827119     1.283933

In [458]:
net_ret_ts

time
2016-01-04         NaN
2016-01-05    4.794474
2016-01-06    6.825381
2016-01-07    7.548749
2016-01-08    5.162499
2016-01-11    6.827119
dtype: float64

In [454]:
gross_ret_ts

time
2016-01-04    6.398909
2016-01-05    4.794766
2016-01-06    6.825663
2016-01-07    7.549034
2016-01-08    5.162780
2016-01-11    6.827440
dtype: float64

In [446]:
data3.groupby('instrument_id')['ret'].diff().abs().groupby('time').mean()

time
2016-01-04         NaN
2016-01-05    1.164687
2016-01-06    1.128135
2016-01-07    1.140033
2016-01-08    1.123568
2016-01-11    1.283933
Name: ret, dtype: float64

In [426]:
ic.index.name = 'year'

In [428]:
pd.concat([ic, icir])

,fac1 NumIC,fac2 NumIC,fac1 RankIC,fac2 RankIC,fac1 NumICIR,fac2 NumICIR,fac1 RankICIR,fac2 RankICIR
year,,,,,,,,
2016,0.782559,0.482995,0.847064,0.466748,NaN,NaN,NaN,NaN
2017,0.774217,0.508776,0.849294,0.468590,NaN,NaN,NaN,NaN
2018,0.761190,0.525915,0.850112,0.465335,NaN,NaN,NaN,NaN
2019,0.745613,0.533056,0.850316,0.464658,NaN,NaN,NaN,NaN
all,0.765900,0.512672,0.849196,0.466334,NaN,NaN,NaN,NaN
2016,NaN,NaN,NaN,NaN,74.190905,12.556224,113.844843,29.798043
2017,NaN,NaN,NaN,NaN,57.083410,12.241051,129.957064,32.797365
2018,NaN,NaN,NaN,NaN,49.322211,8.071319,117.527845,31.203116
2019,NaN,NaN,NaN,NaN,50.900911,6.817680,134.332944,30.704477
all,NaN,NaN,NaN,NaN,39.194629,8.369140,121.155749,30.964995

In [389]:
def get_annualized_instrument_count(df_n: pd.DataFrame):
    """

    :param df_n: the func return df_n of get_grouped_ret_and_turnover(need to reset_index)
    :return:
    """
    assert 'time' in df_n.columns
    df = df_n.copy()

    df['year'] = pd.to_datetime(df['time']).dt.year
    n_cols = list(set(df.columns.to_list()) - {'time', 'year'})
    n_cols = sorted(n_cols, key=lambda x: int(x.split(' ')[1]))

    count_year = df.groupby('year')[n_cols].mean().round().astype(int)
    count_all = df[n_cols].mean().round().astype(int).to_frame('all').T

    instrument_count = pd.concat([count_year, count_all])

    return instrument_count

In [398]:
te = get_annualized_instrument_count(df_n.reset_index())
te.mean(axis=1).round(0).astype(int).to_frame('Average Instruement Count')

      Average Instruement Count
2016                        196
2017                        226
2018                        247
2019                        267
all                         234

In [410]:
icir.index.name = 'year'
icir

      fac1 NumICIR  fac2 NumICIR  fac1 RankICIR  fac2 RankICIR
year
2016     74.190905     12.556224     113.844843      29.798043
2017     57.083410     12.241051     129.957064      32.797365
2018     49.322211      8.071319     117.527845      31.203116
2019     50.900911      6.817680     134.332944      30.704477
all      39.194629      8.369140     121.155749      30.964995

In [417]:
(df_turnover.mean()).to_frame('all').T

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1
all,1.78023,1.778977,1.766356,1.758147,1.756499,1.769158,1.775405,1.749744,1.679611,1.285498,3.065728

In [404]:
volatility.index.name = 'year'
volatility

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret
year,,,,,,,,,,,,
2016,0.378513,0.466999,0.459170,0.473210,0.514436,0.245342,NaN,NaN,NaN,NaN,NaN,NaN
2017,0.356482,0.409103,0.425411,0.446666,0.478228,0.246311,NaN,NaN,NaN,NaN,NaN,NaN
2018,0.404372,0.467463,0.420599,0.491044,0.491120,0.315751,NaN,NaN,NaN,NaN,NaN,NaN
2019,0.452641,0.463115,0.418318,0.470377,0.525641,0.260639,NaN,NaN,NaN,NaN,NaN,NaN
all,0.452991,0.465487,0.438135,0.485002,0.520337,0.270070,NaN,NaN,NaN,NaN,NaN,NaN

In [381]:
data2

,time,instrument_id,open,high,low,close,volume,fac1,fac2,ret
1335036,2016-01-04,600895,28.68,28.70,25.95,25.95,350024,NaN,NaN,NaN
638250,2016-01-04,002318,15.37,15.45,13.77,13.77,278024,NaN,NaN,-0.469364
2012869,2016-01-04,600358,17.13,17.13,15.30,15.30,128171,0.580475,NaN,0.111111
1787534,2016-01-04,600363,20.43,20.85,18.48,18.51,148094,0.098693,NaN,0.209804
408157,2016-01-04,601992,9.38,9.38,8.52,8.53,141857,-0.748972,NaN,-0.539168
...,...,...,...,...,...,...,...,...,...,...
1922417,2019-12-31,601001,4.33,4.42,4.30,4.40,185038,-1.000000,-0.331,-0.428571
960383,2019-12-31,600735,6.63,6.84,6.60,6.64,70067,0.937662,0.193,0.509091
511501,2019-12-31,002636,8.71,8.77,8.50,8.57,49708,-0.218428,-4.272,0.290663
1246174,2019-12-31,603999,7.53,7.54,7.32,7.34,130181,-0.434187,-1.426,-0.143524
2237541,2019-12-31,300293,8.12,8.16,7.95,8.01,98814,0.234805,0.438,0.091281

In [366]:
icir = pd.concat([num_ic, rank_ic], axis=1)
icir.columns = icir_cols
icir_year = icir.copy()
icir_year.reset_index(inplace=True)
icir_year['year'] = pd.to_datetime(icir_year['time']).dt.year
icir_year = icir_year.groupby('year')[icir_cols].apply(lambda x: x.mean() / x.std())

icir_all = (icir.mean() / icir.std()).to_frame('all').T
icir = pd.concat([icir_year, icir_all])
icir

      fac1 NumICIR  fac2 NumICIR  fac1 RankICIR  fac2 RankICIR
2016     74.190905     12.556224     113.844843      29.798043
2017     57.083410     12.241051     129.957064      32.797365
2018     49.322211      8.071319     117.527845      31.203116
2019     50.900911      6.817680     134.332944      30.704477
all      39.194629      8.369140     121.155749      30.964995

In [133]:
df = data2.copy()
portfolio_number = 10
method = 'longshort'
fc_name = fc_name_list[0]
df = df.set_index(['time', 'instrument_id'])
df['quantile_0'] = float('-inf')
for i in range(1, portfolio_number):
    df[f'quantile_{i}'] = df.groupby('time')[fc_name].transform(lambda x: x.quantile(i / portfolio_number))
df[f'quantile_{portfolio_number}'] = float('inf')
fc_freq = '1m'

In [ ]:
del df_ret, df_n, df_turnover

In [134]:
df_ret, df_n, df_turnover = pd.DataFrame(), pd.DataFrame(), pd.DataFrame()

for i in range(portfolio_number):
    df_ret[f'{fc_name} {i+1}'] = df.groupby('time').apply(
        lambda x: (((x[fc_name] > x[f'quantile_{i}']) &
                    (x[fc_name] < x[f'quantile_{i + 1}'])) * x['ret']).sum() / (
                            (x[fc_name] > x[f'quantile_{i}']) & 
                            (x[fc_name] < x[f'quantile_{i + 1}'])).sum(), include_groups=False)

    df_n[f'{fc_name} {i+1}'] = df.groupby('time').apply(
        lambda x: ((x[fc_name] > x[f'quantile_{i}']) & 
                   (x[fc_name] < x[f'quantile_{i + 1}'])).sum(), include_groups=False)
    
    turnover_arr = df.groupby('time', as_index=False).apply(lambda x: (x[fc_name] > x[f'quantile_{i}']) &
                                         (x[fc_name] < x[f'quantile_{i + 1}']), include_groups=False).droplevel(0)
    turnover_arr = (turnover_arr.unstack() * 1).astype(float).fillna(0)
    turnover_arr = turnover_arr.apply(lambda x: x / df_n[f'{fc_name} {i+1}'])
    turnover_arr = turnover_arr.diff().abs().sum(axis=1)
    
    df_turnover[f'{fc_name} {i+1}'] = turnover_arr
    
    
    print(i)
df_ret[f'{fc_name} {portfolio_number}-1'] = (df_ret[f'{fc_name} {portfolio_number}'] - df_ret[f'{fc_name} {1}']) / 2
df_turnover[f'{fc_name} {portfolio_number}-1'] = (df_turnover[f'{fc_name} {portfolio_number}'] + df_turnover[f'{fc_name} {1}'])

if fc_freq != '1d':
    df_ret = df_ret.reset_index()
    df_ret['time'] = pd.to_datetime(df_ret['time']).dt.date
    df_ret = df_ret.groupby('time').sum()
    
    df_turnover = df_turnover.reset_index()
    df_turnover['time'] = pd.to_datetime(df_turnover['time']).dt.date
    df_turnover = df_turnover.groupby('time').sum()
    
    df_n = df_n.reset_index()
    df_n['time'] = pd.to_datetime(df_n['time']).dt.date
    df_n = df_n.groupby('time').mean()
    

df_net_ret = df_ret - df_turnover * cost

if method == 'longshort':
    df_ret['ret'] = df_ret[f'{fc_name} {portfolio_number}-1']
    df_net_ret['ret'] = df_net_ret[f'{fc_name} {portfolio_number}-1']
elif method == 'long_only':
    df_ret['ret'] = df_ret[f'{fc_name} {portfolio_number}']
    df_net_ret['ret'] = df_net_ret[f'{fc_name} {portfolio_number}']
else:
    raise NotImplementedError(f'Do not support method {method}.')

0
1
2
3
4
5
6
7
8
9

In [243]:
def get_annualized_ret(Data: pd.DataFrame,
                          ret_col,
                          method: str = 'simple'):
    """
    Get annualized return for every year in data and total annualized return.

    :param Data:
    :param ret_col:
    :param method:
    :return:
    """
    for col in ['time'] + ret_col:
        assert col in Data.columns, f'Data does not contain column {col}.'
    df = Data.copy()
    df = df.sort_values(by='time')
    df = df.dropna()
    df['year'] = pd.to_datetime(df['time']).dt.year
    if method == 'simple':
        ret_year = df.groupby('year')[ret_col].mean() * 252
        ret_all = (df[ret_col].mean() * 252).to_frame('all').T
    elif method == 'compound':
        df = df.set_index('time')
        df_cumret = (1 + df[ret_col]).cumprod().reset_index()
        df_cumret['year'] = pd.to_datetime(df_cumret['time']).dt.year
        
        ret_year = df_cumret.groupby('year')[ret_col].apply(
            lambda x: (x.iloc[-1] / x.iloc[0]) ** (252 / len(x)) - 1)
        ret_all = (df_cumret[ret_col].iloc[-1] ** (252 / len(df_cumret[ret_col])) - 1).to_frame('all').T
    else:
        raise NotImplementedError(f'Does not support method {method}.')

    ret = pd.concat([ret_year, ret_all])

    return ret

In [208]:
def get_annualized_volatility(Data, ret_col):
    """

    :param Data:
    :param ret_col:
    :return:
    """
    for col in ['time'] + ret_col:
        assert col in Data.columns, f'Data does not contain column {col}.'
    df = Data.copy()
    df = df.dropna()
    df = df.sort_values(by='time', ascending=True)
    df['year'] = pd.to_datetime(df['time']).dt.year
    volatility_year = df.groupby('year')[ret_col].std() * np.sqrt(252)
    volatility_all = (df[ret_col].std() * np.sqrt(252)).to_frame('all').T
    volatility = pd.concat([volatility_year, volatility_all])

    return volatility

In [234]:
ret = get_annualized_return(df_ret.reset_index(), df_ret.columns.to_list()[:1], 'simple')
volatility = get_annualized_volatility(df_ret.reset_index(), df_ret.columns.to_list()[:1])

In [236]:
ret

          fac1 1
2016 -146.325729
2017 -146.929406
2018 -152.162022
2019 -154.326133
all  -149.933539

In [235]:
volatility

        fac1 1
2016  0.378513
2017  0.356482
2018  0.404372
2019  0.452641
all   0.452991

In [218]:
def get_sharpe(ret, volatility):
    """
    Calculate annualized sharpe, does not consider risk free rate.
    :param ret:
    :param volatility:
    :return:
    """
    vola = volatility.copy()
    assert ret.shape == vola.shape
    assert all(ret.index == vola.index)
    assert all(ret.columns == vola.columns)
    sharpe = ret / vola

    return sharpe

In [257]:
def get_sortino_ratio(Data, ret_col, method: str='simple'):
    # 采用下行波动率计算
    df = Data.copy()
    df = df.dropna()
    df = df.sort_values(by='time', ascending=True)
    
    volatility_list = []
    ret = get_annualized_ret(df, ret_col, method)
    for col in ret_col:
        df_down = df.loc[df[col] < 0]
        volatility = get_annualized_volatility(df_down, [col])
        volatility_list.append(volatility)
    
    volatility = pd.concat(volatility_list, axis=1)
    sortino_ratio = ret / volatility

    return sortino_ratio

In [242]:
def get_annualized_volatility(Data, ret_col):
    """

    :param Data:
    :param ret_col:
    :return:
    """
    for col in ['time'] + ret_col:
        assert col in Data.columns, f'Data does not contain column {col}.'
    df = Data.copy()
    df = df.dropna()
    df = df.sort_values(by='time', ascending=True)
    df['year'] = pd.to_datetime(df['time']).dt.year
    volatility_year = df.groupby('year')[ret_col].std() * np.sqrt(252)
    volatility_all = (df[ret_col].std() * np.sqrt(252)).to_frame('all').T
    volatility = pd.concat([volatility_year, volatility_all])

    return volatility

In [276]:
def get_drawdown(Data, ret_col):
    """
    Get drawdown by simple rate.
    """
    # maximum_drawdown = max((nav - max(nav)) / max(nav))
    # if lost all money, just stop. This algorithm does not consider adding extra capital.
    # So the maximum drawdown is 1.
    df = Data.copy()
    df = df.dropna()
    df = df.sort_values(by='time', ascending=True)
    
    nav = (1 + df[ret_col]).cumprod()
    dd = 1 - nav / nav.cummax()

    df['year'] = pd.to_datetime(df['time']).dt.year
    max_dd_year = df.groupby('year')[ret_col].apply(_get_max_dd)
    max_dd_all = (dd.max()).to_frame('all').T
    max_dd = pd.concat([max_dd_year, max_dd_all])
    
    return dd, max_dd

def _get_max_dd(ret):
    ret_nav = (1 + ret).cumprod()
    dd = 1 - ret_nav / ret_nav.cummax()
    return dd.max()

In [280]:
dd, max_dd = get_drawdown(df_ret.reset_index(), ret_col)

/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/numpy/core/fromnumeric.py:57: RuntimeWarning: overflow encountered in accumulate
  return bound(*args, **kwds)

In [320]:
max_dd

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret
2016,1.0,1.0,1.0,1.0,1.0,0.142074,0.0,0.0,0.0,0.0,0.0,0.0
2017,1.0,1.0,1.0,1.0,1.0,0.072010,0.0,0.0,0.0,0.0,0.0,0.0
2018,1.0,1.0,1.0,1.0,1.0,0.102118,0.0,0.0,0.0,0.0,0.0,0.0
2019,1.0,1.0,1.0,1.0,1.0,0.286477,0.0,0.0,0.0,0.0,0.0,0.0
all,1.0,1.0,1.0,1.0,1.0,0.286477,0.0,0.0,0.0,0.0,0.0,0.0

In [302]:
def get_win_rate(Data, ret_col):
    """
    Get win rate, which is the ratio of profitable trades.
    """
    df = Data.copy()
    df = df.dropna()
    df = df.sort_values(by='time', ascending=True)
    
    df['year'] = pd.to_datetime(df['time']).dt.year
    
    win_rate_list = []
    for col in ret_col:
        win_rate_list.append(df.groupby('year')[col].apply(lambda x: len(x[x > 0]) / len(x)))
    win_rate_year = pd.concat(win_rate_list, axis=1)
    win_rate_all = (df[ret_col].apply(lambda x: len(x[x > 0]) / len(x))).to_frame('all').T
    win_rate = pd.concat([win_rate_year, win_rate_all])
    
    return win_rate

In [303]:
get_win_rate(df_ret.reset_index(), ret_col)

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret
2016,0.0,0.0,0.0,0.0,0.0,0.688525,1.0,1.0,1.0,1.0,1.0,1.0
2017,0.0,0.0,0.0,0.0,0.0,0.721311,1.0,1.0,1.0,1.0,1.0,1.0
2018,0.0,0.0,0.0,0.0,0.0,0.679012,1.0,1.0,1.0,1.0,1.0,1.0
2019,0.0,0.0,0.0,0.0,0.0,0.614754,1.0,1.0,1.0,1.0,1.0,1.0
all,0.0,0.0,0.0,0.0,0.0,0.675897,1.0,1.0,1.0,1.0,1.0,1.0

In [322]:
df = df_n.reset_index()

In [343]:
n_cols = list(set(df.columns.to_list()) - {'time', 'year'})
n_cols = sorted(n_cols, key=lambda x: int(x.split(' ')[1]))
n_cols

['fac1 1',
 'fac1 2',
 'fac1 3',
 'fac1 4',
 'fac1 5',
 'fac1 6',
 'fac1 7',
 'fac1 8',
 'fac1 9',
 'fac1 10']

In [339]:
sorted(n_cols, key=lambda x: int(x.split(' ')[1]))

['fac1 1',
 'fac1 2',
 'fac1 3',
 'fac1 4',
 'fac1 5',
 'fac1 6',
 'fac1 7',
 'fac1 8',
 'fac1 9',
 'fac1 10']

In [379]:
df_n

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10
time,,,,,,,,,,
2016-01-04,191,191,191,191,191,191,191,191,191,191
2016-01-05,192,191,192,191,191,191,191,192,191,192
2016-01-06,192,192,192,191,192,192,191,192,192,192
2016-01-07,192,191,191,191,191,191,191,191,191,192
2016-01-08,192,192,192,191,192,192,191,192,192,192
...,...,...,...,...,...,...,...,...,...,...
2019-12-25,276,275,275,275,275,275,275,275,275,276
2019-12-26,277,276,276,276,276,276,276,276,276,277
2019-12-27,277,276,276,277,276,276,277,276,276,277
2019-12-30,277,277,277,277,277,277,277,277,277,277
2019-12-31,277,276,276,276,276,276,276,276,276,277

In [376]:
df_turnover

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1
time,,,,,,,,,,,
2016-01-04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2016-01-05,1.739583,1.664921,1.739583,1.759162,1.790576,1.738220,1.748691,1.760417,1.832461,1.312500,3.052083
2016-01-06,1.802083,1.729167,1.770833,1.769634,1.750000,1.750000,1.759162,1.708333,1.635417,1.260417,3.062500
2016-01-07,1.802083,1.729167,1.739583,1.780105,1.729167,1.812500,1.832461,1.750000,1.718750,1.281250,3.083333
2016-01-08,1.750000,1.781250,1.822917,1.748691,1.770833,1.750000,1.863874,1.750000,1.656250,1.197917,2.947917
...,...,...,...,...,...,...,...,...,...,...,...
2019-12-25,1.833935,1.811594,1.724638,1.760870,1.775362,1.717391,1.789855,1.739130,1.702899,1.155235,2.989170
2019-12-26,1.841155,1.775362,1.804348,1.818841,1.826087,1.782609,1.797101,1.833333,1.644928,1.140794,2.981949
2019-12-27,1.790614,1.746377,1.746377,1.754513,1.746377,1.731884,1.797834,1.702899,1.666667,1.155235,2.945848
2019-12-30,1.776173,1.747292,1.725632,1.747292,1.740072,1.754513,1.732852,1.740072,1.638989,1.184116,2.960289
2019-12-31,1.812274,1.754513,1.768953,1.812274,1.797834,1.682310,1.740072,1.747292,1.602888,1.205776,3.018051

In [374]:
volatility[['ret']]

      ret
2016  NaN
2017  NaN
2018  NaN
2019  NaN
all   NaN

In [354]:
df[n_cols].mean().round().astype(int).to_frame('all').T

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10
all,235,234,234,234,234,234,234,234,234,235

In [351]:
df['year'] = pd.to_datetime(df['time']).dt.year
df.groupby('year')[n_cols].mean().round().astype(int)

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10
year,,,,,,,,,,
2016,196,196,196,196,195,195,196,196,196,196
2017,227,226,226,226,226,226,226,226,226,227
2018,248,247,247,247,247,247,247,247,247,248
2019,268,267,267,267,267,267,267,267,267,268

In [357]:
portfolio_number = 10
ret_col = [fc_name + ' ' + str(i) for i in range(1, portfolio_number + 1)] + \
    [f'{fc_name} {portfolio_number}-1', 'ret']
ret_col

['fac1 1',
 'fac1 2',
 'fac1 3',
 'fac1 4',
 'fac1 5',
 'fac1 6',
 'fac1 7',
 'fac1 8',
 'fac1 9',
 'fac1 10',
 'fac1 10-1',
 'ret']

In [364]:
sortino_ratio

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret
2016,-386.580644,-237.618031,-196.519129,-144.012782,-83.745146,18.913897,NaN,NaN,NaN,NaN,NaN,NaN
2017,-412.164698,-277.772101,-213.221276,-157.563392,-88.120528,20.626008,NaN,NaN,NaN,NaN,NaN,NaN
2018,-376.291878,-246.363550,-221.810361,-148.173772,-95.865254,13.886455,NaN,NaN,NaN,NaN,NaN,NaN
2019,-340.946343,-249.390132,-221.582266,-154.598955,-88.899541,10.954367,NaN,NaN,NaN,NaN,NaN,NaN
all,-330.985609,-244.508328,-209.365202,-146.390652,-86.013744,15.699618,NaN,NaN,NaN,NaN,NaN,NaN

In [368]:
df_turnover

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1
time,,,,,,,,,,,
2016-01-04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2016-01-05,1.739583,1.664921,1.739583,1.759162,1.790576,1.738220,1.748691,1.760417,1.832461,1.312500,3.052083
2016-01-06,1.802083,1.729167,1.770833,1.769634,1.750000,1.750000,1.759162,1.708333,1.635417,1.260417,3.062500
2016-01-07,1.802083,1.729167,1.739583,1.780105,1.729167,1.812500,1.832461,1.750000,1.718750,1.281250,3.083333
2016-01-08,1.750000,1.781250,1.822917,1.748691,1.770833,1.750000,1.863874,1.750000,1.656250,1.197917,2.947917
...,...,...,...,...,...,...,...,...,...,...,...
2019-12-25,1.833935,1.811594,1.724638,1.760870,1.775362,1.717391,1.789855,1.739130,1.702899,1.155235,2.989170
2019-12-26,1.841155,1.775362,1.804348,1.818841,1.826087,1.782609,1.797101,1.833333,1.644928,1.140794,2.981949
2019-12-27,1.790614,1.746377,1.746377,1.754513,1.746377,1.731884,1.797834,1.702899,1.666667,1.155235,2.945848
2019-12-30,1.776173,1.747292,1.725632,1.747292,1.740072,1.754513,1.732852,1.740072,1.638989,1.184116,2.960289
2019-12-31,1.812274,1.754513,1.768953,1.812274,1.797834,1.682310,1.740072,1.747292,1.602888,1.205776,3.018051

In [285]:
df = df_ret.reset_index().copy()
df = df.dropna()
df = df.sort_values(by='time', ascending=True)
df['year'] = pd.to_datetime(df['time']).dt.year

In [298]:
win_rate_list = []
for col in ret_col:
    win_rate_list.append(df.groupby('year')[col].apply(lambda x: len(x[x > 0]) / len(x)))
win_rate_year = pd.concat(win_rate_list, axis=1)
win_rate_all = (df[ret_col].apply(lambda x: len(x[x > 0]) / len(x))).to_frame('all').T
win_rate = pd.concat([win_rate_year, win_rate_all])
win_rate

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret
2016,0.0,0.0,0.0,0.0,0.0,0.688525,1.0,1.0,1.0,1.0,1.0,1.0
2017,0.0,0.0,0.0,0.0,0.0,0.721311,1.0,1.0,1.0,1.0,1.0,1.0
2018,0.0,0.0,0.0,0.0,0.0,0.679012,1.0,1.0,1.0,1.0,1.0,1.0
2019,0.0,0.0,0.0,0.0,0.0,0.614754,1.0,1.0,1.0,1.0,1.0,1.0
all,0.0,0.0,0.0,0.0,0.0,0.675897,1.0,1.0,1.0,1.0,1.0,1.0

In [297]:
(df[ret_col].apply(lambda x: len(x[x > 0]) / len(x))).to_frame('all').T

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret
all,0.0,0.0,0.0,0.0,0.0,0.675897,1.0,1.0,1.0,1.0,1.0,1.0

In [292]:
df.groupby('year')[ret_col[5]].apply(lambda x: len(x[x > 0]) / len(x))

year
2016    0.688525
2017    0.721311
2018    0.679012
2019    0.614754
Name: fac1 6, dtype: float64

In [274]:
nav = (1 + df[ret_col]).cumprod()
dd = 1 - nav / nav.cummax()
df['year'] = pd.to_datetime(df['time']).dt.year
(dd.max()).to_frame('all').T

/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/numpy/core/fromnumeric.py:57: RuntimeWarning: overflow encountered in accumulate
  return bound(*args, **kwds)

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret
all,1.0,1.0,1.0,1.0,1.0,0.286477,0.0,0.0,0.0,0.0,0.0,0.0

In [272]:
df.groupby('year')[ret_col].apply(_get_max_dd)

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret
year,,,,,,,,,,,,
2016,1.0,1.0,1.0,1.0,1.0,0.142074,0.0,0.0,0.0,0.0,0.0,0.0
2017,1.0,1.0,1.0,1.0,1.0,0.072010,0.0,0.0,0.0,0.0,0.0,0.0
2018,1.0,1.0,1.0,1.0,1.0,0.102118,0.0,0.0,0.0,0.0,0.0,0.0
2019,1.0,1.0,1.0,1.0,1.0,0.286477,0.0,0.0,0.0,0.0,0.0,0.0

In [267]:
df

,time,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret
0,2016-01-04,-0.579963,-0.472553,-0.401225,-0.262287,-0.153951,0.001236,0.400739,0.871920,1.721584,5.422670,3.001316,3.001316
1,2016-01-05,-0.600071,-0.463340,-0.314752,-0.233847,-0.178738,-0.007528,0.362218,0.784907,1.717890,5.017644,2.808857,2.808857
2,2016-01-06,-0.586025,-0.450195,-0.434366,-0.279482,-0.135954,0.031141,0.381593,0.834236,1.684192,5.699219,3.142622,3.142622
3,2016-01-07,-0.596590,-0.477745,-0.329280,-0.224581,-0.143455,0.021880,0.344934,0.803652,1.522940,5.523621,3.060105,3.060105
4,2016-01-08,-0.601678,-0.485890,-0.344306,-0.314502,-0.167587,0.041616,0.362942,0.809977,1.735349,5.152102,2.876890,2.876890
...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,2019-12-25,-0.677960,-0.460716,-0.396287,-0.288072,-0.191068,-0.032602,0.470827,1.127008,2.490854,9.834422,5.256191,5.256191
971,2019-12-26,-0.679133,-0.489920,-0.366845,-0.287966,-0.181993,0.010148,0.393007,1.037260,2.389408,10.174387,5.426760,5.426760
972,2019-12-27,-0.628659,-0.487296,-0.377135,-0.352592,-0.178850,-0.032565,0.429172,1.216365,2.617670,12.107270,6.367964,6.367964
973,2019-12-30,-0.586037,-0.460991,-0.380806,-0.312685,-0.195619,-0.010073,0.380871,1.079207,2.366753,9.702409,5.144223,5.144223
974,2019-12-31,-0.669128,-0.445808,-0.371206,-0.323041,-0.186439,-0.039401,0.448818,1.192512,2.547832,11.080789,5.874959,5.874959

In [266]:
nav

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret
0,0.420037,5.274470e-01,5.987748e-01,7.377127e-01,8.460488e-01,1.001236e+00,1.400739e+00,1.871920e+00,2.721584,6.422670e+00,4.001316,4.001316
1,0.167985,2.830598e-01,4.103090e-01,5.652008e-01,6.948276e-01,9.936987e-01,1.908112e+00,3.341204e+00,7.396965,3.864934e+01,15.240443,15.240443
2,0.069542,1.556278e-01,2.320847e-01,4.072372e-01,6.003630e-01,1.024643e+00,2.636233e+00,6.128556e+00,19.854875,2.589204e+02,63.135392,63.135392
3,0.028054,8.127733e-02,1.556639e-01,3.157793e-01,5.142382e-01,1.047062e+00,3.545560e+00,1.105379e+01,50.092666,1.689098e+03,256.336331,256.336331
4,0.011174,4.178547e-02,1.020680e-01,2.164661e-01,4.280587e-01,1.090637e+00,4.832393e+00,2.000710e+01,137.020904,1.039151e+04,993.787822,993.787822
...,...,...,...,...,...,...,...,...,...,...,...,...
970,0.000000,1.213159e-254,6.030070e-192,1.436732e-140,1.677529e-83,7.276234e+06,1.680680e+128,2.899149e+269,inf,inf,inf,inf
971,0.000000,6.188085e-255,3.817970e-192,1.023002e-140,1.372230e-83,7.350071e+06,2.341199e+128,5.906320e+269,inf,inf,inf,inf
972,0.000000,3.172653e-255,2.378081e-192,6.622999e-141,1.126807e-83,7.110715e+06,3.345976e+128,1.309056e+270,inf,inf,inf,inf
973,0.000000,1.710087e-255,1.472494e-192,4.552089e-141,9.063822e-84,7.039085e+06,4.620359e+128,2.721799e+270,inf,inf,inf,inf
974,0.000000,9.477168e-256,9.258948e-193,3.081580e-141,7.373976e-84,6.761740e+06,6.694061e+128,5.967577e+270,inf,inf,inf,inf

In [254]:
volatility_list = []
ret = get_annualized_ret(df, ret_col, 'simple')
for col in ret_col:
    df_down = df.loc[df[col] < 0]
    volatility = get_annualized_volatility(df_down, [col])
    volatility_list.append(volatility)
volatility = pd.concat(volatility_list, axis=1)
sortino_ratio = ret / volatility
sortino_ratio

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret
2016,-386.580644,-237.618031,-196.519129,-144.012782,-83.745146,18.913897,NaN,NaN,NaN,NaN,NaN,NaN
2017,-412.164698,-277.772101,-213.221276,-157.563392,-88.120528,20.626008,NaN,NaN,NaN,NaN,NaN,NaN
2018,-376.291878,-246.363550,-221.810361,-148.173772,-95.865254,13.886455,NaN,NaN,NaN,NaN,NaN,NaN
2019,-340.946343,-249.390132,-221.582266,-154.598955,-88.899541,10.954367,NaN,NaN,NaN,NaN,NaN,NaN
all,-330.985609,-244.508328,-209.365202,-146.390652,-86.013744,15.699618,NaN,NaN,NaN,NaN,NaN,NaN

In [253]:
volatility

     ret
all  NaN

In [259]:
get_sortino_ratio(df_ret.reset_index(), ret_col)

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret
2016,-386.580644,-237.618031,-196.519129,-144.012782,-83.745146,18.913897,NaN,NaN,NaN,NaN,NaN,NaN
2017,-412.164698,-277.772101,-213.221276,-157.563392,-88.120528,20.626008,NaN,NaN,NaN,NaN,NaN,NaN
2018,-376.291878,-246.363550,-221.810361,-148.173772,-95.865254,13.886455,NaN,NaN,NaN,NaN,NaN,NaN
2019,-340.946343,-249.390132,-221.582266,-154.598955,-88.899541,10.954367,NaN,NaN,NaN,NaN,NaN,NaN
all,-330.985609,-244.508328,-209.365202,-146.390652,-86.013744,15.699618,NaN,NaN,NaN,NaN,NaN,NaN

In [219]:
get_sharpe(ret, volatility)

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret
2016,-386.580644,-237.618031,-196.519129,-144.012782,-83.745146,8.504790,129.854104,270.093964,371.814578,63.453028,70.205664,70.205664
2017,-412.164698,-277.772101,-213.221276,-157.563392,-88.120528,9.843844,146.296025,239.058240,258.662127,208.274758,226.295301,226.295301
2018,-376.291878,-246.363550,-221.810361,-148.173772,-95.865254,7.425095,150.672727,243.732893,260.581861,187.215219,202.420013,202.420013
2019,-340.946343,-249.390132,-221.582266,-154.598955,-88.899541,5.819975,137.236916,172.319006,150.109323,80.647559,86.221404,86.221404
all,-330.985609,-244.508328,-209.365202,-146.390652,-86.013744,7.870794,124.924461,151.970159,137.819188,64.992322,70.430801,70.430801

In [162]:
ret_col = df_ret.columns.to_list()

In [170]:
1 + df_ret[ret_col]

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret
time,,,,,,,,,,,,
2016-01-04,0.420037,0.527447,0.598775,0.737713,0.846049,1.001236,1.400739,1.871920,2.721584,6.422670,4.001316,4.001316
2016-01-05,0.399929,0.536660,0.685248,0.766153,0.821262,0.992472,1.362218,1.784907,2.717890,6.017644,3.808857,3.808857
2016-01-06,0.413975,0.549805,0.565634,0.720518,0.864046,1.031141,1.381593,1.834236,2.684192,6.699219,4.142622,4.142622
2016-01-07,0.403410,0.522255,0.670720,0.775419,0.856545,1.021880,1.344934,1.803652,2.522940,6.523621,4.060105,4.060105
2016-01-08,0.398322,0.514110,0.655694,0.685498,0.832413,1.041616,1.362942,1.809977,2.735349,6.152102,3.876890,3.876890
...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-25,0.322040,0.539284,0.603713,0.711928,0.808932,0.967398,1.470827,2.127008,3.490854,10.834422,6.256191,6.256191
2019-12-26,0.320867,0.510080,0.633155,0.712034,0.818007,1.010148,1.393007,2.037260,3.389408,11.174387,6.426760,6.426760
2019-12-27,0.371341,0.512704,0.622865,0.647408,0.821150,0.967435,1.429172,2.216365,3.617670,13.107270,7.367964,7.367964
2019-12-30,0.413963,0.539009,0.619194,0.687315,0.804381,0.989927,1.380871,2.079207,3.366753,10.702409,6.144223,6.144223
2019-12-31,0.330872,0.554192,0.628794,0.676959,0.813561,0.960599,1.448818,2.192512,3.547832,12.080789,6.874959,6.874959

In [172]:
0.420037 * 0.399929 * 0.413975

0.06954158100798767

In [173]:
df_cumret = (1 + df_ret[ret_col]).cumprod()

/Users/wenglongao/anaconda3/envs/leoweng4.1/lib/python3.9/site-packages/numpy/core/fromnumeric.py:57: RuntimeWarning: overflow encountered in accumulate
  return bound(*args, **kwds)

In [177]:
df_cumret = df_cumret.reset_index()

In [178]:
df_cumret['year'] = pd.to_datetime(df_cumret['time']).dt.year

In [185]:
df_cumret

,time,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret,year
0,2016-01-04,0.420037,5.274470e-01,5.987748e-01,7.377127e-01,8.460488e-01,1.001236e+00,1.400739e+00,1.871920e+00,2.721584,6.422670e+00,4.001316,4.001316,2016
1,2016-01-05,0.167985,2.830598e-01,4.103090e-01,5.652008e-01,6.948276e-01,9.936987e-01,1.908112e+00,3.341204e+00,7.396965,3.864934e+01,15.240443,15.240443,2016
2,2016-01-06,0.069542,1.556278e-01,2.320847e-01,4.072372e-01,6.003630e-01,1.024643e+00,2.636233e+00,6.128556e+00,19.854875,2.589204e+02,63.135392,63.135392,2016
3,2016-01-07,0.028054,8.127733e-02,1.556639e-01,3.157793e-01,5.142382e-01,1.047062e+00,3.545560e+00,1.105379e+01,50.092666,1.689098e+03,256.336331,256.336331,2016
4,2016-01-08,0.011174,4.178547e-02,1.020680e-01,2.164661e-01,4.280587e-01,1.090637e+00,4.832393e+00,2.000710e+01,137.020904,1.039151e+04,993.787822,993.787822,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,2019-12-25,0.000000,1.213159e-254,6.030070e-192,1.436732e-140,1.677529e-83,7.276234e+06,1.680680e+128,2.899149e+269,inf,inf,inf,inf,2019
971,2019-12-26,0.000000,6.188085e-255,3.817970e-192,1.023002e-140,1.372230e-83,7.350071e+06,2.341199e+128,5.906320e+269,inf,inf,inf,inf,2019
972,2019-12-27,0.000000,3.172653e-255,2.378081e-192,6.622999e-141,1.126807e-83,7.110715e+06,3.345976e+128,1.309056e+270,inf,inf,inf,inf,2019
973,2019-12-30,0.000000,1.710087e-255,1.472494e-192,4.552089e-141,9.063822e-84,7.039085e+06,4.620359e+128,2.721799e+270,inf,inf,inf,inf,2019
974,2019-12-31,0.000000,9.477168e-256,9.258948e-193,3.081580e-141,7.373976e-84,6.761740e+06,6.694061e+128,5.967577e+270,inf,inf,inf,inf,2019

In [188]:
df_cumret[ret_col].iloc[-1]

fac1 1        0.000000e+00
fac1 2       9.477168e-256
fac1 3       9.258948e-193
fac1 4       3.081580e-141
fac1 5        7.373976e-84
fac1 6        6.761740e+06
fac1 7       6.694061e+128
fac1 8       5.967577e+270
fac1 9                 inf
fac1 10                inf
fac1 10-1              inf
ret                    inf
Name: 974, dtype: float64

In [191]:
(df_cumret[ret_col].iloc[-1] ** (252 / len(df_cumret[ret_col])) - 1).to_frame('all').T

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret
all,-1.0,-1.0,-1.0,-1.0,-1.0,57.251542,1.979183e+33,9.663386e+69,inf,inf,inf,inf

In [190]:
pd.Series(df_cumret[ret_col].iloc[-1] ** (252 / len(df_cumret[ret_col])) - 1, index=['all'])

all   NaN
Name: 974, dtype: float64

In [181]:
df_cumret.groupby('year')[ret_col].apply(
            lambda x: (x.iloc[-1] / x.iloc[0]) ** (252 / len(x)) - 1)

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret
year,,,,,,,,,,,,
2016,-1.0,-1.0,-1.0,-1.0,-1.0,85.023497,1.117156e+31,2.154897e+65,4.485807e+108,1.202871e+202,5.178268e+150,5.178268e+150
2017,-1.0,-1.0,-1.0,-1.0,-1.0,132.758889,9.873896e+31,3.506966e+66,1.773200e+110,inf,5.104611e+151,5.104611e+151
2018,-1.0,-1.0,-1.0,-1.0,-1.0,60.841289,3.560316e+34,6.031620e+72,inf,NaN,inf,inf
2019,-1.0,-1.0,-1.0,-1.0,-1.0,13.127297,1.135353e+35,1.505756e+74,NaN,NaN,NaN,NaN

In [174]:
df_cumret

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret
time,,,,,,,,,,,,
2016-01-04,0.420037,5.274470e-01,5.987748e-01,7.377127e-01,8.460488e-01,1.001236e+00,1.400739e+00,1.871920e+00,2.721584,6.422670e+00,4.001316,4.001316
2016-01-05,0.167985,2.830598e-01,4.103090e-01,5.652008e-01,6.948276e-01,9.936987e-01,1.908112e+00,3.341204e+00,7.396965,3.864934e+01,15.240443,15.240443
2016-01-06,0.069542,1.556278e-01,2.320847e-01,4.072372e-01,6.003630e-01,1.024643e+00,2.636233e+00,6.128556e+00,19.854875,2.589204e+02,63.135392,63.135392
2016-01-07,0.028054,8.127733e-02,1.556639e-01,3.157793e-01,5.142382e-01,1.047062e+00,3.545560e+00,1.105379e+01,50.092666,1.689098e+03,256.336331,256.336331
2016-01-08,0.011174,4.178547e-02,1.020680e-01,2.164661e-01,4.280587e-01,1.090637e+00,4.832393e+00,2.000710e+01,137.020904,1.039151e+04,993.787822,993.787822
...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-25,0.000000,1.213159e-254,6.030070e-192,1.436732e-140,1.677529e-83,7.276234e+06,1.680680e+128,2.899149e+269,inf,inf,inf,inf
2019-12-26,0.000000,6.188085e-255,3.817970e-192,1.023002e-140,1.372230e-83,7.350071e+06,2.341199e+128,5.906320e+269,inf,inf,inf,inf
2019-12-27,0.000000,3.172653e-255,2.378081e-192,6.622999e-141,1.126807e-83,7.110715e+06,3.345976e+128,1.309056e+270,inf,inf,inf,inf
2019-12-30,0.000000,1.710087e-255,1.472494e-192,4.552089e-141,9.063822e-84,7.039085e+06,4.620359e+128,2.721799e+270,inf,inf,inf,inf
2019-12-31,0.000000,9.477168e-256,9.258948e-193,3.081580e-141,7.373976e-84,6.761740e+06,6.694061e+128,5.967577e+270,inf,inf,inf,inf

In [159]:
(df_ret.mean() * 252).to_frame('all').T

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret
all,-149.933539,-113.815394,-91.730265,-70.999766,-44.756096,4.239994,89.799205,226.234856,476.896762,1624.264983,887.099261,887.099261

In [203]:
get_annualized_return(df_ret.reset_index(), df_ret.columns.to_list(), 'simple')

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret
2016,-146.325729,-110.967367,-90.235659,-68.148350,-43.081558,4.640368,83.279141,207.121692,431.121464,1371.260257,758.792993,758.792993
2017,-146.929406,-113.637446,-90.706763,-70.378238,-42.141733,5.080406,86.085322,212.255017,441.450995,1379.371431,763.150418,763.150418
2018,-152.162022,-115.165889,-93.293149,-72.759825,-47.081374,4.384659,94.135132,239.545458,506.157397,1688.614671,920.388347,920.388347
2019,-154.326133,-115.496409,-92.691893,-72.719864,-46.729249,2.855134,95.714995,246.071810,528.977111,2058.077302,1106.201717,1106.201717
all,-149.933539,-113.815394,-91.730265,-70.999766,-44.756096,4.239994,89.799205,226.234856,476.896762,1624.264983,887.099261,887.099261

In [135]:
df_turnover

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1
time,,,,,,,,,,,
2016-01-04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2016-01-05,1.739583,1.664921,1.739583,1.759162,1.790576,1.738220,1.748691,1.760417,1.832461,1.312500,3.052083
2016-01-06,1.802083,1.729167,1.770833,1.769634,1.750000,1.750000,1.759162,1.708333,1.635417,1.260417,3.062500
2016-01-07,1.802083,1.729167,1.739583,1.780105,1.729167,1.812500,1.832461,1.750000,1.718750,1.281250,3.083333
2016-01-08,1.750000,1.781250,1.822917,1.748691,1.770833,1.750000,1.863874,1.750000,1.656250,1.197917,2.947917
...,...,...,...,...,...,...,...,...,...,...,...
2019-12-25,1.833935,1.811594,1.724638,1.760870,1.775362,1.717391,1.789855,1.739130,1.702899,1.155235,2.989170
2019-12-26,1.841155,1.775362,1.804348,1.818841,1.826087,1.782609,1.797101,1.833333,1.644928,1.140794,2.981949
2019-12-27,1.790614,1.746377,1.746377,1.754513,1.746377,1.731884,1.797834,1.702899,1.666667,1.155235,2.945848
2019-12-30,1.776173,1.747292,1.725632,1.747292,1.740072,1.754513,1.732852,1.740072,1.638989,1.184116,2.960289
2019-12-31,1.812274,1.754513,1.768953,1.812274,1.797834,1.682310,1.740072,1.747292,1.602888,1.205776,3.018051

In [140]:
df_ret

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret
time,,,,,,,,,,,,
2016-01-04,-0.579963,-0.472553,-0.401225,-0.262287,-0.153951,0.001236,0.400739,0.871920,1.721584,5.422670,3.001316,3.001316
2016-01-05,-0.600071,-0.463340,-0.314752,-0.233847,-0.178738,-0.007528,0.362218,0.784907,1.717890,5.017644,2.808857,2.808857
2016-01-06,-0.586025,-0.450195,-0.434366,-0.279482,-0.135954,0.031141,0.381593,0.834236,1.684192,5.699219,3.142622,3.142622
2016-01-07,-0.596590,-0.477745,-0.329280,-0.224581,-0.143455,0.021880,0.344934,0.803652,1.522940,5.523621,3.060105,3.060105
2016-01-08,-0.601678,-0.485890,-0.344306,-0.314502,-0.167587,0.041616,0.362942,0.809977,1.735349,5.152102,2.876890,2.876890
...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-25,-0.677960,-0.460716,-0.396287,-0.288072,-0.191068,-0.032602,0.470827,1.127008,2.490854,9.834422,5.256191,5.256191
2019-12-26,-0.679133,-0.489920,-0.366845,-0.287966,-0.181993,0.010148,0.393007,1.037260,2.389408,10.174387,5.426760,5.426760
2019-12-27,-0.628659,-0.487296,-0.377135,-0.352592,-0.178850,-0.032565,0.429172,1.216365,2.617670,12.107270,6.367964,6.367964
2019-12-30,-0.586037,-0.460991,-0.380806,-0.312685,-0.195619,-0.010073,0.380871,1.079207,2.366753,9.702409,5.144223,5.144223
2019-12-31,-0.669128,-0.445808,-0.371206,-0.323041,-0.186439,-0.039401,0.448818,1.192512,2.547832,11.080789,5.874959,5.874959

In [139]:
ret_year = df_ret.reset_index()
ret_year['year'] = pd.to_datetime(ret_year['time']).dt.year
ic_year = ic_year.groupby('year')[ic_cols].mean()

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret
time,,,,,,,,,,,,
2016-01-04,-0.579963,-0.472553,-0.401225,-0.262287,-0.153951,0.001236,0.400739,0.871920,1.721584,5.422670,3.001316,3.001316
2016-01-05,-0.600071,-0.463340,-0.314752,-0.233847,-0.178738,-0.007528,0.362218,0.784907,1.717890,5.017644,2.808857,2.808857
2016-01-06,-0.586025,-0.450195,-0.434366,-0.279482,-0.135954,0.031141,0.381593,0.834236,1.684192,5.699219,3.142622,3.142622
2016-01-07,-0.596590,-0.477745,-0.329280,-0.224581,-0.143455,0.021880,0.344934,0.803652,1.522940,5.523621,3.060105,3.060105
2016-01-08,-0.601678,-0.485890,-0.344306,-0.314502,-0.167587,0.041616,0.362942,0.809977,1.735349,5.152102,2.876890,2.876890
...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-25,-0.677960,-0.460716,-0.396287,-0.288072,-0.191068,-0.032602,0.470827,1.127008,2.490854,9.834422,5.256191,5.256191
2019-12-26,-0.679133,-0.489920,-0.366845,-0.287966,-0.181993,0.010148,0.393007,1.037260,2.389408,10.174387,5.426760,5.426760
2019-12-27,-0.628659,-0.487296,-0.377135,-0.352592,-0.178850,-0.032565,0.429172,1.216365,2.617670,12.107270,6.367964,6.367964
2019-12-30,-0.586037,-0.460991,-0.380806,-0.312685,-0.195619,-0.010073,0.380871,1.079207,2.366753,9.702409,5.144223,5.144223
2019-12-31,-0.669128,-0.445808,-0.371206,-0.323041,-0.186439,-0.039401,0.448818,1.192512,2.547832,11.080789,5.874959,5.874959

In [130]:
df_ret = df_ret.groupby('time').sum()

In [137]:
df_net_ret

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret
time,,,,,,,,,,,,
2016-01-04,-0.579963,-0.472553,-0.401225,-0.262287,-0.153951,0.001236,0.400739,0.871920,1.721584,5.422670,3.001316,3.001316
2016-01-05,-0.600505,-0.463756,-0.315187,-0.234287,-0.179186,-0.007962,0.361781,0.784467,1.717432,5.017316,2.808094,2.808094
2016-01-06,-0.586476,-0.450627,-0.434809,-0.279925,-0.136391,0.030703,0.381153,0.833809,1.683783,5.698904,3.141856,3.141856
2016-01-07,-0.597040,-0.478178,-0.329715,-0.225026,-0.143887,0.021427,0.344476,0.803215,1.522511,5.523300,3.059334,3.059334
2016-01-08,-0.602116,-0.486336,-0.344761,-0.314939,-0.168029,0.041179,0.362476,0.809540,1.734935,5.151803,2.876153,2.876153
...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-25,-0.678418,-0.461169,-0.396718,-0.288513,-0.191512,-0.033032,0.470380,1.126573,2.490428,9.834133,5.255444,5.255444
2019-12-26,-0.679593,-0.490364,-0.367296,-0.288421,-0.182450,0.009702,0.392557,1.036802,2.388996,10.174102,5.426014,5.426014
2019-12-27,-0.629107,-0.487733,-0.377571,-0.353031,-0.179286,-0.032998,0.428722,1.215940,2.617253,12.106981,6.367228,6.367228
2019-12-30,-0.586481,-0.461428,-0.381237,-0.313121,-0.196054,-0.010512,0.380437,1.078772,2.366343,9.702113,5.143483,5.143483
2019-12-31,-0.669581,-0.446247,-0.371649,-0.323494,-0.186888,-0.039821,0.448383,1.192075,2.547431,11.080488,5.874204,5.874204

In [138]:
df_n

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10
time,,,,,,,,,,
2016-01-04,191,191,191,191,191,191,191,191,191,191
2016-01-05,192,191,192,191,191,191,191,192,191,192
2016-01-06,192,192,192,191,192,192,191,192,192,192
2016-01-07,192,191,191,191,191,191,191,191,191,192
2016-01-08,192,192,192,191,192,192,191,192,192,192
...,...,...,...,...,...,...,...,...,...,...
2019-12-25,276,275,275,275,275,275,275,275,275,276
2019-12-26,277,276,276,276,276,276,276,276,276,277
2019-12-27,277,276,276,277,276,276,277,276,276,277
2019-12-30,277,277,277,277,277,277,277,277,277,277
2019-12-31,277,276,276,276,276,276,276,276,276,277

In [112]:
# 多空组合的turnover如何计算？
# 根据定义，等于组合10的turnover + 组合1的turnover
df_turnover[f'{fc_name} {portfolio_number}-1'] = (df_turnover[f'{fc_name} {portfolio_number}'] + df_turnover[f'{fc_name} {1}'])

In [103]:
turnover_arr

time
2016-01-04    0.000000
2016-01-05    1.312500
2016-01-06    1.260417
2016-01-07    1.281250
2016-01-08    1.197917
                ...
2019-12-25    1.155235
2019-12-26    1.140794
2019-12-27    1.155235
2019-12-30    1.184116
2019-12-31    1.205776
Length: 975, dtype: float64

In [115]:
df_turnover

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1
time,,,,,,,,,,,
2016-01-04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2016-01-05,1.739583,1.664921,1.739583,1.759162,1.790576,1.738220,1.748691,1.760417,1.832461,1.312500,3.052083
2016-01-06,1.802083,1.729167,1.770833,1.769634,1.750000,1.750000,1.759162,1.708333,1.635417,1.260417,3.062500
2016-01-07,1.802083,1.729167,1.739583,1.780105,1.729167,1.812500,1.832461,1.750000,1.718750,1.281250,3.083333
2016-01-08,1.750000,1.781250,1.822917,1.748691,1.770833,1.750000,1.863874,1.750000,1.656250,1.197917,2.947917
...,...,...,...,...,...,...,...,...,...,...,...
2019-12-25,1.833935,1.811594,1.724638,1.760870,1.775362,1.717391,1.789855,1.739130,1.702899,1.155235,2.989170
2019-12-26,1.841155,1.775362,1.804348,1.818841,1.826087,1.782609,1.797101,1.833333,1.644928,1.140794,2.981949
2019-12-27,1.790614,1.746377,1.746377,1.754513,1.746377,1.731884,1.797834,1.702899,1.666667,1.155235,2.945848
2019-12-30,1.776173,1.747292,1.725632,1.747292,1.740072,1.754513,1.732852,1.740072,1.638989,1.184116,2.960289
2019-12-31,1.812274,1.754513,1.768953,1.812274,1.797834,1.682310,1.740072,1.747292,1.602888,1.205776,3.018051

In [104]:
df_n

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10
time,,,,,,,,,,
2016-01-04,191,191,191,191,191,191,191,191,191,191
2016-01-05,192,191,192,191,191,191,191,192,191,192
2016-01-06,192,192,192,191,192,192,191,192,192,192
2016-01-07,192,191,191,191,191,191,191,191,191,192
2016-01-08,192,192,192,191,192,192,191,192,192,192
...,...,...,...,...,...,...,...,...,...,...
2019-12-25,276,275,275,275,275,275,275,275,275,276
2019-12-26,277,276,276,276,276,276,276,276,276,277
2019-12-27,277,276,276,277,276,276,277,276,276,277
2019-12-30,277,277,277,277,277,277,277,277,277,277
2019-12-31,277,276,276,276,276,276,276,276,276,277

In [116]:
cost = 0.00025

In [117]:
df_net_ret = df_ret - df_turnover * cost

In [118]:
df_net_ret

,fac1 1,fac1 10,fac1 10-1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,ret
time,,,,,,,,,,,,
2016-01-04,-0.579963,5.422670,3.001316,-0.472553,-0.401225,-0.262287,-0.153951,0.001236,0.400739,0.871920,1.721584,NaN
2016-01-05,-0.600505,5.017316,2.808094,-0.463756,-0.315187,-0.234287,-0.179186,-0.007962,0.361781,0.784467,1.717432,NaN
2016-01-06,-0.586476,5.698904,3.141856,-0.450627,-0.434809,-0.279925,-0.136391,0.030703,0.381153,0.833809,1.683783,NaN
2016-01-07,-0.597040,5.523300,3.059334,-0.478178,-0.329715,-0.225026,-0.143887,0.021427,0.344476,0.803215,1.522511,NaN
2016-01-08,-0.602116,5.151803,2.876153,-0.486336,-0.344761,-0.314939,-0.168029,0.041179,0.362476,0.809540,1.734935,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-25,-0.678418,9.834133,5.255444,-0.461169,-0.396718,-0.288513,-0.191512,-0.033032,0.470380,1.126573,2.490428,NaN
2019-12-26,-0.679593,10.174102,5.426014,-0.490364,-0.367296,-0.288421,-0.182450,0.009702,0.392557,1.036802,2.388996,NaN
2019-12-27,-0.629107,12.106981,6.367228,-0.487733,-0.377571,-0.353031,-0.179286,-0.032998,0.428722,1.215940,2.617253,NaN
2019-12-30,-0.586481,9.702113,5.143483,-0.461428,-0.381237,-0.313121,-0.196054,-0.010512,0.380437,1.078772,2.366343,NaN
2019-12-31,-0.669581,11.080488,5.874204,-0.446247,-0.371649,-0.323494,-0.186888,-0.039821,0.448383,1.192075,2.547431,NaN

In [106]:
df_ret

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10,fac1 10-1,ret
time,,,,,,,,,,,,
2016-01-04,-0.579963,-0.472553,-0.401225,-0.262287,-0.153951,0.001236,0.400739,0.871920,1.721584,5.422670,3.001316,3.001316
2016-01-05,-0.600071,-0.463340,-0.314752,-0.233847,-0.178738,-0.007528,0.362218,0.784907,1.717890,5.017644,2.808857,2.808857
2016-01-06,-0.586025,-0.450195,-0.434366,-0.279482,-0.135954,0.031141,0.381593,0.834236,1.684192,5.699219,3.142622,3.142622
2016-01-07,-0.596590,-0.477745,-0.329280,-0.224581,-0.143455,0.021880,0.344934,0.803652,1.522940,5.523621,3.060105,3.060105
2016-01-08,-0.601678,-0.485890,-0.344306,-0.314502,-0.167587,0.041616,0.362942,0.809977,1.735349,5.152102,2.876890,2.876890
...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-25,-0.677960,-0.460716,-0.396287,-0.288072,-0.191068,-0.032602,0.470827,1.127008,2.490854,9.834422,5.256191,5.256191
2019-12-26,-0.679133,-0.489920,-0.366845,-0.287966,-0.181993,0.010148,0.393007,1.037260,2.389408,10.174387,5.426760,5.426760
2019-12-27,-0.628659,-0.487296,-0.377135,-0.352592,-0.178850,-0.032565,0.429172,1.216365,2.617670,12.107270,6.367964,6.367964
2019-12-30,-0.586037,-0.460991,-0.380806,-0.312685,-0.195619,-0.010073,0.380871,1.079207,2.366753,9.702409,5.144223,5.144223
2019-12-31,-0.669128,-0.445808,-0.371206,-0.323041,-0.186439,-0.039401,0.448818,1.192512,2.547832,11.080789,5.874959,5.874959

In [76]:
i = 2
df.groupby('time').apply(
        lambda x: (((x[fc_name] > x[f'quantile_{i}']) &
                    (x[fc_name] < x[f'quantile_{i + 1}'])) * x['ret']).sum() / (
                            (x[fc_name] > x[f'quantile_{i}']) & 
                            (x[fc_name] < x[f'quantile_{i + 1}'])).sum(), include_groups=False)

time
2016-01-04   -0.401225
2016-01-05   -0.314752
2016-01-06   -0.434366
2016-01-07   -0.329280
2016-01-08   -0.344306
                ...
2019-12-25   -0.396287
2019-12-26   -0.366845
2019-12-27   -0.377135
2019-12-30   -0.380806
2019-12-31   -0.371206
Length: 975, dtype: float64

In [77]:
df.head(10)

                           open   high    low  close  volume      fac1  fac2  \
time       instrument_id
2016-01-04 600895         28.68  28.70  25.95  25.95  350024       NaN   NaN
           002318         15.37  15.45  13.77  13.77  278024       NaN   NaN
           600358         17.13  17.13  15.30  15.30  128171  0.580475   NaN
           600363         20.43  20.85  18.48  18.51  148094  0.098693   NaN
           601992          9.38   9.38   8.52   8.53  141857 -0.748972   NaN
           600371         22.20  22.43  20.25  20.25   43926  1.913142   NaN
           600791          9.38   9.43   8.44   8.44  107465 -1.957184   NaN
           600167         20.11  20.12  18.18  18.20   30871  1.739608   NaN
           601939          5.77   5.78   5.57   5.60  610415 -1.848706   NaN
           002321         13.29  13.30  11.89  11.90  155489  1.817308   NaN

                               ret  quantile_0  quantile_1  quantile_2  \
time       instrument_id
2016-01-04 600895              NaN        -inf   -2.968562   -1.623216
           002318        -0.469364        -inf   -2.968562   -1.623216
           600358         0.111111        -inf   -2.968562   -1.623216
           600363         0.209804        -inf   -2.968562   -1.623216
           601992        -0.539168        -inf   -2.968562   -1.623216
           600371         1.373974        -inf   -2.968562   -1.623216
           600791        -0.583210        -inf   -2.968562   -1.623216
           600167         1.156398        -inf   -2.968562   -1.623216
           601939        -0.692308        -inf   -2.968562   -1.623216
           002321         1.125000        -inf   -2.968562   -1.623216

                          quantile_3  quantile_4  quantile_5  quantile_6  \
time       instrument_id
2016-01-04 600895          -0.885072   -0.346814    0.037865    0.455634
           002318          -0.885072   -0.346814    0.037865    0.455634
           600358          -0.885072   -0.346814    0.037865    0.455634
           600363          -0.885072   -0.346814    0.037865    0.455634
           601992          -0.885072   -0.346814    0.037865    0.455634
           600371          -0.885072   -0.346814    0.037865    0.455634
           600791          -0.885072   -0.346814    0.037865    0.455634
           600167          -0.885072   -0.346814    0.037865    0.455634
           601939          -0.885072   -0.346814    0.037865    0.455634
           002321          -0.885072   -0.346814    0.037865    0.455634

                          quantile_7  quantile_8  quantile_9  quantile_10
time       instrument_id
2016-01-04 600895           0.947651    1.578527    2.976964          inf
           002318           0.947651    1.578527    2.976964          inf
           600358           0.947651    1.578527    2.976964          inf
           600363           0.947651    1.578527    2.976964          inf
           601992           0.947651    1.578527    2.976964          inf
           600371           0.947651    1.578527    2.976964          inf
           600791           0.947651    1.578527    2.976964          inf
           600167           0.947651    1.578527    2.976964          inf
           601939           0.947651    1.578527    2.976964          inf
           002321           0.947651    1.578527    2.976964          inf

In [19]:
df.groupby('time').apply(lambda x: (x[fc_name] > x[f'quantile_{1}']) &
                                           (x[fc_name] < x[f'quantile_{1 + 1}']), include_groups=False) * 1

time
2016-01-04  1335036    0
            638250     0
            2012869    0
            1787534    0
            408157     0
                      ..
2019-12-31  1922417    0
            960383     0
            511501     0
            1246174    0
            2237541    0
Length: 2283779, dtype: int64

In [436]:
df_turnover

                    fac1 1  fac1 2  fac1 3  fac1 4  fac1 5  fac1 6  fac1 7  \
time
2016-01-04 1335036       0       0       0       0       0       0       0
           638250        0       0       0       0       0       0       0
           2012869       0       0       0       0       0       0       0
           1787534       0       0       0       0       0       0       0
           408157        0       0       0       0       0       0       0
...                    ...     ...     ...     ...     ...     ...     ...
2019-12-31 1922417       0       0       0       0       0       0       0
           960383        0       0       0       0       0       0       0
           511501        0       0       0       0       0       0       0
           1246174       0       0       0       0       0       0       0
           2237541       0       0       0       0       0       0       0

                    fac1 8  fac1 9  fac1 10
time
2016-01-04 1335036       0       0        0
           638250        0       0        0
           2012869       0       0        0
           1787534       0       0        0
           408157        0       0        0
...                    ...     ...      ...
2019-12-31 1922417       0       0        0
           960383        0       0        0
           511501        0       0        0
           1246174       0       0        0
           2237541       0       0        0

[2283779 rows x 10 columns]

In [ ]:
# 如何求每个分组的换手？

In [417]:
df_turnover = pd.DataFrame()

In [70]:
arr = df.groupby('time', as_index=False).apply(lambda x: (x[fc_name] > x[f'quantile_{1}']) &
                                         (x[fc_name] < x[f'quantile_{1 + 1}']), include_groups=False).droplevel(0)

In [109]:
arr3

instrument_id,000001,000002,000005,000006,000007,000008,000009,000010,000011,000014,...,870199,870299,870436,870976,871396,871553,871634,871642,871970,872351
time,,,,,,,,,,,,,,,,,,,,,
2016-01-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2016-01-05,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2016-01-06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2016-01-07,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2016-01-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-12-26,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-12-27,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-12-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-12-31,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [86]:
arr3 = (arr.unstack() * 1).astype(float).fillna(0)

In [110]:
arr

time        instrument_id
2016-01-04  600895           False
            002318           False
            600358           False
            600363           False
            601992           False
                             ...
2019-12-31  601001           False
            600735           False
            002636           False
            603999           False
            300293           False
Length: 2283779, dtype: bool

In [95]:
arr3.apply(lambda x: x / arr1)

instrument_id,000001,000002,000005,000006,000007,000008,000009,000010,000011,000014,...,870199,870299,870436,870976,871396,871553,871634,871642,871970,872351
time,,,,,,,,,,,,,,,,,,,,,
2016-01-04,0.00000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.00000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2016-01-05,0.00000,0.0,0.0,0.005208,0.0,0.005208,0.0,0.000000,0.00000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2016-01-06,0.00000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.00000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2016-01-07,0.00000,0.0,0.0,0.000000,0.0,0.005208,0.0,0.000000,0.00000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2016-01-08,0.00000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.00000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-25,0.00000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.003623,0.00000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-12-26,0.00361,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.00000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-12-27,0.00000,0.0,0.0,0.000000,0.0,0.003610,0.0,0.000000,0.00361,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-12-30,0.00000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.00000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-12-31,0.00361,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.00361,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [88]:
arr3.diff().abs().sum(axis=1)

time
2016-01-04      0.0
2016-01-05    318.0
2016-01-06    331.0
2016-01-07    331.0
2016-01-08    341.0
              ...
2019-12-25    499.0
2019-12-26    489.0
2019-12-27    482.0
2019-12-30    483.0
2019-12-31    485.0
Length: 975, dtype: float64

In [26]:
arr1 = df.groupby('time').apply(
        lambda x: ((x[fc_name] > x[f'quantile_{i}']) & (x[fc_name] < x[f'quantile_{i + 1}'])).sum(), include_groups=False)

In [44]:
arr2 = arr.to_frame('weight').merge(arr1.to_frame('instrument_count'), on='time', how='left', validate='m:1')
arr2['weight'] = arr2['weight'] / arr2['instrument_count']
arr2[['weight']]

            weight
time
2016-01-04     0.0
2016-01-04     0.0
2016-01-04     0.0
2016-01-04     0.0
2016-01-04     0.0
...            ...
2019-12-31     0.0
2019-12-31     0.0
2019-12-31     0.0
2019-12-31     0.0
2019-12-31     0.0

[2283779 rows x 1 columns]

In [48]:
arr2

            weight  instrument_count
time
2016-01-04     0.0               191
2016-01-04     0.0               191
2016-01-04     0.0               191
2016-01-04     0.0               191
2016-01-04     0.0               191
...            ...               ...
2019-12-31     0.0               277
2019-12-31     0.0               277
2019-12-31     0.0               277
2019-12-31     0.0               277
2019-12-31     0.0               277

[2283779 rows x 2 columns]

In [30]:
arr.merge(arr1, on='time', how='left', validate='1:1')

AttributeError: 'Series' object has no attribute 'merge'

In [15]:
import numpy as np

In [21]:
arr.groupby('time').apply(np.sum)

time
2016-01-04    191
2016-01-05    191
2016-01-06    192
2016-01-07    191
2016-01-08    192
             ...
2019-12-25    275
2019-12-26    276
2019-12-27    276
2019-12-30    277
2019-12-31    276
Length: 975, dtype: int64

In [24]:
arr

time
2016-01-04  1335036    0
            638250     0
            2012869    0
            1787534    0
            408157     0
                      ..
2019-12-31  1922417    0
            960383     0
            511501     0
            1246174    0
            2237541    0
Length: 2283779, dtype: int64

In [8]:
arr.unstack().fillna(0).sum(axis=1)

/var/folders/db/b8whb6yn3dv2ht5cgvvj6hgm0000gn/T/ipykernel_92822/3695650239.py:1: PerformanceWarning: The following operation may generate 2226684525 cells in the resulting pandas object.
  arr.unstack().fillna(0).sum(axis=1)

KeyboardInterrupt:

In [419]:
df_turnover.

                    fac1 1
time
2016-01-04 1335036       0
           638250        0
           2012869       0
           1787534       0
           408157        0
...                    ...
2016-01-11 911266        0
           1235521       0
           551380        0
           76625         0
           1957468       0

[10000 rows x 1 columns]

In [402]:
df_ret.iloc[:, :portfolio_number] / df_n

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10
time,,,,,,,,,,
2016-01-04,-0.579963,-0.472553,-0.401225,-0.262287,-0.153951,0.001236,0.400739,0.871920,1.721584,5.422670
2016-01-05,-0.600071,-0.463340,-0.314752,-0.233847,-0.178738,-0.007528,0.362218,0.784907,1.717890,5.017644
2016-01-06,-0.586025,-0.450195,-0.434366,-0.279482,-0.135954,0.031141,0.381593,0.834236,1.684192,5.699219
2016-01-07,-0.596590,-0.477745,-0.329280,-0.224581,-0.143455,0.021880,0.344934,0.803652,1.522940,5.523621
2016-01-08,-0.601678,-0.485890,-0.344306,-0.314502,-0.167587,0.041616,0.362942,0.809977,1.735349,5.152102
...,...,...,...,...,...,...,...,...,...,...
2019-12-25,-0.677960,-0.460716,-0.396287,-0.288072,-0.191068,-0.032602,0.470827,1.127008,2.490854,9.834422
2019-12-26,-0.679133,-0.489920,-0.366845,-0.287966,-0.181993,0.010148,0.393007,1.037260,2.389408,10.174387
2019-12-27,-0.628659,-0.487296,-0.377135,-0.352592,-0.178850,-0.032565,0.429172,1.216365,2.617670,12.107270
2019-12-30,-0.586037,-0.460991,-0.380806,-0.312685,-0.195619,-0.010073,0.380871,1.079207,2.366753,9.702409
2019-12-31,-0.669128,-0.445808,-0.371206,-0.323041,-0.186439,-0.039401,0.448818,1.192512,2.547832,11.080789

In [404]:
df_n

,fac1 1,fac1 2,fac1 3,fac1 4,fac1 5,fac1 6,fac1 7,fac1 8,fac1 9,fac1 10
time,,,,,,,,,,
2016-01-04,191,191,191,191,191,191,191,191,191,191
2016-01-05,192,191,192,191,191,191,191,192,191,192
2016-01-06,192,192,192,191,192,192,191,192,192,192
2016-01-07,192,191,191,191,191,191,191,191,191,192
2016-01-08,192,192,192,191,192,192,191,192,192,192
...,...,...,...,...,...,...,...,...,...,...
2019-12-25,276,275,275,275,275,275,275,275,275,276
2019-12-26,277,276,276,276,276,276,276,276,276,277
2019-12-27,277,276,276,277,276,276,277,276,276,277
2019-12-30,277,277,277,277,277,277,277,277,277,277
2019-12-31,277,276,276,276,276,276,276,276,276,277

In [319]:
t.columns = t.columns.droplevel(0)
t

ValueError: Cannot remove 1 levels from an index with 1 levels: at least one level must be left.

In [279]:
data1

              time instrument_id    signal       ret  year         a         b
0       2016-01-15        000503  0.319861 -0.085549  2016 -0.640242 -0.132968
1       2016-01-15        002448 -0.640242 -0.179398  2016 -0.640242 -0.132968
2       2016-01-15        600137  0.319861 -0.059753  2016 -0.640242 -0.132968
3       2016-01-15        002217 -2.560448  0.008514  2016 -0.640242 -0.132968
4       2016-01-15        600726  0.319861  0.011417  2016 -0.640242 -0.132968
...            ...           ...       ...       ...   ...       ...       ...
2170142 2019-11-18        300671 -0.058006  0.124510  2019 -0.767439  0.008957
2170143 2019-11-18        603896 -0.767439  0.067667  2019 -0.767439  0.008957
2170144 2019-11-18        002790 -0.767439 -0.064620  2019 -0.767439  0.008957
2170145 2019-11-18        002926 -0.058006  0.164906  2019 -0.767439  0.008957
2170146 2019-11-18        600403 -0.058006  0.055853  2019 -0.767439  0.008957

[2170147 rows x 7 columns]

In [269]:
data.groupby('time')[['signal']].transform(lambda x: x.quantile(1 / 5))

           signal
0       -0.640242
1       -0.640242
2       -0.640242
3       -0.640242
4       -0.640242
...           ...
2170142 -0.767439
2170143 -0.767439
2170144 -0.767439
2170145 -0.767439
2170146 -0.767439

[2170147 rows x 1 columns]

In [263]:
data

              time instrument_id    signal       ret  year
0       2016-01-15        000503  0.319861 -0.085549  2016
1       2016-01-15        002448 -0.640242 -0.179398  2016
2       2016-01-15        600137  0.319861 -0.059753  2016
3       2016-01-15        002217 -2.560448  0.008514  2016
4       2016-01-15        600726  0.319861  0.011417  2016
...            ...           ...       ...       ...   ...
2170142 2019-11-18        300671 -0.058006  0.124510  2019
2170143 2019-11-18        603896 -0.767439  0.067667  2019
2170144 2019-11-18        002790 -0.767439 -0.064620  2019
2170145 2019-11-18        002926 -0.058006  0.164906  2019
2170146 2019-11-18        600403 -0.058006  0.055853  2019

[2170147 rows x 5 columns]

In [247]:
temp = data1.groupby('instrument_id', as_index=False, sort=False).apply(factormaker1)

In [251]:
temp.reset_index().set_index(['time', 'instrument_id']).iloc[:, -1].to_frame('signal')

                            signal
time       instrument_id
2016-01-04 600895              NaN
2016-01-05 600895        -0.010790
2016-01-06 600895        -0.000272
2016-01-07 600895        -0.100118
2016-01-08 600895        -0.120674
...                            ...
2019-12-30 300811              NaN
2019-12-31 300811         0.100106
2019-12-30 688078              NaN
2019-12-31 688078         0.044990
           603109              NaN

[2283779 rows x 1 columns]

In [199]:
self.data = reduce(lambda x, y: pd.merge(x, y, on=['time', 'instrument_id'], how='left', validate='1:1'), 
                             [bt.bbt[i].data for i in [1, 2, 3, 4]])

MergeError: Passing 'suffixes' which cause duplicate columns {'ret_x', 'signal_x'} is not allowed.

In [207]:
bt.bbt[1].data

                            signal       ret
time       instrument_id
2016-01-05 300482        -0.391123 -0.023501
           002071        -0.720484 -0.087857
           002517         0.844297 -0.105501
           300327         0.604330 -0.107430
           300016        -1.214685 -0.048128
...                            ...       ...
2019-11-18 300671         0.013778  0.124510
           603896        -0.382047  0.067667
           002790         0.418145 -0.064620
           002926        -0.028384  0.164906
           600403         1.329249  0.055853

[2192622 rows x 2 columns]

In [194]:
bt.bbt[4].data

                            signal       ret
time       instrument_id
2016-01-21 002491        -0.502006  0.256972
           600841        -0.994318  0.014726
           300445        -0.037668 -0.152807
           600382         0.114090 -0.104774
           601668        -0.488799  0.003574
...                            ...       ...
2019-11-18 300671         0.982672  0.124510
           603896        -0.710586  0.067667
           002790         1.509225 -0.064620
           002926        -0.615777  0.164906
           600403         1.640650  0.055853

[2158906 rows x 2 columns]

In [109]:
self.data['signal1'] = self.data.groupby('time')['signal'].transform(lambda x: (x - x.mean()) / x.std())

In [127]:
df2 = self.data.loc[self.data['time'] == time][['signal1']]

In [141]:
all(df.values.round(2) == df2.values.round(2))

True

In [118]:
df = list(self.data.groupby('time')[['signal']])[0][1]
time = pd.Timestamp('2016-01-15 00:00:00')

In [107]:
self.data.groupby('time')['signal'].transform(lambda x: (x - x.mean()) / x.std())

0          0.319861
1         -0.640242
2          0.319861
3         -2.560448
4          0.319861
             ...
2170142   -0.058006
2170143   -0.767439
2170144   -0.767439
2170145   -0.058006
2170146   -0.058006
Name: signal, Length: 2170147, dtype: float64

In [105]:
list(set(['time', 'instrument_id', 'ret']) - set(['time', 'ret']))[0]

'instrument_id'